apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production-spring-react-example-tls
  namespace: production
spec:
  secretName: production-spring-react-example-tls
  dnsNames:
    - spring.demo.tahmid.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
