apiVersion: apps/v1
kind: Deployment
metadata:
  name: codebloom-standup-bot
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codebloom-standup-bot
  template:
    metadata:
      labels:
        app: codebloom-standup-bot
    spec:
      containers:
        - name: codebloom-standup-bot
          image: tahminator/codebloom-standup-bot
          envFrom:
            - secretRef:
                name: codebloom-standup-bot-production-secrets
          resources:
            requests:
              memory: "2Mi"
              cpu: "15m"
            limits:
              memory: "4Mi"
              cpu: "200m"
