apiVersion: v1
kind: Secret
metadata:
  name: codebloom-standup-bot-production-secrets
  namespace: production
type: Opaque
stringData:
  DISCORD_CLIENT_ID: ENC[AES256_GCM,data:mwC+Tdexl9L+9wm48lR+XigM0w==,iv:XMOqFJaB+0dnIjz83tIdKsuUNG0zcguaYcd7RtO8QHw=,tag:KlWSIlT6e4XjXYAoDkMRuQ==,type:str]
  DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:LRiCER21FosVDDPSFZQJL9o+jPAzC4wiRpX1G67dffw=,iv:NPcva7gQsspqDvA3IN0UfQJPj20jBFXLPZx/84aILjc=,tag:eCBcQOgzZ4DwTvw1GzJjmA==,type:str]
  DISCORD_TOKEN: ENC[AES256_GCM,data:sv7UnuzKgLUQYOoxCU+hyJdvImrJRpTEVbIn8BWZwiAYd1tf2UOWjQaOYGkxyfh3cav/ngo4Hnp/glTZv+lPws5llsiyYdt4,iv:KqWl3RG3OV8cdUmyy0aMVDL9erVmgx4KkDjniphPi6U=,tag:5+6Z+yk2qU/iltsa68isjg==,type:str]
  DISCORD_GUILD_ID: ENC[AES256_GCM,data:5wppfpswL89Ym8R9jS5rnDUQmQ==,iv:VuhNC0Ocjy1d/ExsB7mkAsatSAZazU3DZegBmhQbuGc=,tag:ykEvakITpMc3VTDeCwsewQ==,type:str]
  DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:YSFWgGs6NA/lbmR6tM9ua2fUcw==,iv:JsqhkMcR0L2NxBCpZO5U2rLghOQo6ushVY8oEKE54Pg=,tag:HoP6p0luf8xACAE4b8r3dw==,type:str]
  REDIS_URI: ENC[AES256_GCM,data:XdVwpSPoDaG6anFsH97g/cN5SEvLXyzGge2iEzo4nR5fZFP0kCI5pM94J5+FoYLCsJAUWv57dUDiZMU+NIpGhDRw+LrXvNaqunWrUQCClTyxxk0lm13QbdsZLGWkBcrjE0rhMLoWi0Iti4XpuI5YbjWBDNA=,iv:61DIXZsRuNhepJDOM3Yd8E+KfMQoa8vj+NuwVO7uDVU=,tag:kMu5x8sToQNve7qaM2OYqg==,type:str]
sops:
  lastmodified: "2026-03-15T07:21:29Z"
  mac: ENC[AES256_GCM,data:t/O1dxMBlej0rP29kEizlSTFQkyrGCYujqlYp3/oT2hD/G3hfhLfUS+Q5yUdx5jw0GjncmrnzVxb5jAxs197njt+oj8c0n5lvPoZpCuVisZy41A4NGgTPCBNusGGRyJiuGg+Yzrxtvyj1MYtJroQUQIkkvX4F1kGhb+p5Q4DcbI=,iv:PqdKkxD7rMohpokN5FElEFj2hx9YprbNaKeYr10luqM=,tag:/ILIu70OZePPs/AfwxEGbg==,type:str]
  pgp:
    - created_at: "2026-03-15T07:21:29Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ/8DH6BUSt272NRMvEo47HhpWsvTbxs5C4pC+UgY2cbAX7e
        PqwpVf+zE27FHFAs8NZ5upr6hP4gicoqunkB55BibQRcdRbSs3fdY8EGLNyoV5hv
        AqPQQ70BjHL2sW8YtjluhPe8KRpEkDIaZd8kV8N0NJqPAhTTXiZP0KgMJx1q2gGl
        S89TpJZJEuSqK5oljoy5XdDkxn3BymR8Y7/hIbc/+OOdBapefjzaG6LGYSrLY3Xv
        xyhizKpqO1x7YLJNup7Gxa3P/m8xJkuAIoDvF2jpz9KXjyeXkCEBXi0qAHNjWDDp
        pqqKWrwQaNT7j2whUbFmHyONEqYwKJzlxv5hvPEinBxNkOr7CEDmAXl4zOvs1uBz
        M5Y+Up3REk52kJMO7o1UuZOOR3K5z8aUQ4dSAZS1ex2vRH+WqSkmbj6yd/SrBFtr
        BZqEYnficKII8KjFTJjtt1w4ToNDORlh4fMVhinMe+CRreDBBtfE92TmFrPLir/P
        7DZ905+2HAIMV9WrJaEjGDtH6TT5M5EBKCKixsaWfvtZCTEgNdlpSMAZd39fV1jT
        C6O1EZN64OS2jD8EhYVJ/WEcf/z+MuoHpBovAZBXhkDynJHgZHfeMyNWQL+/thsb
        IF1iOe7HhzE8N4kU3CCHS2pp+x0loH4KcWZKm7yUlzR20kyvaM52/ToswFiMy/bU
        aAEJAhCXxKHypq+NZOTiy+bpldC+qtV2lmVvU9McA/F5mmQnCzUnlXFZhmoCXgqb
        QzPsiAE8KN6Ug3BtECVgbOkbgjxnslAYVHd04qneXIliWskft3GwknzRb/9qPtDg
        oTRlJ/BurLDg
        =BrX7
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-03-15T07:21:29Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ/+OtNpFOwnHEBcX/r6VQNndhSZk6YnCYI1LaZn0+AzFd25
        KIyWl0e0vpgKFXVdi61MhievsI0D2sK8ROznSOwRtsz0I5IrQoI1iQ5Kdi+Yn3m7
        thRAhMD7wIw0DzohmeqXJ0yF5tcL4s3tOR3I6WbhwrN4MzK6fQLS8i+2wl1/GNYN
        ljWjBNRRWnLBK2E44H3M4TmJYb6H7g6j/3n5aAqr+DZrYXfw7OxddgmBitzwNMdB
        C7d8hOHj3Vc/x0eBNAn7zJc2WaMB8KMmRyJg7lLdhlH6S9dd9Zi/3PcOt9lPckBt
        XN22OAR+QD2Wt6zEKneZOOc25iRw0wM1krP0xBnzJdwVP+06mUBOtRICPInF7e5s
        Gt9No5l21Fp/HYfgGUTj01GqozRtBhIwrq85AXSDLqcG7tUU7LgP5SlqyOXzzZ87
        WEkSm3UYHTdyOHrTreMgaMGrSIAx+LMspdeaz03ecBkVSgBHbR5G352Mpky0+RVO
        YET9SEVjOvYCkuuHmS4tAqaW2ZLlW4/XQ5ZUnbrRLltzoF1jDPAQGav5avN5FNYU
        r0L1LaMks0udSxYCxgwYep5udivyIyrqFt5NnoB5gQAqEbFOyBrR4AU6sMhNWpVm
        NcqJs8oVn3TxdktbfUyUTUTd2nqeCwxYrqnhRozyu+5QI9HKDepkbwDMG7LXmhjU
        aAEJAhC4zJfzl8Mef9LbAUUWzOGpMpheGD1pzJ7+7HZTkhjfs2kVO8etatC7tKKO
        +q2LXV7SXF7Op/oq76lAGVjWgIlZYZdwzBK1GjGoy30084Ix0pzU0PmfmHBj4aN+
        Qt51ufaKoaqv
        =KX8Q
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
