apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api
  namespace: infrastructure
type: Opaque
stringData:
  key: ENC[AES256_GCM,data:bDKiFNDaR8JYv3EDGIcFgidOxClo39+jm6CdgV+lLHnsrjo61dim0Gz4KVICTuwMQMjP4GA=,iv:jM97BZPVPffR+4mMntdf9Lrg0O1LVHihp8wQKDxEwfI=,tag:xiasU5lMuzPgactytPnEPw==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T17:54:43Z"
  mac: ENC[AES256_GCM,data:5HPR/ot3AM3AkLOeX39gqS7WTqihHrWVrrkG6CrkUCnK7AOX13QgYQN4BA2LA4p16sRC6UbWnCHcQlQ6ff3+SK4vOz8NlepW192R6dL73Cg9RHl8HkoPwis58QHBlZ9I1IaZyoJ+0i1Xl7a+6uAj7MdRO0r7nDhNmdB8MPvtr30=,iv:4EYvKYmajD306bYKUuT9olTgHZT5NsnLIPpENgFuSKg=,tag:UJ/SrqFXb5D5iZKrUNAEjg==,type:str]
  pgp:
    - created_at: "2026-06-07T17:52:53Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ/+J7KZ5LBtm3mxrODFtxFysjniakgSK/Xnje1iVDcvactP
        XP140nJfrufn9TrVURqZMRJ7FoHdUarBfwt78xW8y8m9AHoxR92zd4vLA8e5gXor
        fy7VXHS91wV9MfqhEuQ6r2gr3V909TkiSiZ7Dg/mLkGU7lZ8fhS8OolGepAQGP2d
        oO02qmeYpGp/KgCdoQEEkDa9b/lHv0WP/TP49j5kIzW8d49lLPlPiJ8G15UfZeqS
        BabXvCYkpzliBCQ6Xi8N146FdzxUOKzLuzcLnL1dCw77BU4m6rCYGJwsTrpY7Hu2
        irIj74kyXFHFB5dKQEah4RZ5VtSpJiGwqIl4CVV8P4SARB4as1X7M69nxXMuPxOA
        FcpScJelWOwX2jIPDYynNApQkANFgqWCwBOxzil0x0q+QBuEa5jC6MyW0yr9onG+
        yydJ8Bmsan8NWufcb4HqPg+CG3KQwd2ZiN/8FEmkz1vIPzOwn0gANLB8VydBbj5h
        NS7qsPbhdGooG4eo8r95XHDG6TDqyVzqo1IVK08/Brvc3XQcunaXkPAVJ+4O7uvw
        4rSAQkQuKBfHe2BfhFxmGBmmHcAgADfXS1u3roaJYoDZLwyW3/NS+arKTAbQNYIv
        sUHURaIoxxasknOlccl9j3Mj9BwmltxhqAMkFJ91SHQ7CDj7CrQ1bGGmAQiAoozU
        aAEJAhApzjTFHXkkAO0ScZsSEvYNMbh09A/KRIFj174FtRvWPY0IL9J8wJAmtyma
        dBLgQwm58SYBNDAjm4cT1gDwtEbCf6IWHyCn1+DV6pqs3Oar7VvxZhkE/oWeRk7J
        LUHxR0waTTmk
        =CvuZ
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-06-07T17:52:53Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2ARAAjqFoNzmKT7CORJ3TNX2S6w14TZxSouFQh5HpQReg43ks
        vIx5nBsPNivtVxbJ03jdgbk1DupdGp4U4M0M7NIbpVIDHsOhKYRca2Nz6R6xXu5F
        ER32Uwo9v23SyhU4kHl7/Gm9p9Ce0jl0N+edgqe1NhjCnsZ7/rggc3lsbBAwvqI4
        9hswjHslh94xiNYvrgaG7hlHMrMMclL4pS2ffrQq0TGtyraMpzTF1O6+gkcB798p
        Z7bd+V5mqgRzCVmExyyDVslA+mSnBJym6lsmSNUsWz1uAZKH/j/OuDz3YXcAeZSW
        bLnrN9VnC2EKE2OUCYNkTwUPQX+Atf9QN0MGKAqOXFBURhMO1ykPTj8piDdbbuPG
        bfO/xwD1ad6SiunV/Labd9LCQs6dk10X81cSaXeEMkCkXyYccsmZzrWYE34nMqbI
        RG3UAVRfhKgZzwvwNw8PvLztXJTDTJZACcjs++ggC3aaczS4vP3unpvZ845c/wSv
        ojElwab6SNzJVDOtpqBY+nKcPsxzdbzp6soh68XrEXjLm89Bvd/L/+z6iqVpl+mZ
        4lH7009d4Mi0aDFGBaZEw02DlG1S4N4AvjuboqAXJV34i4WwTNdJJGRLkmFXS4Rz
        oq0UpMRDBxsJXZN4wtplQdrz8b/RpF4+9WplhdLlO5RHWXGGcN+h7BafJLkckZHU
        aAEJAhBWbyoZvmQfaPxNZY+rHjPCCk6e4VnYVsFMY+q3aqlpxGs3T7II1HtmuwZk
        7pl/OtyRnqlDKYQZzwy5IXNmZviDOdwDoFGoSxva/clsU7yH+rtYNauV2jHxKT7d
        S0vXpYN6gQTo
        =qXQG
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
