apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1h
  releaseName: kube-prometheus-stack
  targetNamespace: production
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "69.7.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      enabled: true
      grafana.ini:
        database:
          type: postgres
          host: postgres-public.production.svc.cluster.local:5432
          name: grafana
          user: grafana
          password: $__env{PASSWORD}
      envFromSecrets:
        - name: grafana-db-creds
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: ALL
          defaultFolderName: "K8S"
    prometheus:
      enabled: true
      prometheusSpec:
        retention: 30d
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        scrapeConfigNamespaceSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
