apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-creds
  namespace: production
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:8HjGTDRYvoG9FlhJd/Z5,iv:tUTSShjyhYp0tZUduQ4+e+3s2x5BfnrS98xSorhKI7I=,tag:Hlyk3AjZu81lrkwbWgMwMA==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:1JQUcjvAShw8ooaojip5AWUZ,iv:1HZao0AzWfqURPFcoARzymQzwKXP9HCTEg8TfXwp5hA=,tag:cDgR03HPn5AOQs/xTlTyVA==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:z2HbNWNI9OT9rsKXAZNna0I=,iv:XOWjvpcOjBZtXH9urpmLNlc/2Vly0jG438h83rXroUE=,tag:CrPAyEp9nS1JIRYvmve5Vg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:Q9R5d/IT+ga4d59Qa9PG,iv:hk11kGdBm7cl8/cqJU7VvkWvHAJ1+lQH37qcWopMhUE=,tag:PKxKzm+fIt5wkPDgrbtPPg==,type:str]
sops:
  lastmodified: "2026-03-14T04:55:22Z"
  mac: ENC[AES256_GCM,data:av4wVOCU8GYZvl7y4wn0Nmmhc5N9yar6CouFXf/QJXpkadBKvxHbm1QQZQZ4zxWqi3QmZvFXtSiKqWwMbZiOX5eQW8sZKQTmehgmZ4WhtVrndVmus/DTg5JnBEjmhgQrKiJocLPmeuYZCnPsglIm59CiSzAbC74cj4Guv3tGbQM=,iv:SfsQQ+UeKTHUhVOmiX5WmsdcxzPTWD5xF8YYxc6Wa1s=,tag:2OZqf60j0sIdOi/r5kmMBw==,type:str]
  pgp:
    - created_at: "2026-03-14T04:55:22Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ//UNryxg100IVFL/+S59SmmP+5WpAzs/yicSMo+qstCu/Q
        5WL7IC0fzga0mdmJcxwE0AidgdJtQDP9MGZxpKyAdJHihXXp6dXiRe0iN0EVyZ/6
        15/Xh2trLPZizQO28PVaREi5duZ43wl4MYbScAzyp7PiTQE6MEFePcoL+8fklBbC
        4ycfpYiguJQ2+79rTVfT2PlfpveyiqfsQp1IEm9OpazeV1vwMRN4HAnGwosnf9h6
        C/xGXatlDagDTQ1Zc/SQUC+bkIbQOgKYdLbPsJ8fwUmBkFc9SKEy1vOBHSMiBfzN
        RXSIekcM2AsYCJLKdoQ5LKc9JgsM2CtxywJ+hTHU2W9joMm1KI/eWFhKgQGnVeaF
        PpJzbOzEgohlNHHcy+UtzzVnIdVmkXyt9wEp9t27+Zclg3soIjVLFQmBcKs575NW
        fuC7QTRnx/XpTAuQF5ppM6wUPzTXvn4+ndHHOymrIj0cJzvCMefS2FaCCf9YVdZz
        43TUfCtC+gTagUk/0w8ll/ZZ4DE2OCGa0M9ZGhoHWCv7yHdrafP1hEn+yAboh6OQ
        TQV6PpfT5lrDVr3CkvIYy9PZiDNUaIAH3OPuGwHHdrqoy9KpVoNcpoJH77aD879w
        /rsbilK/wxdPK/WYTzsVn8znfbzgfHGTVlEorSDhQYlzPUvRNO7ZLa0aIVMpPPrU
        aAEJAhB0KTpT5QHWtv7ClrnKxiyxlLCysyDkHudvLnWHSzpN0lRhNJJ3bkwaCFC7
        y/WghIKGdG33RiCLB36e7ZGRrUOxJp0A5COgxr5PwQpRM4+rdgRgIABFXgf9QOS6
        2m2VrdUbmcH0
        =8vy/
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-03-14T04:55:22Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ/7BSinBrZyM9F0ctlHfTFXinP9DwCTmOD/yG6f4qzOL59w
        ELGxdMZ5nsDbBcExjkqOcdkfGPVi6vTqJeWHCKU3gnstFzVHNEMAvU63+VCohLE7
        EC1B4rxCUEIkjdFp2Ok2zpHxxaKY4nCDJqfBEY3IZhE7BWnHktAPdnMS5ybWhh0g
        RNs9uBAhQrocVQKuBFvZY58mrBHrJ5Z8wC/LsMKmgjepr/NpD6I2IzjC3ljXSvD5
        MQmhtnJ3lFjB1VTYioywDNgLIIuXRDzR1uJQhL2QrTrqeiwjpyLC6NeM6sl3ESdp
        x6Cfw8vKbvIRkr/6fqn2RuvQBajIsFVLmxUtBpAnUApBgc59v7Pnr4Bb0Y8TIvsP
        NlugROdRwymD4n757YFBSNBete8gmITG26DawFeh9A/NeZaqlOQyHb/C/yavrSg9
        nIw/EKOi9HdFSAOBbW3vZHyiu7QmagRNSt4B/dRryIKRduG3crx2CluN/9FaO8rt
        ok0orq3f5gKd7e+0Imdf4At7Nqi0ldCOtt2knYZB3xuJkeB2smAdaTOj2YWqnsNu
        39BHDNprvYdN60lHNmdGYQfFCY1Mb1hZd8h7XdvkSDBAdSRj3JmKdu62IPbYgyUM
        Ay0WlBzsYINYoDENA04gXpakQ/ndC7tMuH5/IKYJdxaIpbsOnUbGHvjs82OuGlTU
        aAEJAhD6sQj4Ig+jw/4JWUUAQPSE6e2Dk3RlQiKk5dYp9jX0ue2187Qb1juF9Lbj
        /Xa7Z+41YxG1cRzJM+yRpYYbreq6eEFyV+yY9drqL0xG10lzolgig+ah/Lyi2l72
        b0kja7ip2kLY
        =u9yg
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
