apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-creds
    namespace: production
type: Opaque
stringData:
    PASSWORD: ENC[AES256_GCM,data:ukkTk4y671WKYglevjPj,iv:HGKDqJ/OXX6RiXq7Sx6ul9lgmGvhWH5lzd8S6Qocg6w=,tag:go58Y31HPUNcBkz1QbfjtA==,type:str]
sops:
    lastmodified: "2026-02-27T00:38:20Z"
    mac: ENC[AES256_GCM,data:1JRihkevLudI6D1tWBmNwNIyMtIEAknBFH412nFJmeh9kDdN4wFGiuWrpq6KhajrnA/equLAKnPO6JD5idEdf9pPNWo1m0HpBErVr8JwEltvKWRdtvkF2CjVeqNtf+0iig3rI7v8ah/D38eXGmnW5nqodn4YatlPWumwuAbhCpE=,iv:0ND4Q8zpYo1hXHDDc/J1VSE0LBg5iuwFQzavssAlRPY=,tag:rASoMcm5+og3zu0Qtkvjag==,type:str]
    pgp:
        - created_at: "2026-02-27T00:38:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYgP05NwJ3CAQ//T4/702DfCUPQ08zF9zrg4WpVyA7GnS0jRVYsfEwx9ZPn
            sOwKudx5QuzIRPxmWKTL+JWbUMAArbnzU1VNI5eZahP1fP0hNBaxdAWPnhd00pHs
            3sjHPUPZZYhNRBv8girCz5+6+9ZqG2R04nk3Mdt4SlOdKl1XoyUzJ4xC24DLZLky
            vThHQ7oPI2JRC2FPVFCS6Vs609Maav5+YQ+fV4gNa32T3rw7Jao1v7fkhZ/AqMXu
            DeGhzdhMvNBBQWcjSj3iyMdOQxYEHjFoYq0CY6n6iLx9Z2IiJQgC7rqRjP9kwzJv
            bBBrd2uV8tiHYJInRtMekPurfXBGP0hLKLZS7De85hiMOMY5h7K8gEzIpoTDQ1LF
            f170sQERA7kSRg4FqUCmC9jvkWg8Hww/uwVIDjmPhadvshgLPGrVXmQ/3jBVHo7z
            dZRWmomx77qgBTETwupfBxiPGk2Te5ttubtsjkNQq5fjsWcxyuHUBPKMn5vokSVy
            s9dEjDtmdyyoiQC/RKzv7+yidtUCW5vgiR14iu9Yjy7lO07GlMuS48/xcZLfFbYB
            LJZMEh+VVrLaTw1F4pN6ej16s035AgsjcJyvXIrEw7D6InqOajqcoHG/P6HhYhKr
            h6Jq/dsCtVi8ehuqB5bJAvKo4isg0qq5NTogGMHlwaiirzHdWXqD00rF2G+tWwvU
            aAEJAhAzjlXyOGTgglHjTOUxC9YHjSzFCz7uB8/qELpZXOsTZuN5fFarn0dEP1Oj
            u63RQY1Ws+Qaw0+iogQiN4INL2SIUdM3sX0nhzWp1r9LxYTwk5wddce2P1fzNoG9
            9pPwze1vyFty
            =FIfz
            -----END PGP MESSAGE-----
          fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
        - created_at: "2026-02-27T00:38:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7m5W8M9NGm2ARAAgidiGBR4Wv9lTWZQlRqNG/1CuBcfZS6buPx4+eZaZPZA
            bKux1Gffhwd5JQYmVEKwBV26zQ6Ct+22UBi7fDvr2Y/hRrB7B9xQ5fwtZqim4KXR
            UFqbghuFY5Ezpuis5wTt+i+ZnZxt3EN59cpcDAyNVvUI4ph/1GJvRF/mEyNV57vh
            DpKlVFG0p4jHrBj8qsRJRY1tSrYFXJy0MqLZ+mwx44UH4XZuTYsSR4Da6fH+6yT4
            fYI7T+IsIBgI8rzcg/1fGy+q+WIgoM99UBx8bmXgc6eMMNQPRaaJZcy79vWxLfV0
            0hd2lWhz40GG6Len5FT/BAcZ+4pisH1nBy9DUrKWpWOM+hTg7rAH8brt2k7VBJMS
            siC/VZPLcbr3RNrsGBTBpQUvYpI7BmykSezBKwHFrQV3VIB8X3mRI3RQ+v0fZPZ9
            KaZkOkcMY7CfCKGEEYm8NhppBadgiBMN5redid17fXucz5xfyuZFjZsTdbCwNhCx
            XNpoKBciDMPmjMyFoq/f3fWmFSQNeCqV7sKRCJsp76/6QF83TkU15bl8cFPEwdaL
            ZFjzcjkxdUCuBUvz6STilXBmU3k927Z7o284GMq+gT4UDIsWrTVus2iUMLrPuW2h
            4cJrE3BpbGZXztiwOZUy9y9NEqcwQ+SrTGgM85fKqIxQrBwOYmiL2yw4ock5mUTU
            aAEJAhBny7dz+ksNYZIoAizcHQpYw6oFyYd0mWUAQqLnKRsYVE4ztTZ4/gMvNn+9
            ghnkW3tqXK68dhOhNLvm1iZCsrorAujWwM3TnGFtQbr2IpeONLxCbLGX+TxbIOFq
            tzct+3HZkPt/
            =uFco
            -----END PGP MESSAGE-----
          fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
