apiVersion: v1
kind: Secret
metadata:
  name: grafana-creds
  namespace: production
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:U4iJDLg=,iv:q8fCDOfUHRHX6aPxwgHsorOdBzQlQuoc/3DuwFeSl0I=,tag:T3QNQOMlFk09ynKL8SWiNw==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:mYwZ9DO0nXbvmALmUEhMmnVJq33KoXtFboJXTX61ClN8vq89Pb0OKg==,iv:0XUx8wntxmiKmbLE52W+3i8shUu/NTAZkMXkcD+LSZ0=,tag:AXMFCSfp6V+Mi30VbhUsIw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:OFSW4N4sL76gSvdTHHVt,iv:i3XKyrIyNsTCAneyu0HDAtWtlsgQwz3n1iPdsULXMQQ=,tag:YCwFbyKxvbeTpkeU9AsiHQ==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:0T2Xgw5ItYABlIJA7Cmb6wie,iv:9gF9Zsn22mFdJSJDt0B6ZjDeVL/w2B4rQBOXseT8IbA=,tag:G2LkTvpCzcfo1cdtk0vPMA==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:s3sBwEMuo98iPUWtpphkhhk=,iv:Vb5k70Z8dNL7RSFtZ5Z1r9ptWTyDhaT9RvQZOdONyHQ=,tag:4ka1xzUS9r3mwBDkW5ZK4A==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:YnQrfGcycI2tnnXO9Gc8,iv:bFIgHTU7vMaeLPr2/VmiLSgcSJv3iOBJ+80qJrQhG6Y=,tag:VaNvj5x3Gv/6VATcPJ58iA==,type:str]
sops:
  lastmodified: "2026-03-14T21:38:48Z"
  mac: ENC[AES256_GCM,data:849SEa2itK/DdQign/mygG095iwzp7Un4PoJ1S5xXMqgw/CESjCHpuX7cUYGcyxVqVTEqYrcGfjSfaTpQzUJatk8tt1kOWVeeEOQeBX6J+9Dx4XehLyGaGKzs4Fspkhssh58LXVW7FBuROJhnFw0Z1tRahb81pbmbsEZToKeE0M=,iv:BmVDhW6CyrDnghW1f8N9b9zVyM/v09W3ILYIwxx8oRE=,tag:T6e0zkjFf+xnGawaddI0Wg==,type:str]
  pgp:
    - created_at: "2026-03-14T21:38:48Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAqpVebbexrU0wR/KdIwOkRH1pIuOnlhf/ZDn+uD5HTJTp
        o3jWsuS0jT6JgQQO345upHF6oD/fd22uTJz7Bwf7mHaUfOrHtVV60sHfi8TRAwXK
        ITf0uVzgnX9fUOjhtWE/sV5V1y2EXK1THxuNd+nHfvRqwfYSqqI/5B20aEjdd3GV
        KMeK2GtykfN2zRPM5MThYcb+ZdGXLRjXCISrLsEhbdFFJ/fivcMInVZzwNOU+2kT
        wlo6NlUSTF4xpn+6zktShpMarBkaCCQYOajGlLqXMlZN8HGLjTSJmAGyL1zpZDsw
        asghrLw17f8IN4PC/qeije13yhoj6Q+n8DkfO/ZzfgSzLPuDt3Q3Od1fEwxkblFq
        UALZq4PPKbeOVOqYSWB+KNiXRX21v51OOMoTH6c9ee9W4Z8bhT8Tl6WfkJgwR8Yb
        pnMFDW8AFkr4WPhf3eSkmk3suuvexg1+12u4hIpw63mRZ1y9O6+K2JvKSxcEwf0X
        4nxKxu9g/Fn+bavwZkWP5qIaPOKAaB08yawGQ8ZwbfL/4dQ6VxL9GjK6lnojUQj3
        XY1QfopZ1rlgUgnHlkLPl42dt0WfTrZls19v9jTNDw+EFX4/iyTy0GWsbDtSpQQZ
        zaUfCIVu2x4R7jJQOTVYzowZnBxbIijTBhnNInz4VV40LFOh11wx6Gh2cY33mDXU
        aAEJAhCJCce/gPhf23DLPn+TwXbow9E0borkvQxoONkTYTImREpGO3fiXg9Ej0R2
        UlzT+iiCcfuvahCm7gp9+CHDTtaF7jykLldGIdqeYfx0J2lrq13j51U3CrvNyYH/
        cg3JbzkUKjcg
        =h/K7
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-03-14T21:38:48Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2ARAAqJYYm0xVZOB/gsye3cbQU/Bu25MT47p5wbCU3yfoQpk9
        4WrAXtEmXcHFTNJ0gyjGy34NOXiQqkvgzVgrvyqzs/zM+Wft3cRs+sJGEpkn1Ih7
        rwFvUP8zPxnhzAdgnDvzLsU0pFlvXlwcN9LOoTGfQTnVBwFua8QeY7a6SkjKdXdo
        /2B7O57Sy66Y3YQRz6RFoVsp2uHn361gMBzfHr8K/+RSP7OfvvIiSsI5KV1Oain9
        +cEOq5765rfsMwSAvBltidYQ1YXkwp5TBEi4LqkLSIHvINVAhKlLGzVLPr7MWuY/
        996gEQy2xkQl/wBlyCKtThy1qw1l5JA1zW9a1Grk+GIesx2yyhLdiGTmlBe66BIm
        CRtNnTPlgo8tSJHj/0ZIDzl6u8QWeSSo/nyWpp1mkXTz6g55XymYX5T+iPUdA5q4
        Nd9UWp5rEo0HK8rAnvVr1DJi6rfCJBTQ8I1nvD4b2eEDSIUE6byEAqSLGbs7757i
        GsOND2y8CAQC8FiuIpdK0R2lDsuWXwqb8KEUwCecbfUUCMecfRZTIpueuh6uIk/g
        4/Tbw8vZ4tK5yL/UBE/WALM5IrYGyuI5WOQ/j7EgwEEwiLUWeA2ZC66kSr8Za0lD
        2hrUnUTy366YsIdmVPyZK43UQOKHcU3KR6F0ym6b5YChjE7Y2t7vOeMLmrEPzpXU
        aAEJAhD1wRgdLPC2ArfDXRsFAmpP3yjjZjI3gLXrp9V3PTTeRb/p3pAr9jYGMJUH
        dfsVBq0LdtcYeZbBNs9gKT6EG5VaF5VQBWDTHHmQFVXeAWjHcKTsuvvDQScZCgIg
        zXxwScf0mJ90
        =FVts
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
