apiVersion: v1
kind: Secret
metadata:
  name: grafana-creds
  namespace: production
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:bDdZQpg=,iv:ABQotxiw7H66ASwFDaghwm0ZQ4y9Ab9dUnA/LqlIxsQ=,tag:uv6lk0Wy39j7M/F3ATCFEg==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:Ir4BDpniIC+vGG7OkCKEMOeBUx7MeQuq9MiZ5hm2Y+kXgln08+Xndw==,iv:MLZaIK3xu8RGzsSGln79gYgxMDmpdS00gcrPB50tbdw=,tag:MfzFyT+E1D0DTDIm3yhwyQ==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:jnqBCpNoPF7gC5VjWFLm,iv:dsI+hzzoUyMCQc2WFxkaWnUShHSof5eaJXdRHv5il60=,tag:VJMcOVMIbNznMSRialbjDQ==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:z3105wxd4YWVrJ72Y/m60cTJ,iv:V7MjHi0pwDlUOwBOgM7rde+HiQDbjO9JbwHG4fBo2Ao=,tag:Y5DCpk7qbwuyGQv2ascgWw==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:C+Kw/LIjJw72ysULNpIrOrQ=,iv:Nhp/q3TUizX7XpUeSDBoV2sPitsdkWlGBhG7ZALBXuA=,tag:QnCZLeFNqFJkCK6EbBXbOA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:GtOX3qFWQubC25oryrpq,iv:OwLrXapJMXpcdNEQLWFGIE+kQ30dXKCA+1u12umyEUU=,tag:eEziK/G38a2pPD7kvNQajg==,type:str]
sops:
  lastmodified: "2026-03-16T01:12:43Z"
  mac: ENC[AES256_GCM,data:FOjSHrP9T6RYC8gAXhKtwXyhiSEfTjjqycrR0Oeu5q7umVZfKD8tmS/PUzG7qMqOsJCYViwLD4RFIvr7ZYqbO98+NVh0gfw49Dr5jE24ycNR4jnF1rmBoB/fHYOWfiizGOys1ZUsz+PHgrNCEZswgvYcqCp+L5NCcMrNUxZ6v2s=,iv:k9pA4HsSkm3runWog4bFLJdOCmKVu2sUDmCzG6G/zGU=,tag:NKSod1Qu+kx1g3jWDuYILw==,type:str]
  pgp:
    - created_at: "2026-03-16T01:12:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAApI2WsAdTSFLJeFXddOkqgM2yoULwR9WdAoE6oLeJ2Rpl
        U+ZzS1S4asruv95zbs8kc1Bailz4toVzKJUefLjVs+OCsDBLshuL/2FvnztvVYsW
        BMOD/CjF5afDXrg0HsicP0LJInsGVzs7slH1Z++RCrztYGyJofHzTd1VxE8O14s4
        MfBwo/6KwRkTLdKZnqZqpEji8dwH2eJ/c9pOqj8G3OBjpQaa1UgQYUy8wEqvUFAQ
        ceoqbgc0GbQzLMDDoKR8gG6VNKiTmOW3RKT2u/0W/ldtb5Yu5BDCY4tt6xTkVpdI
        43H5FZBKUVC8ZPyA583QKlDrPGK7saAPYyHAAbJ8ANyJz6+QlFVd3z5XfnLlVwzp
        snOgLrhrm3X/AklNt8TaL8TnEc9ysWA0mRtAPz6EJaY77y8H+tMmwaZPS0lrlzKW
        3P1JX2wbyDBik7IWJDu7hl5gEcMSXfsFy1gO3TGc2ExVBU/SnpXC88wuYuGV54Ma
        kw1qWxK1LzeaMfCMeIFx9ZzIbbgDH7rQBHPe5sFOBgi0h8okDLAc4FpzYf/EqjWM
        WoKgkBN2/cDXogHjYp9V6FYngC48YCgJJt0WvqiEKOH0PpOB2u+Ri2nnkSeHYrWV
        QGqaNbLmRnEkJIfFUf0I1ativ0+wBYUMydUBamiKdzz3dUFom3q6RQMRzpDKgWzU
        aAEJAhBXq359wAhl5dqT1783EuNmdHFIpGHkDogdgc1JicnkBJkMLooH2YNUuqS/
        tX6An2+YwwQdxbf0awrNBpHsA5ktp3oUTkT9jWNiI6BfCZRpdGL3uqn8Z4TYBJSp
        YfeuTFK4drlF
        =8bXr
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-03-16T01:12:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ/+O6LFZxqU9ZFHieBM8ImulYd4q5nwn/klAugRNlDyr2Zg
        yBcBrTx4hJgAqSy2AsvNuLJtrZsvkWBxmko5hTM40HlqZoPzXVtvG2Ewtvce8fFz
        ArHoDEJKwH40noq9uiCl/aBTPz3N9dU7B9D0IU221YZirxHvkv8vfTtTUGw0fXmm
        KL8DPvhJUI5L+dFKAN6RF6D6IJRlBV7GaQ89JcbjvJbwduWh5e3uwT5Z5qO42EgC
        ssZ56YcimCk8MfpVIhnalxhXIuvStvrkK4FGu/FqtgQ90ZIW4e5u1dT9AgHM2cPa
        51P8FXxqKRLQ70ka9AJKgSP7YPRhdFAh4QJuUtpXZpZYt74PlRMOLu2Zn5mflvOY
        HqS7kwYoOB6srNvs4r4MpEMZF0nXEbiaWQpM6ASzmTB7pkvc7cI8B/HE/lkiIY68
        yDg5xPGwRLaW5kQAv2Pq+Lhq31VUls8+M7lqlNJQDjN1Lk0zShG1kFVGtknP6PrM
        S6L+G3jSxwmmefkBnjtf8DORde5JFnE5XOuTQ+ARX3shG1Je/NdgQh5x5H6Rlv4q
        jmDDr7iOjOrYhIOtvgoAcOjr/2qhwQOPyNm5nqQWnsygst54LnlbdWfFu2CTOhya
        R6RYgtL3mePcI6tXNtdbWOwlpNXLBpc1yu2U4X9sOElcIeewKN+gJJgzeXPVbczU
        aAEJAhCeun7GvkuO9kOToKAdyQ0y0taJO6+1d5RXyLbVVbY8itzbSMNodholZuJy
        mgnvY33WdIqXI3jF4WF6JzuuAc9zGYdEzHZkQXs83B/julNYztz+H/VHE6v5Z90r
        EKaT/27iNKmF
        =AUv5
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: loki-creds
  namespace: production
type: kubernetes.io/basic-auth
data:
  #ENC[AES256_GCM,data:AZNi/BZC2A==,iv:y5A5mU4ZDKW/h+CzMAR3NBDqB/JWzIV/nIpkRFPw+eA=,tag:x+KpaBhjzB3Sq/Jd3KfXVg==,type:comment]
  username: ENC[AES256_GCM,data:EnEGua71D9o=,iv:wNTjRBQwLGiSHMQQdzMicdMKZahe4xRB5xKUIoffvs4=,tag:Df3L/uBDMf07G7mIdYCEKg==,type:str]
  #ENC[AES256_GCM,data:UMn9UTYRjB5jXC4C3rc=,iv:FhuyVRotTt1Y+N2PRAaXkhgmo0sULCQQ2XsFFo+/q2M=,tag:edO+HNCDh5cv/NU8yDSZMg==,type:comment]
  password: ENC[AES256_GCM,data:RWKAT2a4vPtlxTEJ7LvZX3W80gc=,iv:JlF527o9Iz7muvNeyuO54HJnTz1lcVp7ASiRi+kngk0=,tag:MaGzR/EnTQa8XIokR/qHVA==,type:str]
sops:
  lastmodified: "2026-03-16T01:12:43Z"
  mac: ENC[AES256_GCM,data:FOjSHrP9T6RYC8gAXhKtwXyhiSEfTjjqycrR0Oeu5q7umVZfKD8tmS/PUzG7qMqOsJCYViwLD4RFIvr7ZYqbO98+NVh0gfw49Dr5jE24ycNR4jnF1rmBoB/fHYOWfiizGOys1ZUsz+PHgrNCEZswgvYcqCp+L5NCcMrNUxZ6v2s=,iv:k9pA4HsSkm3runWog4bFLJdOCmKVu2sUDmCzG6G/zGU=,tag:NKSod1Qu+kx1g3jWDuYILw==,type:str]
  pgp:
    - created_at: "2026-03-16T01:12:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAApI2WsAdTSFLJeFXddOkqgM2yoULwR9WdAoE6oLeJ2Rpl
        U+ZzS1S4asruv95zbs8kc1Bailz4toVzKJUefLjVs+OCsDBLshuL/2FvnztvVYsW
        BMOD/CjF5afDXrg0HsicP0LJInsGVzs7slH1Z++RCrztYGyJofHzTd1VxE8O14s4
        MfBwo/6KwRkTLdKZnqZqpEji8dwH2eJ/c9pOqj8G3OBjpQaa1UgQYUy8wEqvUFAQ
        ceoqbgc0GbQzLMDDoKR8gG6VNKiTmOW3RKT2u/0W/ldtb5Yu5BDCY4tt6xTkVpdI
        43H5FZBKUVC8ZPyA583QKlDrPGK7saAPYyHAAbJ8ANyJz6+QlFVd3z5XfnLlVwzp
        snOgLrhrm3X/AklNt8TaL8TnEc9ysWA0mRtAPz6EJaY77y8H+tMmwaZPS0lrlzKW
        3P1JX2wbyDBik7IWJDu7hl5gEcMSXfsFy1gO3TGc2ExVBU/SnpXC88wuYuGV54Ma
        kw1qWxK1LzeaMfCMeIFx9ZzIbbgDH7rQBHPe5sFOBgi0h8okDLAc4FpzYf/EqjWM
        WoKgkBN2/cDXogHjYp9V6FYngC48YCgJJt0WvqiEKOH0PpOB2u+Ri2nnkSeHYrWV
        QGqaNbLmRnEkJIfFUf0I1ativ0+wBYUMydUBamiKdzz3dUFom3q6RQMRzpDKgWzU
        aAEJAhBXq359wAhl5dqT1783EuNmdHFIpGHkDogdgc1JicnkBJkMLooH2YNUuqS/
        tX6An2+YwwQdxbf0awrNBpHsA5ktp3oUTkT9jWNiI6BfCZRpdGL3uqn8Z4TYBJSp
        YfeuTFK4drlF
        =8bXr
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-03-16T01:12:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ/+O6LFZxqU9ZFHieBM8ImulYd4q5nwn/klAugRNlDyr2Zg
        yBcBrTx4hJgAqSy2AsvNuLJtrZsvkWBxmko5hTM40HlqZoPzXVtvG2Ewtvce8fFz
        ArHoDEJKwH40noq9uiCl/aBTPz3N9dU7B9D0IU221YZirxHvkv8vfTtTUGw0fXmm
        KL8DPvhJUI5L+dFKAN6RF6D6IJRlBV7GaQ89JcbjvJbwduWh5e3uwT5Z5qO42EgC
        ssZ56YcimCk8MfpVIhnalxhXIuvStvrkK4FGu/FqtgQ90ZIW4e5u1dT9AgHM2cPa
        51P8FXxqKRLQ70ka9AJKgSP7YPRhdFAh4QJuUtpXZpZYt74PlRMOLu2Zn5mflvOY
        HqS7kwYoOB6srNvs4r4MpEMZF0nXEbiaWQpM6ASzmTB7pkvc7cI8B/HE/lkiIY68
        yDg5xPGwRLaW5kQAv2Pq+Lhq31VUls8+M7lqlNJQDjN1Lk0zShG1kFVGtknP6PrM
        S6L+G3jSxwmmefkBnjtf8DORde5JFnE5XOuTQ+ARX3shG1Je/NdgQh5x5H6Rlv4q
        jmDDr7iOjOrYhIOtvgoAcOjr/2qhwQOPyNm5nqQWnsygst54LnlbdWfFu2CTOhya
        R6RYgtL3mePcI6tXNtdbWOwlpNXLBpc1yu2U4X9sOElcIeewKN+gJJgzeXPVbczU
        aAEJAhCeun7GvkuO9kOToKAdyQ0y0taJO6+1d5RXyLbVVbY8itzbSMNodholZuJy
        mgnvY33WdIqXI3jF4WF6JzuuAc9zGYdEzHZkQXs83B/julNYztz+H/VHE6v5Z90r
        EKaT/27iNKmF
        =AUv5
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
