apiVersion: v1
kind: Secret
metadata:
  name: grafana-to-ntfy-secrets
  namespace: production
type: Opaque
stringData:
  NTFY_URL: ENC[AES256_GCM,data:pC2JEbwI3g1Bm3FVW7NCLve13LmRjmNI3fRwtYwUoPihoTVJ5wXNQp+pvDw3Vzbd,iv:04pvtDsZoZnZoTg97NemwhAESyAD0Dfaeo8nWMYLoRA=,tag:YaWZ9+M8i/x/Gr7krgucVw==,type:str]
  NTFY_BAUTH_USER: ENC[AES256_GCM,data:BoJukqI=,iv:98H6AyolDaoqs7vMlSuLo2Yk6HkVcUM3yHmXinw+mKo=,tag:Kf3UHGhE9TDTB3Ki/bbQYw==,type:str]
  NTFY_BAUTH_PASS: ENC[AES256_GCM,data:SQg7r1y7zJHpSdew7/o9,iv:a8vdcgxLNCAFNOJ1NczLGfn66KuO8P1nSyahZzJ58/Y=,tag:ugVunNdCrjFYqDqHZhgQcg==,type:str]
  BAUTH_USER: ENC[AES256_GCM,data:YxSKj+U=,iv:wyYRV4T2zx0zsOJoUQoO9P1ciHj+pgHkSkeF/C1NpBc=,tag:jpp4ARY6GDZSFgnpsHqf7g==,type:str]
  BAUTH_PASS: ENC[AES256_GCM,data:yFYSz2f6j7/4JzxXvfRLDPTYdUAiQus/S+hlhg5hR0PvgoXhBVZ+Yw==,iv:29wCY3TfuJp1UnlRNK7VZN7+ssSTKlxy0u/1T4exHTc=,tag:UzRxZsAsVFF/p7mDnr7Dcg==,type:str]
  MARKDOWN: ENC[AES256_GCM,data:VeT1vg==,iv:WHJXckKt7wKztMvLVn5xsDzdTHuHLo6GmoTC/Mj+CpE=,tag:iOeYRPkyD3nyFIVvsfXHLg==,type:str]
sops:
  lastmodified: "2026-03-31T16:40:06Z"
  mac: ENC[AES256_GCM,data:0NxIHovKAsvRfYueuwqOvMBuAFbZkGXLTE3pw48E+V5wpeuLlZCUvH6WwHM+qzhIyC+VfV3rXKYQsEtwo/H2L26NYYvRQ26moheum2Va7IpLV3+Puf2Soz+hfjFwtexDGSb9oQ46MyxXng+NzRUBYDdVBFwpScu0Ks2sE+B6p84=,iv:bF39WCzakT2wbzaGDF9sg2/KQxlRSDYXTfE75UcpQAg=,tag:GAXe0ZLnCBZcLrL55d7BiQ==,type:str]
  pgp:
    - created_at: "2026-03-31T16:40:06Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAhObIQNKvLJ1pu3scQLG5KrqFJDfwV2qh+M+8LhHgP37D
        C6VLoXQVzbmCM8ufKEAPxo+GqyVwiE5K+CkxaxQ9kTcFfabWhudRwNhRw1khZPdG
        drEFMu8FOIYTkfSnI7rJpfWh8YXL37bl+xidGOkDe5LFufTG82xj48w2FSYC0IYL
        DzDXaW56C1w3LMbj2xiuU3rPjJ199XIgt81ndKg2udjLKvAmQaibc/jzmgg/hVYV
        2U+E9dxuKLlbyaqB7OxPOm+eIcsBFMTStT0pLzoMRfmyF/hc1LTbm+AF/jVKqLRR
        Dc6GXrwcGMr5C/N4pRtvJvQGZNty2LTJevH/iIfPPBNHeor8Ji40dSSYH9ClrEIe
        xbYPgn9QnmxEIQU4bNpKkD8Ie+W7mJ9Dk6Pd08GZuHwkPc5Ggfga/2JynHDTemhu
        p1NoKwBqe59JfzBRJOsWSIwgIM4wv8S8Kx71YHWLGfzWtL1gR7eYDdNfcQvyWFKo
        /VoPawLqz/oJ48jhadmhJFUCqwGYjO7kI2BNMuDyxdhI2iyKOzMfHKnhgVrCZ43u
        Aqbnd4U/uvanV57/SkEqp+w5Ar3ARDD2jlqjm2Iw68LQaYcl8k2sgkRczCI9Tuq1
        8rdZTjdtJCPy5TSKPQNr1EjUI6bk53W8YqLSbJHAL5HjvIU13N/bmA87whxRZ17U
        aAEJAhDfINMbOrbQnisThoJnYNF/H9Eqy7n1/MQTjrV7sEm9luTWplv51pJqurWQ
        x5NQXFicGbHaLf8IyTafAuLhrAE/d8EmGad62EvUNK+n/SQhRWRj5LbeVZPZbQ6h
        jhTEsi8+9Fn0
        =e8/O
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-03-31T16:40:06Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ/7BKy6amjmBppYnWbeY3HGVD0yuhJ2p52HjlJKbR0mfrok
        B6ILCBGGaHOyGJkTHpoqwEFTy/QVDgtxDbc6ou+DvQ3f2QzZXS6g2MajVUvS74oI
        +UFU7dBUZdxkMuYxKpEWV+LOIE33O01+gsW+q3/HFQfmu3MxqgoaP8oc0GdUXTPj
        ux6X7Z61dWsffglL1RWU3foHRLUzds+zPoVsYKlGu+u5lxU+y93VhABvldI6UGUt
        z4onDHjV9AgCAZADZqpHjVxH5aR7PltacCTr7a8WtiGf8gdKw5GazMEQaN/TiZXR
        eTabFMnafjLghRSOHND2RiRu9ZZstAy5H2aGJ21tEKpsLBJv4f2ZG6q5vimVjWIw
        /YeKhsvl0l5UVVLjL1M7xvL+hVZMdrEi3AitEsdIvIomrnId/4xEkPnHGrsNgfTP
        USSUf5Zp4n83/DHABrUR3G+OG+5jX6W3C/SOvway4rZxopSY64tGp0sfjGp7XJWF
        HV4iGyQ6EugEeDvp8+MPP/lRatqdSQeW+UelWjuywYUI11yD3baWmPocOiG6VpGB
        +SPffKANQitcWYQ4Eizp5df3PuPf4cntCmjHlNwPCbAvOaGKEzC1l8G3Qkm7DtH+
        jr6Ef/DDFVYUtZIpI2u8D5fBl/bSgeLbra0Lo7wLuIMwB1pEBfCd1TqUQA3xTwzU
        aAEJAhBGzIiJ+5OwkTy8lZo+OyYvNMkz+fVqSB/htTCgw2qcYIsegkuKq/GTAyKv
        P/NaQ0oHRVps4jfw+k+Y0IRZCzqzrS7tZ0RTX4GSnyrHOZk/n2QTicxF0KS3DcXs
        UuG3mF6RTUqL
        =ycP8
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
