apiVersion: v1
kind: Secret
metadata:
  name: grafana-to-ntfy-secrets
  namespace: production
type: Opaque
stringData:
  NTFY_URL: ENC[AES256_GCM,data:mtJB1lWFb6jNauk8iwmCqhnzXXMHO1agWM858u4gfJ6KYpfDgrZEeHenw/tavvDOns5j9YBe2ksJh89b3ijlFxIhodbw5Yede2ywhnnz1bE8fpq1aFU=,iv:xuWpOalCeeRqVhZdTzB3Osrz2lNsH0q7Y5Mz6RHCbBs=,tag:NVml1z3+J3BREthPUdNPLQ==,type:str]
  NTFY_BAUTH_USER: ENC[AES256_GCM,data:RuV1BIE=,iv:0KDUkB58zXS8+N9DoC1Rt3marGUbnewwbR0KjPiMFUI=,tag:gRq/1A5fJtGlZuC58KavPA==,type:str]
  NTFY_BAUTH_PASS: ENC[AES256_GCM,data:LDj+xGGbUuz5Uegvr+G7,iv:A/wP4Y40pH7Rw61PHQ7txzEoI0k9WidaWbmNiIAuF7s=,tag:2UypRnf7s0VdbES/ejAFRA==,type:str]
  BAUTH_USER: ENC[AES256_GCM,data:F4ZYiNw=,iv:jRsT8PIMFxKaJO/LAkd3W0M+dABuyUWtMrJNStjUOPo=,tag:4VPiJI+omBIKYLNOREDQrQ==,type:str]
  BAUTH_PASS: ENC[AES256_GCM,data:fdireA6I8ItIZ+0OsG1z4qv7+/jOcusZMroZl7iCdSJu1GTxiZKdJg==,iv:d7e7KvLmseMDOVNOzson0lHmdFS0Qbzjyo04eYIVEsI=,tag:eiq7+6Fa179RDg4VWE4Q9g==,type:str]
  MARKDOWN: ENC[AES256_GCM,data:4U5xEA==,iv:pwzex/Tv3GvOTeglYRd6vq9297Jmy0XjMccUUNFtikQ=,tag:7T+fgQ46NbqWGwnre3RZ+w==,type:str]
sops:
  lastmodified: "2026-03-31T16:51:46Z"
  mac: ENC[AES256_GCM,data:PTOQsqnJZlL0pen2YjdgWk3HvXAHJciO3OL1hfHfbWbs9uWkv8NgTqBIHh3fPdgUUbYB5u4nK0/uOrjJoksWP5u5i6AKUTntEbiL/b+Yyo6IZyOVyJZ6N3RHBahV+OKHYnf0oYkQsEa8TQDooSlfmwJ4856FuSHe6kDYF4WdQg4=,iv:PQWm+briPoQR/JB9zFIGEa/IqVCoI035bsdZ1wSywUg=,tag:gLPP2xPZOCRMHinfqdi2fQ==,type:str]
  pgp:
    - created_at: "2026-03-31T16:51:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ//WLywhXzjTwz5fGY4BnYFdPLHSzlRhV406o+KrnXhDrvx
        mJal/3LJbr117AlcKPDaRLkjmQXZBKfKWiwxymMyyxVmUamzv3RVBM5IqstDLom8
        QxwEHOVf+FEQbwjif019SgIqiV5Is11AOQOIHOPkBW8k1MgBbM20bX0ivRCBWjWP
        nao1UL+IT46XA/WKHt2N4pAdASx0djM2JYmMF3zwNDMSOOB4CvJyPZhlZ+RMvPc7
        dtlo2frYSNjLFOXP26PdahGztWOIPa9lLBHkXLiTxo5SfwCR4VhgDBBEQUalb7Mw
        XFMhUB0jimWdUFLRWfHW8GvGgED/cUhzG5sxvfsjVQUVDS9zzZEU/jZx0Hq9uAyk
        N9Tq+Vp/RUQvsmHMkOKAWM+fZGu4h8ryFPcmsQlptecjc/o9QIYPkWjru2dGpXQW
        nb/pANovJ+nI7P+YS3yXWTZGuSRa8xJuKVKrgKorDlod8b640+qMg6GAw5hIrY2A
        KrAQOVEt8MGo5wKaYPfn+HbWYJcWTN0VQQwb/7m1Jz/ioOmNOpkUVjzxdGbV9Kkt
        WO1nw6fiQI1t6R7kFh93KkgYS4ngsoZkmaaJrL2+XKSuwJeOv6wA53d1nfx2YUqx
        QKMmsFvIcUgmnfb5fUwsQwX4gb6dsoLt1fN0JPb4fOXxjCQM6woPBsgfKbom7ujU
        aAEJAhCmHU64wQkiTgkW3ZvkAeL3dM+/Jor92aBGRO6gc5jvXkaBGhs3K1x3I1O3
        CLXAioSHJSBaIQj097Kao2xkw7yP4nsRBno/Y2rCPn5/wVa769WWTr9edOHxZxSE
        0s/f0HO2lO2b
        =GL6a
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-03-31T16:51:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ/+Ns/itnW+tF+eGK8E40bVzo9JrT//4GmBGiaPqDxxMaJx
        KbM/MnSARMPAZvQj4cTmeLaqovqJpQfMOxqagrEJEiQ3nGHayF6DUURO2rYqa7de
        KNFo1gH2fuNB9lRepPLdatupX6reyKLz26zVmx2oY7j65dg59IXueonaMsNYGjLJ
        Bgz9xTdmLEQCqEF2UM44zXDVdqPYzxN6CpADM2+q2+Tc1hxrduM+nEd2ZjDzmZXy
        rWwwn94BGUWnYcrJcajZ4gKje8unlkquxoBtws1/bocxq6Z2+RVy9sw6qdHTfFR+
        fSAGhav4p5cGpkUbsFol2kqSEx4zYfrX69fnBdfSAtbpSC81WsQL/LYHg++8r1gR
        gJrTyvp2AnEq+K/bFAbLUuZ11lY7m6hBQWRE1fC7/2YKV4AIUHL83MYdVlWEL0T1
        0UBfHFmAZBQm9xL8hqDcVmxM9Kdgi4NwSiEq8O9+CqlhNFhOF/K2BSxNLKZlQwt5
        3+6o3dGXE1wOBk2aJbBz2Kw9wR2UKOM056+52Ab950v7ZL4dA9RUrEM8j29/tOZL
        RLZ8DZfVUpq4Slo0ZbuyPOPrqHvef8BdAweIzrl4jOKohniwdu0Vv8xfPINW04sv
        E28BWBDU3ejk0mtdQ6Frtjfjv/Bp+cgfLvzeJlOd4bdDEr/bsv4dRBNK43LXl4DU
        aAEJAhBELpYOIrAIEX4CQVDtJkwb+6XvJ1o73tM6CJv29O0v9FSYbeAbKV4MgLnj
        JbdkhK3ETHxTVg4VtcaUqfB9p4ORGAdMXRB2vMO8k4SHTsTowKopZSXgUGBg6lWD
        8qJVisgoAT1K
        =02L8
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
