apiVersion: v1
kind: Secret
metadata:
  name: tailscale-oauth
  namespace: infrastructure
type: Opaque
stringData:
  clientId: ENC[AES256_GCM,data:/nsBKc+XvN5tCH+GcW7tWdU=,iv:r0+Es0iPVuhpBUgo9oo01aoXOKSjzuKZxZBAPjUcfxw=,tag:QPK/GXVVxcTsIsj0cj5LuQ==,type:str]
  clientSecret: ENC[AES256_GCM,data:sEQ+BIcEtT6E8KkAWbqiO1dgM6osbExMneuLkB+FCgdwf3nYlHwkZljMh6TEzC6rCc9iag6R0Qau9XIUrKZgCg==,iv:lMGwBtJ67IxjnYb15cZkg6egq451H4iVb1MZSii32Co=,tag:bTnA3eABkrIJHASj3rvbPA==,type:str]
  authKey: ENC[AES256_GCM,data:xkjGMcWdJ9ga8/hqF5TLG77lBekqB2em/AjSdGkNlWfaXLVlhnRWmTn7sCaAurW/J+U6NRAUA7i0XdO7Ag==,iv:/TX6/9qsVNqlyqu/TYkPNhPEQomFTPycvMpGouwoh4c=,tag:FHeXENCO3lF2QD1utDieQQ==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T06:27:57Z"
  mac: ENC[AES256_GCM,data:toAv5Cip1Tah/gM/vlOH5kqkWKFYefaZpEmGdVHgh9Y7cBRqNBORNeptF1clYXCYikue692cXifGDAIZEKe+ETkOJSQzkGH6EUMClzo2QD5LdScBYMqBX6UciSJqtWbK8b6bxi/rEAAEC6CLXCDqjvgs0sgZyky+qwOg8QFRTAc=,iv:lISXoEwsbs6CBPJc6KBHu1WIALkm+b5wIx0bjFkPx3E=,tag:N/2Ny4lXK0Tzj/dd4vrGIA==,type:str]
  pgp:
    - created_at: "2026-06-07T05:33:50Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ/+NwOuNkTfzybqrwRi/teI3yJyUXv1dmS+SKvQVvUWRi8v
        9oO+N1/0NB8mIk1AyFRs7ws0zSlkjbYxfGPlLzEE0UBQa8F68tj04+MONsn0wP3f
        MQKrdxG+toeda7FBavFoiVfPtXjaU8p+u6jfZmjx32YW8SPCm9EJYW0BLBx07N7f
        SRIDhzMjLrD5hch7oY6TDilPPeFOG3z0aTJ982Wg+n8TDgCHleINHf9MYmgFKey/
        XxFnjDLvrGVkzwlfO26q3VAih8pQBhB2pEcxgorGx5zZ2n2gFm9NhfFA9dy2TRRV
        8fBHmUTQmIrXNoNpIJP4dzWjkxf57yp4S3IGTzTxFzWJHQBtjRgYR3V0gd7MundB
        IZrL5INZfnKlBkuL9XUF78ToeIjC6P+IY38Z5LM3ud7NaoXe0mucxLicaY5Fdsmm
        3KXa++6h3pdqWXHTypRndpFa+T2bVnyt/Flsm6QaLBQfsPCPrpQDoKEGu2QZeatG
        vo572/Uk0NS2i7GEGNmT1Q27Ef+ISt5vy6oPkGkjQRd8CwPczaNB9gglsO2B0C1Z
        9T59RIX+vUAYJoh89reXT+SG/K21/UZzuTS/OddGAh4vvnQE53L24soX6YccXgIP
        qKccgVFuJiJEfSfvbe/SVvr1wN20lDi3+FKqFI6k7asjPocn1QNjYk3lML22WEvU
        ZgEJAhA4k0BCxL5IKrgqUNfIUEFVCEOj+Edz5fzHG60Rrlp+UO7gYm0pUDJEG7mN
        jUAM8A26QW0Fq3bpjJ1m2QBiSs9+Uh8qcVp2T/LXgmiPhB0uoASfQDE8RTqDz/5i
        8ayAS2jnfw==
        =KHMa
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-06-07T05:33:50Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ//dioby1GGH2YVYGVHaZyQh1cRNke2NmGMMuO8+wvgsrBO
        6fJz7lF7dYdSe39dpRcujKFGFb9dsOmsmApx3T4QnCOqxafR7otdwVaYo/w3/mgQ
        YBD2igzORK1hje87RXo/pBAgod6up27r8xa5NLlIPPWm8oZsMY311nA6kPrRXRXs
        SX15pBiNEn0k5usglwLZNe8/+XjuMM3a/CJDtURsEIH87WaJvpE7kxvO2CF3NPoi
        ChV1F83+5h1EYO+JwTyH8K1vXQmkGb5KLapUuCPMlagRZfHMh1hRxgtxdXTgDGoL
        6JBUkC1om+2wEwSkc5vJZOEJcqgVYTYOYgVrt8laAtnr372nnnp0qzNX0pFQvzDJ
        Oed2DpJ45wgOuMOgSAQFEUJ1OSPilf/TRpaVTM9Y+euGC6yj6fJN+hwgPVvk2x/o
        NYMJDEinBeUBZlv39rjkXknrm6LsKM8GSuqCM8HKrU7oFNNOLzjSx0iq3KwfO7Wp
        ww/t6bHSLPgdMktWzd7mR1xLhukjpMATW1MwWS7DvEdJogkxTQ7U4+tM6y2N8gpW
        LqsZ8sRux/+oCNwxdE/5cIL9H/pSALg0JTp4k5FqhiiIbyb1XafSm9b7Dwv3aGhr
        jInFoOVYwEmuQ/ZweXtXULgQQqO0WU/2LAic9QZOaA5Hsgwao07cpZJe9TFHbIzU
        ZgEJAhCOtYQzKX13zRAx0BU4vUSGeaEPHAOAKbh65Qx9jz+IqAYIMvvC76Dg00OG
        ZSTTzdevBHw+MTBW7b/D8Wx2s55ywh6diZKbz2BLevt1hj7+4g5cs1PUxZU1iZEZ
        rMDhbH6HPg==
        =IZXZ
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
