apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-ingress-infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/infrastructure/postgres/ingress
  dependsOn:
    - name: cert-manager-issuer-infrastructure
    - name: postgres-cluster-infrastructure
    - name: traefik-infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: infrastructure
