apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.22.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # Add any custom operator values here if needed
    {}
