apiVersion: v1
kind: Secret
metadata:
  name: excalidash-backend-production-secrets
type: Opaque
stringData:
  #ENC[AES256_GCM,data:V/Q9YUaeNV7eGhqfSCUBv8D1fgdwQw2rqpBn0gQKpvOTLLGXVog8i8O/Oc3S/pyng/DWwZJG+VGuw/3NvQ==,iv:F0RFQfeONxyd4GvbQk1ZTAZ05na7zJhLWtTre9OtF2E=,tag:JhtTR5I2PaP7O4Q8Hq0u5A==,type:comment]
  JWT_SECRET: ENC[AES256_GCM,data:fIN5xbQwXniCkv7vTIo9V7noXZJu4ysnBTC3TwKwE4g=,iv:LFQVSaBb5QVXmHzkeuisYWmU4YMV2rIF9xTrxVeIAFQ=,tag:26BD9zG8bAd/mTFqUaAl0g==,type:str]
  CSRF_SECRET: ENC[AES256_GCM,data:W5CFVt0WBRooo7xWXoy0QcZbUACJEePyiybt0ZxWwog=,iv:m8YbTjgU5yaXBMaq1KNHdE4BKLFX6ah2s5b9V1jIAYc=,tag:zHOBYHnRLSo1MhYPId6Efw==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T10:33:16Z"
  mac: ENC[AES256_GCM,data:jGvjge/O8VP3oAk+D4mh7QTMg9RioxKn1pI39sy0pWzZMB56e3mDasd9BwjGWrdZ6Od0CB4pIGBURZaQbVrzSnnma7oc0x3mcJdv/DEkfVnSr9wV0a0Wy8vPEdrjhJ/EAzwug/xN8JAOqHzuZ+warm33yEzxzJmq1sG/G1aCYGU=,iv:0kCgZbp6VI+uUX8Rr6Ncl/uA6WCALV0SDK3AZuYUadk=,tag:o/NwdlZM956Y0K6Mu18e2g==,type:str]
  pgp:
    - created_at: "2026-05-23T10:33:16Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ/+OuJnhwUSIyB2BWmJ+oUd4cTTJ8ntEP8JuBUQROhYOiow
        cH6DaLKLXwuNnrndxdy9jYZeXHEdVbrArHTRaXciS0aF+jCHaFJmL63CGoRQTRbW
        udn0K4Dwp+4JqmJgh+22cQv8Gwnt/4qGbxRbBFLPwKMpxK3bHec6o1qjAgHTBcXh
        uvOnfpjxC0o7RfefjNFl2yPxfRDrwnNxUCU3x0JqcyFxaPnjP9qXoDD3YlgwCB8l
        UDOYEQ5KUiLrlYYEjKR3S+YidFbik9IpGi20FcL4jxwmYqAmOzTs7prV+LuAHoJa
        VpO/8kpCoWqAQJP1tOJ22mbXnLvWr3DrMD6sHnIA/YEyKKTfeR964bPn796nmT42
        9cpp7IafHNBwyYCT2CC/+bDtJvDvzdx82LniYSH1gUUiyXUXn+f3dS73AUZr/X+H
        91gDYqVowT7RQiEBfWQ9eXSMmXqf800D91l9E1J8H+x7SuADmYDat/qWKCz76tMQ
        a+SB7KZOFesvY69IojyNY9MLyvYh3ds4iLD8eXFRD1G6wg7S/uCPErQezBSwHAoj
        yzyDlo9S3LVUoIAUG/voelT2/BJgt7JI528vMyOGhNC/eBM87CaDaJ6PSDAv5AOA
        3/Q+PMBqAV1MDVzuIfta27ufOIeh9vfmNIOiwHFc4RD4QT1Mp+F4xREiyk+dyhjU
        ZgEJAhDVZDlNlNGHOnHZggeezjArsZwUwBTx7QTauZoV3SpYMhUZFe6vDOlSiM6M
        x8d4Oiu3oi6ICDn4kQmyh9ZhUHgKe9hYugssr8ez6aWjvLviJAwoF+uZiSW8DaW/
        evYsOB4IGQ==
        =EtOb
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-05-23T10:33:16Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ/+KxPEVExUNuUb7/2/QZz8xImYAojxdaZNp+HDnl9i2NE7
        rQabV05sm8RLG156gBoxLrrhtFvH6J2bX3O/1o3rjuh3A0tDNetx9HYMl9H2Mksj
        UGT2K/q3Aw7Sw7GKr8HFVBwFP5yuQBWU6ztdynuFgQ3NwqGC1y42c23mYVMsnZjj
        KmzzWecEG5wnSCFZs+90TyBHVF4fNFgMFujZrDggXGDqZ8BhRs0gtBn7BJ8K6Av5
        kKpy6+5jvT8gpYFi/xQJ+E5QMHmh/fxewnfhPTSodf4CL8iWxvNz5bvk5JOAF6EJ
        3r7AY+4NtHbcSB5W7dLZ8xnf9QK+Hy0hn1HbULakiGRyW4CL6mq/Qd0ayLQR9RrR
        Pwfv2IvMn0xcZ32M3aaPEcmMBaNkBkOUK/aksTrM3LDLfjuRr3yIoYE8Wn9bRSA5
        FAltGNO2A2McG2UmC9DSnqSUkEqe53WZg4btuYJ7EtrIbivT6PXz1nUxAgGj0kXq
        tfbdW/A7au42h0DmrzpO9KoS93Fe2bIIKAwXyVd+DhqaGDrOG5I5zT98YFZAkUuz
        SqhFw6rQx09X76fyNbW4bg+0qPRicBTC3ulWiMF59DiqYJek6MUqmwU4/fUUnmWH
        U/TA6ILbw8ZetmYZB6hoXYqQ6TSxWXGqgicjx3dwDGuysqwz/Ei9AUh9ZfXI+zTU
        ZgEJAhBAZKeF5ahS9s4FtK286kcwnb+vnXI3CjC+SCGwrq1ghqfxF0po3x8Mg4zN
        S+5vZ7xynydCLror81ZoV6z5lBwedK2NIF8D+aqSas3jmcA6dwHrXwY+vFblHzHA
        P3xaIGj6wA==
        =J70I
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
