apiVersion: apps/v1
kind: Deployment
metadata:
  name: instalock-cron
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instalock-cron
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: instalock-cron
    spec:
      containers:
        - name: instalock-cron
          image: tahminator/instalock-cron
          env:
            - name: NODE_ENV
              value: staging
          envFrom:
            - secretRef:
                name: instalock-cron-staging-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "15m"
            limits:
              memory: "256Mi"
              cpu: "500m"
