apiVersion: v1
kind: Secret
metadata:
  name: instalock-cron-staging-secrets
  namespace: staging
type: Opaque
stringData:
  DB_HOST: ENC[AES256_GCM,data:iQFF0tOacoztkDG+3RW5rxlsR+v34UCGhLawP040MQGEJXa6CNwAnVDxhYiDLwg=,iv:Bw9LXNCc10srN4OjSXh/tKgF1FjNFXXiLPShiQ8cTdM=,tag:tnh0xeG8JHxDVb/ZxOiFMw==,type:str]
  DB_PORT: ENC[AES256_GCM,data:VXxrnA==,iv:mIbyFf0Tzkiv8Rclhb1V9cNTodxwMxDvtDB6r6pp1Dk=,tag:1bEGrjL4NarVvgi29RR/Vw==,type:str]
  DB_NAME: ENC[AES256_GCM,data:5ZiUvKDkaaArPhg82lKBX9euS7Q4sML3,iv:nu4pk+c51133iLRxiOAi4tuxOrfQiIH/yVaNNkeDbtw=,tag:Pr49xuIgT9quLDgnplqMaQ==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:dwKHiwscbxo=,iv:GEgqt+IeW2NybYrLWbroCgj2HATG7+jNSZY0cLUyiOk=,tag:s/6LdQldJ6dur+eH99/DMg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:3k+l2ZUJuxmr7zLR1Tdc1tJE1c9UwJPpmpWls2suywRR4E3mjQ8tyyvIFj3DgqgKHwRiUY/3E3o8r3nN5PikcQ==,iv:v56M0geb1DvMasqidD7ovljqhSztT9JY1QX2GybfSxU=,tag:nRWRsiNQ6T94qiOEryx8jw==,type:str]
  PROMETHEUS_USERNAME: ENC[AES256_GCM,data:7cfAUWP9tLI=,iv:j4qscxO7RUQhHRjMNAV7gMbEtOA5RwXnwxwLDOAak/A=,tag:KjtIadv0sT7rEx8Ds5YHOA==,type:str]
  PROMETHEUS_PASSWORD: ENC[AES256_GCM,data:wXK164B4jQ2VU+uql/XkTzXzA8A4BX5BjS13fWzuHBZpnv6qfslTDPr0IQlzDHVjIfnKdkZMA+QIs67qFa4wwg==,iv:j5Z5ymrqNC6sUMzcRiQckfDn7bnomd8i4pm7Z2Wdzm4=,tag:ZoaxlY5XTu7fGkgLyx29Bg==,type:str]
sops:
  lastmodified: "2026-03-25T18:10:40Z"
  mac: ENC[AES256_GCM,data:Iq5a+zVj7DrELnlGG9FIn096vU9Oe55PaEiGfVfeSiHQznLg1mQsq+T5monXX8ekVKpw6Wa9uBW+SIUxJWXR+XQBGV+lc/g2v9jhiTw5pv48Gozxh5LqyBoX/ICN5DTyOJTqrPwjzTjnaFSQrSE4mhXOOROiNaR9yocwYn/SzW8=,iv:0wrY/DjVyVnpH7mdtvbmGA2SPq0m8G3tePqdLqDF8Vs=,tag:iznmSFg/NNQia+RRh43TjQ==,type:str]
  pgp:
    - created_at: "2026-03-25T18:10:40Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAmD2Hgkz6aMpWdMgZjIDFSVLeuLqJ16efVtLvGiM7uCRd
        albODKSu0wj+yVCVUS7hkBWmRAt+5mybuFD4gQsrkzbECGtfVwEgc9yDzPMOPQOD
        P/PMAvp3z/GbPjR+1CxUImKyxZk2cC+EEyQhdv5/YxcrNQ504jEDbaxIOCWtPpeE
        iwec1kkO/AmIxK+QSPpvButJcF3IPVJ7lL2bT/FBDsLhEo4vMBM3DazaaSqSnL1s
        cT/NWCExPKetUiOVi78FHEoeXGBDpP550G0caJtB4lgIMufxbNDQpe3GOK/o1WPZ
        hRjFxwj865T+YULOpANxSOI9O6BtsxZAJQWyn02LFSf+w4rxqJqT2OHY+5iVJwt0
        N+Zv6B9tLHuV0WK0sMAFYClvYuF7sWVdf7gh/5fRMG1HGKWxyVcIVOPa3GKc2kIg
        VuWzvrey+jYoYXd0qTax5X13WRKPcI5r2HjKRGPNxYylLfjE6i0MEJBBlEtC7V3R
        a299UBtZV5HqiqJCnYb1mIRZMhaV8mOH16crjEy+/C2agZC15wIPJsmCDsLAXNez
        ahllfncfqWrbiiujO+LlHdzK38VXlaGgpH4r7OJMp2a/Ya4vvOZUuVKeEuYQg95V
        XVCTg2rv4RnqOmjw/ICTidYaAN7SSVFLMM9CnV1vXtfQCRa1y7pLWZJBO65nJRnU
        aAEJAhAf9wJ8j0MzCkm+MeKzDxBrEnbvSQbGBHpVzatMBHaz6+9Mgy2e6taKO/sg
        9rMpnRDZ56ukA2Ar+gWM3lpKs8rjc2Q9NPLhJPp+bocPT/Jd4dOmpNXnJHwh0TUp
        /Zu56s6vmK9+
        =DD08
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-03-25T18:10:40Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ/8DpZ+8i7jra/nR/i+jh7QzGCrCM56JW3pHTyS5Va29ITz
        +sRK9P+Z3W9i2GroDrHHNRiWsp+RNTk8g2yvTabSWXDdRDnM3Ivqd0ry4idlLssZ
        CrWgIin+Ty1If3eOWPkNVkd5t93wDaQVbD+RU2LW9rx+ksNGyppIbvF/RY3lZWg1
        NIsDiJDNWLuCgWzpqJvrg43shxdDl2DeUFY17ICPADB8xia9D8n+ZzF1KU1fY7re
        jTOB5b8BujlZyzSWd7gxbUx1/cgxeBrIUUQ0IzRHpRTH2ggoMyqfOvK5KruIBDll
        DSAfC4t32MiRnHsYUgmIH3OIdIWK6ix62VcfTG+U9Okhk8CIu953PIa502Vo15y2
        bO8cCuqi8fymPgjV9hfqU0fQsn9Kp6oVPa0DHGGS39aTZUMZwBMrQ34sM2b+fw4r
        qZ3KudK7bbof3ZGZ3GhceYAVEZJ8zM5YTcD8nCShh5sjXUSZ3uPDHqLvr6+rPJwQ
        00wMGiVXIHY4e9rVdHBqsWUa3+3GgEAuuNZSckegDZMnQvAjhKu//9arF8lLiUKU
        dqvuXZRCnrC+QhyFx/uaAyrx+G/PlzORulxfm58ItToF+iiRoeKLf5tlFetwSONF
        ZW7xEItTZ4x08W/JN1217plaXPhihNdAZQ9mgLpJtyzstS8bNTtyspGbZHjp3AfU
        aAEJAhBDY8/y0NBC28tKsnoBNPJBHdP1vTV0GSpj+c91AGXDx4vQVDXK4gb+W/lt
        7nqxbp7KrRULbzUJjq9TIs5QRNTkQ9eHJphJAvgQQCheuRy2mNYf1BuDEG2R2v1j
        /tjFHpvgxNUi
        =p+6K
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
