apiVersion: v1
kind: Secret
metadata:
    name: instalock-cron-staging-secrets
    namespace: staging
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:0g+EcpUeKbSyCoNrnpU=,iv:hgUu1PRr7zZUi5ix0fE19vnROgokQ8sIAGdIslRXfJk=,tag:/2qwbgT+/cVhx0OceILMSg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:SjY87g==,iv:AC5JlAfKP7JBu40Z78pTKpiMlg6RyTQzZ3f4l1TSAlQ=,tag:I8HjMTAYqPFrjMQ+olR9YA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:a2OfbkcMJReLmXGMsJ9YvrtTuN75wrV4,iv:/3Gpqa3mCCy81t28yU6Fr6+c1Mw/79oYoMgwC1Gb3R0=,tag:Uc/05/vuMb85cUpWTiYBPQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:gBC8K2PGMs0=,iv:b5IYZ8yv1mI0UVIdTY7zkmjxOcXCyqVVbIjkDHNjhbU=,tag:jjbRCm/Lfk4CnSlit9SO3g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:NPRFzZGQzZ2bFMiGJ+2tnr8FtdZZ4ucg5io9yo6ZmU2VMOKOKaA3F7O0PCnsoFPgOHpm7XaIH0uQPxAwfxESDA==,iv:PLH2Dge1qrN3U2DBYmI7/MpIZXLo/l+JubfcOzZCsFs=,tag:5d6NmdRgCU8N5Tdq3dzoPQ==,type:str]
sops:
    lastmodified: "2026-02-24T05:27:31Z"
    mac: ENC[AES256_GCM,data:C/5SjuXEr6cMkZ28fkHQv50Eq9Lkt0mZnscQHJMY0yXSvdoMB9MwCLZce7b85YZn9A9sCdVa6AMN1fZYAY8CjrRfEZtMO5g7O2g8/n9Rl+wIAyE3LvR4q116XqtWbAPYs0p6Exx7/2JcKTDX4LJCVC4CoqbWLp3Dpirij7wBKOY=,iv:CfXiCcjtFD4PLZruSB1jZMTpt0C9YlHbpjFNJHyNJqk=,tag:V/TJ20bC//XWfr6ZlePtPg==,type:str]
    pgp:
        - created_at: "2026-02-24T05:27:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYgP05NwJ3CAQ//aPIQq1PsZIa5UZYS60gAFUijzm4USzYhdniOaa7QDBF5
            iUlwFxJv9NkRCOonajRVAK3RlwPywxcidFQNmZPUa5HhKzif1EMD6xfF46F9iON5
            AIqimHMnY7G2Zpo0F3uWdSNrselnMwdizIrscAblmaNJUD0NIvkqqNc/yqrwCcJy
            2PX4ihjgRm1rIHiDYrcQlci2q89W14CltSvto+/r+KjsvHOnXv2ylA1Paa7HTu13
            2/lyUgbOS4AKXkGQdAqCYycq+UCR4P8w57LNooFOo55Dma2MajN3MvEC/8RAidzw
            VjV/DBpAl9MLpuG297QSRVFo7t9LMQNxaJ3k6tUACk0LPwE9h3D5nPoEu8zsIGdT
            6DWGo9tbSfaT5tQGDK+gRKeqGpTHGJzrbf9YyrWjF4wqHxQnXLD6BfGKHpWLi+pz
            +JIzTplwhjKdJuwn52iEaPhOOrOM8xLGGC/7hjTK+FYm5Nyocdt8Uk668w1E7YZb
            bqeRxxqobyG/W7fwtod4ILVy13XKNgQEYYRW0LmyKkeRoiOi9YWMIDcb37LxaWQt
            4VCVZx4dyJYM9fNaWrfzY/ZwmQKIfay2PI0IY3Imp0CDyvfgsjsIjPCaraC62vKF
            prGT78s2kApeV7xjCIqWgC/utE6JbEWSizMIMELNE2frKgQbmv+yI+rGmmudvA3U
            WwEJAhB0SytZAFTmvpNu6Uj42QHjtcamNFJ9TG3nrE3grmTqOa8UEdZCnliXYWUT
            BX6edbiYxo+fZ/ZrkCtZ0h5ZmzyPNNZ9iIqkI1cBaRzdZElSnECXk2i7npk=
            =uM1V
            -----END PGP MESSAGE-----
          fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
        - created_at: "2026-02-24T05:27:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7m5W8M9NGm2AQ/8CyhQ4ZuDG7iJGTNW93b/qH8XtWHFLVCcXnJfCGQKK8Q8
            icCbJMaL0QMZlCv7ec8pzgwExgANQN4sUqxAmjL9/LQ3f/f5TVS8cJdKJJ/ExjK5
            0X5bkEF3RwiszWwo5PQlH5q7CPdvuPwCs7S75joobYp7smc0PMN34b8fOyczf8sV
            nYmnkU2i/UvuAX8WpBKIfQqnZWp47Kj+5PiMYW6VkX5hiRaW0yf3liO/E7GJI1Tp
            hzwz9IdXKhzQbtiKaEG2DN4v0owRl2RLuvw1zy+xULDbsHEFXaXtsEJcJg/KAIIJ
            i+Sk70BcXRARi1ZE1sfz/Efv3r2rWW6Zrp4+ZkK1igUE6+emRMVo6sRDmol+0MEW
            zmxg38D6Zd1/tWvlHg/+rTssm7DBJ4hiXlZJ382/KJJKHrGIg7/DRs20MGoBCKGe
            HnLNFrpPfBqugnhz3OjjvUNZmqaSLou3VGEopYy6ErAQDvxpthxTNIwCIQCRHBc9
            URpOqJ+Ei8JvZOLyJB2ATT9kWzlStXnZaRyXsDZPcbQvCR5Att1U9n8bRCQi0L8a
            vNIytHwL7Pi63g5fxsSr+k9HrFL6sgfWz3HMfkSglQfP2Gtv7coyD4I6AIYrIUdi
            x35qAzs7q8Q7rhZeWZnv5ecQR8oAvmSoN0gYvYPBsx27U08MJKprfi3cBC+4jYDU
            WwEJAhAQZ2m45q8IouM9FVbsn+cDLEuqrNZJ7b5Tfjlo4e8zVCEkpyxU68Wre2+C
            fdq4ME2vuXCKuez2CmKCRsg43s3s7bxL3G2jUN5y2ae3Ms8wP2CLmo6tNdY=
            =CN0l
            -----END PGP MESSAGE-----
          fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
