apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-user
  namespace: production
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:FVtEmF0=,iv:cyaVO3ikstAfSyr+XLrkPr+AtUtWDCknFVQKcevSCcM=,tag:gZOmzhs/EjlCU+KqOUIhxA==,type:str]
  #ENC[AES256_GCM,data:p/UlXv4kkLyhKNzqfXp2tEAN10WLhQu7jP8sZOExrLTYzMWhAKwsGokGOT3Fko/DUXgD2M4NKl/TUMDW1jJOGw==,iv:xxNi9vagQYt33UgAGimamj0PbiWglf92nNDken+mk5k=,tag:jsRWdlzhQGls61boxDESzA==,type:comment]
  password: ENC[AES256_GCM,data:f+/KGuwXNmCp5sLisKmqzUrWKYyxVsoRtz0Ulndpc89vgUTm2ZKhlIdJ3g7JPK54TltzX3JVKSS8k8QySzXz+w==,iv:+8RjoA9kRSmQj3OPnM/xoL/yaOJn4aJiSRSImaBwxhk=,tag:/uZFLH/d6n/3gc6ES2CB9g==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-03T02:42:09Z"
  mac: ENC[AES256_GCM,data:qK6Jwa2+V3idz8k/9lckWBaBIC4lsIxAob12Jk9XfURyw8NltbGLa5OPf2+gqtu4R/WH2sMUL8Ml31ZAj34lCpyFjQ0krYHxx27yOeih9FaaWWEHME9mrz8Tj8SjuzSqLx0nKQv74ycoQxp2EtmXly7Y5br5kBhVn/v72pUX8FQ=,iv:HDuJadmYQ4WXGgJ8DKOq05SnpP1cGH+Cp6MoqoO/nQs=,tag:IH2drWh2qLV8PjP2qm/lWg==,type:str]
  pgp:
    - created_at: "2026-06-03T02:42:09Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ//UYlXbZDtsMx1Qgng/niYtrmvH7oOTinP0TOdH1oLuUMc
        2bqQDDMBDKxUBdGaaPgaO8MbtLmM+nzgFj/DH8HAmr7Zq1ce9cXnOACB5XrpeXs2
        EkDia7/TqTw7i48VFhB+nMZ9BIjr9shMBDKFB47YX1ILKYnDmZAjGgG0VnBVDdpR
        nb/us54qLYD6Es2MZkTmgjjn4lsRyjl4pUkjzDtXOCbishfLE31YB1TGCjL21b6m
        v1YpcLxlzghLWVOUpXvoNkXxDNREwhZVZ2djNM6bdw6eHdXc5d/FaMtFQZW11Dpd
        p0rvtoD5ChbDZET7q+9D7dhjQF9sf+WD2nIadDkLRxUQL+bD97qn2lAFArkfnq0Z
        hZrQqpI+N1HfrS6jLPONqA0C+N+TYZD+wT1KecHjIYEAXnsAXDDxmKkmTfP48H79
        w66L+8euuWnzO4R6dZhW3Shj5OSoEc/O1zbA4393cqQLA9NyZLzrK7b3WPfSbhQ1
        40FfVwKh8hYJyxtueBNO3sJDYAN08WfEMy9QVN3Hci6qUzidQxfQncn1T9aloJaI
        Urmhv9JomcsJMYoaCel00Cvv5M/edU7BCpIU2KsNSwdg7vp+ONG2zeD6DtG+ILhw
        bfdtM0uxPgcYOiPFpcFQiUnB7Vj+OhbG0DX+D7TL/QSkEf7cm+ZehP1Lh2Zq1vDU
        aAEJAhALfNn65V5Y+JaL57430t41qpm6X2Z95d21Y1mGqoRTZNzdhlyg7g+GVfwT
        Q36vKuj8PYaRvMoSJZDzPcCHkEQUHfDvJMxuMoY+Ut89TY3VvxKNaMyZhCbHeyyE
        XP+u6bdLjNoY
        =tD6w
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-06-03T02:42:09Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2ARAAqrqd6pAE+esOaIfcu8I4ycBwd6nq+M8U+973tVcpTIY1
        /MagSj1wiAhwY0SkYuaitUCON0sr1tCpusIhFYhq81AF8FWV5lIXkpqF9A2sbAQg
        CLtOUO67kANkcXxN+LsbfW7PsWCGyLg5TVLP7eObLVyZQOPg/191WidMZ3BFeJV2
        FSEN/PuJluJ6W3GQZJVRFjwku0oGS9hDTkX3Iqh7LU7dDuZb1TJq7eJHLRP8c4j6
        BHXkH4+g2iFMX+OnL98RqU6M9BXlGqZi4YLxQPKCkGGHNiiWrsmfhxbO8Ap0oLj3
        j+eHaoWvgcwiLWgCBUfBOB/mQXGRVqDPcpaCUePyxcK6J1S8I3GqD/oxjeDk3DL0
        cvSv9VCfRRCkP52Jb2TGV0IAWt5pgndsb4xaHwDbqCQaN+Nzqwmtnm8aWae5ZKL5
        AoqtqfGZs+bI0GRqzzlNPIX3xDEMA3dGmZZjPs9RyR+Y6iiKr2bFS2eEaOX8ZgjV
        Mx92/ny4UBUDvQDb6b6pUQOSdrCwyeFm0RRKpInSYVrnzy9f6xqfg1ZpKLg1thcd
        rItsIomiRQEadNqh6Pc3B0IBiDXwU4qlEP38rUGYjrK70T1wAdeYL2gjw166pIGe
        5ZfgrOecc4SgK/gsqZckfx0rNAuKeCMrfeTN+ARNX/bPNlbbD55Xe5LToLNaHAbU
        aAEJAhDSfsbsxeCFjUVOfAQd4PhQwqFY8WWT70l4LHVNwL2RZc0+7EYvwaEgKUzC
        lPXDpMH9ZgLhGJhUDGh9LKx/Qpp36sOa9ipRxYgBSk6Sv5rALbg1QdoeDi7YbOIx
        pY6DrsA32yEO
        =X+Sn
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
