apiVersion: v1
kind: Secret
metadata:
    name: redis-creds
    namespace: production
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:UUWtDLzremiOLhrRVvLSriJQLoCQ1IXht1fLHpQNHsNpb+QMVW6UvuF9vBmtze27PkG3GEPgpP9u+uidSuJTuQ==,iv:sQ2KuAp5Xsw/1wGsMsBWuobnpmPFbmUwKQK1/ec15Jg=,tag:9EACP6bIdINCmWkwS0LVUA==,type:str]
sops:
    lastmodified: "2026-02-26T01:37:47Z"
    mac: ENC[AES256_GCM,data:qTLRFD/TUPTtJn8U7PLfWwJ+9hNNEiMt1+FhlPhu4TKuKwSkdLej5hktH7lqcSMNdIk58yw8P7eZyZyFaoFNpqZX0UyJTq5S5LLAut/1gx1yd+p1T3zQ8W2CRAvkQV5dLIRUPD+ut4tE4CacURQHKhoffRwXj1t6nURrks4Nl4I=,iv:zZ/lwS0xzQMCLVT/Km2V7OzHwvjOHs4Bndc1V9/sK9M=,tag:fk2/MT4VicyKQ0R6Cwl9aQ==,type:str]
    pgp:
        - created_at: "2026-02-26T01:37:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYgP05NwJ3CAQ/+IvXGMmi1VaOuTHLM5ZuLaaxG9yvA/YF8RAsSDgPhInRl
            d8PjqrIWTvdycjTVf9L83CKMEsxzoFAvsJI/y/Vz/K+KR6Ni/+yCMlTMlIWE3HGk
            EGe02FVNMHTMZawTYo50NoVyLQ6+wEgoL9OCkYobfOV+6BNzDWHLWbkNo4h1SxyL
            6IYtnoRVlWDGX8oTRU+fz+xJ8dJpNoRkFEytx6H+0x7eGZtSMrM/Tqs7SufnSDaz
            k873BDslbD9J/Xklt2au9rXS5jbNPQAGxS7aFqPbfQDBpm+elCzaYDpcuNapEENu
            ahSSxPraUCndeoDk4lZHnI9aX72Sqv1ii8X3YTEER1Yh2mwP9pf8kwHD/nyapthv
            xsD0WwgKjpa90FgkiZaqxIwnPMOXwaCj/YbReJq7miCzylH+x6cwOscosEeDmadd
            ZsaV8v5Zd2MXW+I64+G2uww3eZkdmyaLWac25Sfs74pHbXXaGdvc10jtdFu0h0YA
            +fB7OoVvirNNAcj2BVLLVsiK/B/PuNYEzKkCtaDAB9gFUNJVi2U5f2JXHxWZNUe5
            b8eLTJOQfKu51ZHMakSZAa4mZHQmyUHrM+DXxZIE189ST4JeUxb0uRKWnGHBSSQE
            xSfLXR0r95rvCPfpPkt7mLwySCHA56rG4RDBqf3qooGPmaqxkbCxf0fE3Sk87izU
            aAEJAhC8O8di2ydiPaZQmhwIJULAjzCpwPu1C7jXQazAbfVMXroxebSOkMumz4Rp
            HlqJug4W9QpuUm5jG2qN+q+Dfq3DF/ioOAZPz0+533qoGcidx+9YCv8j5etP3MzY
            qZfKb2aFxCD0
            =I/nn
            -----END PGP MESSAGE-----
          fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
        - created_at: "2026-02-26T01:37:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7m5W8M9NGm2AQ/+KeYzp2K5v1+If4cjvH0klhnONjFHUg5Ny0a81I0qQpmI
            /sEIvjjxP2B859apjguzH+I2aQLsSeQ/HFyBVohy9owWoJ1z6m7Lqbq0s7cnU83+
            Gpa/01hdRlFYKbaMWhlwmhb7HdTqpmFmdt9CnVwCcDLbRJqK4SorowYw3XPebmeT
            1l+xSUVs/4mDkbC8Lxop8k2o4u7avuXHDpRjo/P1sXTLW7N7fcSL1n+EKHaMZqeY
            cPpnU9Qb7cc7GFeujG2HKZ1HuhIpsFZl0U9UVVryPL2Wp/OpuAAwOatdLzXTeJuP
            XJcs5i44dLuKroBVLiGnvBosJ7iawJciGl4Lfz5VXs5l6jTz3B38Km8JFSNjIiVb
            zTqjfBvp2LCP6U/lDlckH+NhIWVL7MPQpNzkzarvkmnENxHtC0MrA/eCng52QKAN
            u166KKRVZEstayuh7Rkh6b3N3wxueXvFZVgZHsSAgaLZtpKO++T7Jytg/oks+1t8
            fhEQXuCwCpM+Vm1pNxG9qd1LRtFbs8+Ac0t7N0LerNdwgfQGfJnSvBM31CBar5Oc
            6fmdbp5zyR5T2nG5Ia9Of3sqbhoFb1scBStqOFCzJFPwDsnmnd8TEOacIFm2AwAh
            GAJomMtWgOrxk2HHe1n4e3OtgPYxVnWi55BYJj43wACd+AE7JKvbc6RvMs8IKZ3U
            aAEJAhD1faEVXqf0SauVB9AjnjDnaUXs7om82VpFSQ2WCUVyLcXY+Q0WZ9oQbDWP
            GtUO43rlpYur4ito3WfN2zGILzt0PM0uT4HAzx9oQNP733ja1tkf1Waf/8iqvF4b
            yFnNgM4ecBHf
            =zJ+A
            -----END PGP MESSAGE-----
          fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
