apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: production
spec:
  selector:
    app: portfolio
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 3000
