apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - deployment.yaml
  - pvc.yaml
  - secrets.yaml
  - service.yaml
images:
  - name: binwiederhier/ntfy
    newTag: v2.21.0

replacements:
  - source:
      kind: Deployment
      name: ntfy
      fieldPath: spec.template.spec.containers.[name=ntfy].image
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: Deployment
          name: ntfy
        fieldPaths:
          - spec.template.metadata.labels.version
