apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-users
  namespace: staging
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:FgVDKx7ZaOhm,iv:njV/OeaJz2LpV+uYOfh/9cf8LayQYwWAzYJ0rb6hWnM=,tag:ynPLrrKaPIO2shy8lDFPbg==,type:str]
  #ENC[AES256_GCM,data:s215oXlgBjnTIt8IlWTcwxWsxsedCIeSrqm+X+yBjt1hCRt+8FyIgIo+F7ZgvvbK2QuNxsgeyxK24Z1Mk1+PEQ==,iv:s/S1b5jGNkzB4hsoRyB5kZLjjhUvJzZT7kSyavV0Jcw=,tag:alpkvunV9H16mtzSUeRivA==,type:comment]
  password: ENC[AES256_GCM,data:92sgEOCWdvXq50pA7axJOlcESugvQd9Mz6rPWDZ7lKVJ1jv8J7Oi4HwCgFR5/1rFgancH5avFc1uIaxm1AyWaA==,iv:H/pv0cYkbkzllQGnRn60OS+AXt3B8pw+Xii0sFx8Q5A=,tag:dTk/zjNpf+rTs7QhwJeNdg==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-03T02:29:25Z"
  mac: ENC[AES256_GCM,data:HBWMQVksT+1szPW6AjhAFCLAez33d30dzQwIgglZQ1lCxd/RJnsFGzYrB9yGmWRzhmSkeSD6+wnKVX58u/2sCCd9pcKC6xdhC6lCBceA2ca83KOncNdKwWNnWFGZCneIMtr///Y+MQAXSb0D9nmIDdjs/EMAqjpNOTy88keUjKE=,iv:orsYqCU3zQS5nYlh59pGE5jYebjLr2jxMc5xUtmzSUU=,tag:9iX1N7TJqKVRM/z79AuoVA==,type:str]
  pgp:
    - created_at: "2026-06-03T02:29:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAjuRkkloGkEmcWHxr1PlxeDytvtCo9MFQBcOwPz/WlGVf
        xNvZyaXThtoBWPNRkTI6fMvtTIG/cqZFflYpT5IgKehPVgtud6JLile2chLf5Aug
        O2Bo16fUztIlSak6kdQwz7bREIcSkQZN10UPPnMITEs3dmDcLSrfRLr/c04lydC1
        vXASaEX1K75BSwNul0VN7EGgDXO9J1GEKpEJHuQS9FHRZeI/vWuSS59McTqT9RJ4
        70VjgyQ3UomT9rIJCG8cpCLMAgRKFUhyc2UhML+GPfQcUDbSKW+gpaPm/oyQ75Mq
        7AdtgBkYRP/bUlTBkGO/B1U/MITBa6P0jYPvk/zckoDRqAIqedCmbaDAIl4xrlkS
        DEzeekP7M/e+AieB5jpwA7d3rVFk2HUeIvCDWXFqkU04tcgz034pTX25NcESqlbt
        hTUpRuxa02RR46KchwrL1feDW20SqjnWhBK6CfSPBKc/EUuLIsDItpACfkqOpa/H
        UNQNsgrSnANwtbYn1HCxwHewBPrUtuf4/DxwIuj59SFNuMcS0+Twy0H+/nOvB5yJ
        kADqeiVaKyTXKKyWCBcrDpD/3fCBtg7oa0a7xwikRoVbJl4C3xKKVcNzHsQlk6I7
        ZKtWQHYwVikKY91RbzGSwrcgfnc8euAUzlVm7Fr59WpGw8mMI/06WLax5WGf+lDU
        ZgEJAhC+b6vK6I2+hp7rlbS5GRRHuwUzFKImX39m3ccjkWqQKyY5i2W7KZJtnMCX
        NyjjpR7Wi3cDgjYtFBx/4ClddI3og9RauA0Z2QD13jaMb+ANMU+51KknGwcz/PEM
        /Z1cTqqkMA==
        =JJzy
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-06-03T02:29:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2ARAAvU+mpV7HlFoKqQ92zEts1b0knnN56MmziGr8yf1cPsKc
        SdyQbC6A29/eOiAHLV04jcgfOHvbCP9Qo4zeNu7awVAp7LLGAZzDyWIygths99mD
        L5AUgoYf3s626/A8erPQkKNcoF/YrTM0HI2KPrqtlrCmEncFVT+mGoXQKG+xxfnM
        RzDbO1SvwqHJ71wQstZ6ECrwEU1qWqI7zj+erhTO2Cy3C6sC9ouvYZAHqr2Zzz11
        sMUX8NQ8ZR65970NmpWR4Ha5Y6ctt3U+sgIZsOCntx0iE4ZFSzWe48kjjpkd11Vu
        z1HUBd02XE5mzF2UgjY6VoDRqk0hgobiyMWzAoRbVkgPv8o+AT3WHfBgJAy/8yHZ
        FJioFb+yN1Z410YD91CIESKfFHTdxXFOgxhmW4ZOMhjUshuQa9pj72mQ/MNZJ48W
        OpKFzhXVPVHhwvWWRcJngXCT5wlDRYdAerxTFf+y3db7GxJmATvsZHfxz+z0I2Ob
        3obROH5DoBKN5mftpApWNbDKfJWv3c3O1dipXSGz/SVJf6fTMzyPWX4myUUZ4SmB
        A8/Sq+B6q/iaTsIa6dFTh7LuCLCKo5nja6dKOayGOXR4RSlbN56Wk9IuyEHtedCP
        mVhvomhM1DBsuFV58u5DJ6bEIDuEAVO0jaUJmTu1YjrqQDIV1BJAdUmaTHCYHP/U
        ZgEJAhC7JSNlHDJziBVj1r3r5DkzJZujf2p8VxWjwKmglsEX2IBcwEPo1WSZmSnR
        /1b468BbF2my9xbR4n00nELhGcIkhjvdu20xBmgmU5Ww9UsJbwsD92Y8KjbRayBy
        EdNMgK6G+w==
        =6kgB
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
