apiVersion: v1
kind: Secret
metadata:
  name: redis-creds
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:RIFNndwmNfWSlVgkv2HHWtugolcIQ6Xx5SFt4UloA8CzMd2UH/tE9UAxFEXb6JdC8+7ibHZNu8VNWaYp/A==,iv:vOqUI7aM7fL8Y23tlGNoQNTkmjiEAKnXIoDLcf4C/P0=,tag:YtHkul2WblC4xXg+ltrrEw==,type:comment]
  password: ENC[AES256_GCM,data:Mfs74hYGWFzO5sNCDhwkjfZAwkU59qHG/cdotV10Zbw=,iv:WUB5djUm87WJ9xgZcQJit62nnZe0yMeJX195Y0QjFzc=,tag:7a6rl61rq5OtjQsZTsS1Qw==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T06:27:19Z"
  mac: ENC[AES256_GCM,data:6yc5jCHC0PZOYeSyQbeb6ZIl8w/MJ1etQV5/WRlaiEF9/j8BIahVYcuxIz0cEAR2WSTGUAH3xa9eVoyr3VTQYH3Ns1GHeErl0u0QY/Cb/5tCzobhBBhhlGnD25QnB4YWk7lvNDKQ1wnW0rLSXvC3TsumLGn+SnvJW7ZW06PjT8A=,iv:UwGy7RoJKO1HlWMBAaBk7C9b9Jy7fsMSZfFZosy+Hrw=,tag:tasJ9gVXNze6MYz56TlZBQ==,type:str]
  pgp:
    - created_at: "2026-05-23T06:27:19Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAjommnTeOIfxqELr6QBKjcdszRSSTuSbZKbRNTdTNC5Od
        3Gi5pSn/9H5PSoQd7M8DQb9At++vpqI+1AuQ7fzAi9zjGg5Ol798Qx8PEvqxuSBH
        Q/JKXCT+PhTh9BbkMa9HbPtwO8Amj5T78Nv08foIeFsaF8cRTkOpTO0jjXSrGb2M
        xZKLheyNeCQE69yl/9BLlMfLxE2OH0KMEeUs7WDbfmENiOQkUpHUWZwERLCW42q7
        /5nwJpyvPBLRIU6C5W6HczPkgEZAqJw8A2pbbndSXxftxgtMHFb83aHfufAKZD0l
        n5LcbzBrrc6rDDm53nFO0D+w1LO/cZE/ju2t03RkbVvj9MnajUvL1jqR7W2Zn9XB
        3nD4FiNZA5GseIJBmebe8AIMODSuX8jdhpRWeIUU7ZYBiExILNE4l9zYZxmj1Rde
        htQKG57i8JFZyZj7cXTZibOUmv/4Hm6ZKQSqQv96fKBXzHBOWzcb5a6ECrAgHtzq
        fNEEcpPxPrnIlO/pVXfyP/+APi7Y6WZTAenRASkWLW4aI8GufHi5Mt6Xat10nAci
        opeViOM4OABwORF3aFdql9mcKw6+Ivl7SVmWs3r/9VMqun7lytUNe6BQJbk2J446
        zYFDSYCY/ixKkj8fFqynTuhLW50saCMgkpYUyGY6HFD/KDiSMZbQNXwq0i4rTMnU
        aAEJAhC+J7oKIHxLuA7OWSH+U0aUuG3EdhHsSxdp/XTBhpcpylYUhUVCImoa4LEP
        FGSlZ6KEfQf960F7m7RO7iii2b7r4gcQkeaOVGU7mPyhwfzYFPbh56//6ft0gp83
        caVmSj8wMd/J
        =aSH+
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-05-23T06:27:19Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ/7BuarmcFPmnIyFZciYmZQrZ6kXxRBl87kDIgq551tWgz4
        OVXAwVsoxD/zxGzNMNZ0SA87lMx50h5SNQYmUklUznX3FN0YdGnL+BywQX45f6Tu
        WjC7EauzOv8oJiueP2sd3tHaIqkOzOBek7+mj26SPJKzsmaO+uPw8YVrW5INBPYX
        OiQAARxgWU+lzzuMwBixCnacjJeWZJUtzAvYEAVZ3gTKr46+HvyMN/ba2faDXFB7
        gP1zKlEMzgPiqILQ3xFVsn2UOKD033lzMrvGfWO6hA/ldcKPPlJEQlIGygs5Q59b
        JnaBr9GHPjP6rN2uC6D+1C3JIMYeQXiyAhSA91OcyfJmrEUj9dp7SqEf4AlarYGd
        2WA3+t//9znvbEht2IFm1eAJr/Zb2yv7XFDhQELY5rrg1aJ5AzHB1i9iBX0ZwXsd
        O34+shEaKIZG6s11WcGa53JA39lXxPXUkwFhmyIiFVyXKMW6heZMv0lP0ee42sRa
        xioonf4AvNhzAN7mEnvlR7s3JqhZ3KvAy5V6HTRqXxRpT6DjxYekTz73wtJZ5f5q
        avMDYgFjT06vQJlOC4hz4hSUYYUk6bp01xH2Orz6nV6CHf2yWPuSv8AgK1Fv4JEf
        EEdrW3wQf6nvdwngwJQVflHJP0KrdDPvLJfsK0kIVxFXElJkG0+G8FNrPqUxOd3U
        aAEJAhBik41xu5FQDFw+HB+yxVsMyVT2uSQn5TEsRUHhu3HD06jDdpgQIOHMilnm
        wSvvH4FqpFa/OZsoi9RGKASbhlxf1x9eDe99RrMfGr/6wOLdQ0tGBKbS6LjTtGll
        DIZYPS9OMoA/
        =Q42l
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
