apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-production
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: flux-system
  path: ./apps/production/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: production
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
