apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert-manager
  - traefik
  - middleware
  - postgres
  - redis
  - grafana-prometheus
  - grafana-to-ntfy
  - ntfy
  - loki
  - promtail
