apiVersion: apps/v1
kind: Deployment
metadata:
  name: instalock-web
  namespace: staging
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: instalock-web
  template:
    metadata:
      labels:
        app: instalock-web
        version: "N/A"
    spec:
      containers:
        - name: instalock-web
          image: tahminator/instalock-web
          ports:
            - containerPort: 3050
          readinessProbe:
            httpGet:
              path: /
              port: 3050
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3050
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          env:
            - name: NODE_ENV
              value: production
            - name: VERSION
              value: "N/A"
          envFrom:
            - secretRef:
                name: instalock-web-staging-secrets
          resources:
            requests:
              memory: "100Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
