apiVersion: v1
kind: Secret
metadata:
    name: go-example-production-secrets
type: Opaque
stringData:
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:DPCP5MMvIm3AB/Uf6IAIDIZNsjH8f5GuDA==,iv:NmgjRdH2MyhIiPGxtaq2bFB4wurjyq3suzzcXbtkEQM=,tag:+2SbcA1BBggqaqvpM+36Ug==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:AT4p0GutBX3N4VSMQ7JcuXNuf57w0RKG62JDpDWnZQIPjPcZB9NaYGL5jW204m4=,iv:9rv5YWlr2QG/Fh0HWmaAw/MyYgARowDG+0uA+5PuRww=,tag:raZNV+ZlNvwbVHQVvx1Img==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:U3qLSONhiv+aCA==,iv:R/dJyN2BHYQRyGCjSgJF6Ad9LB0GGgE6UYFgfLDG0b8=,tag:EMO69wEagnCgiY8TloKkmg==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:IGJkCw==,iv:Q9yw0M0E+jU6Uy68IXe1NRVKtX5emS0kMIYDDvJjKA8=,tag:eJ5GDDo3Bsl8qJ+hJPwfFQ==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:5g8SgQxtz6s=,iv:P3st+ueEy9OtOgUfO52jOasC5XljhIaFb6i95YuGYAI=,tag:C5mBwzqSh9wkr9q4wFKupw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:hX6dJhnFDApCbU9uHKzhd7XRUXckWN017E4Yjtd3IenRGJPVFF0Tpxw3Z1RMGVgSS7RPeA2IvABvwvgG+XuUig==,iv:z3NErEgIxmq+nbYRU/dbcldUVKz26Nj7b0Ft+yYumV0=,tag:btK7wmnH9/gqavblSy5r1A==,type:str]
    ENV: ENC[AES256_GCM,data:Ud8j1tB73rTkbA==,iv:f1RoYdY7QDLTaxrm6sGLYSBfmurx7I1veH4YXsrYr94=,tag:eqn6wiRhYDOLUeeU6hjaGw==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:w/bQrmC9I0cGKA==,iv:M2hHpp7/3e4UbA0Yb0O8TeIg/dG/qVIjbslmlWn4hJA=,tag:ftxawY0lA2dqEWdgEhGJHw==,type:str]
    VITE_GRAPHQL_URL: ENC[AES256_GCM,data:YJVYimWCr7RkDhSyhrRjmmZCDFoXq8+WeDpNWus+tQ==,iv:NcLmTvFsbLh4yjeZtjEGejPu1pEjvdTvgaq6ydqdvcM=,tag:3vN/RYFNqjMqZM7NAGLv7w==,type:str]
sops:
    lastmodified: "2026-02-26T01:12:35Z"
    mac: ENC[AES256_GCM,data:e/38eR3K8PHhWFfapI6u6Gsee2VuolYToAvCJRJBN2zvJzh364N3mcjKCRqZP6m2qdlEJ6jE5p27MBOxQ00TNf+Dyr+1+I9KlibjLR3S5yzUaYJyZb8NCCvxC/W1OdiZIVMzizNH2L2wxnXVfXG0OSc30iWaLuC3aZdR9AjkgB8=,iv:0DwBMhXBzynnDO13DOsmKhNcS+Y5Jx/WoYpwOLdt8XM=,tag:D+PJfWezk1D5kHrGhFl66w==,type:str]
    pgp:
        - created_at: "2026-02-26T01:12:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYgP05NwJ3CAQ/+ObDxo57ZLBCesOZ6n3gSF0bMJEO9OMekWcpTtImkNfPR
            qvb5VZtKWJNWz0vu47iBNlOTAYbKReV0z6EKivRBt2BvaEbSjuHhgj1+3t2EAUcZ
            99P8KGvQ85RbVBqAGjhj7YVuHGmB/jaDWvTa8gz+n8nsVno+PUXgfqsTMaGNIz4i
            9d8eS7POkQJsHfHkl07eUX8RA0penCmDSu0lQf9RCSZMs+x4Tx/kshqLl0/K2E6Y
            glDyqBJBF2Iebb20TJ7YmxgTq/ONyC0qdusvql4kcVo41lMx33FT+3wt3a2q6S/p
            uZqxgGHD4O3HB/7fluXTV7aB5LPGX4EffDl5pfzI1eLfK4CEMUKSRYLmkY8C9STI
            U3ydDjx6BufCBJK21ASe1gIemXG06by5iS2shY7fS/ok37Uk47jG2Pzns5hloKuK
            OBVXQHvhLBCJ/1GhAKPgzJFdqX5p59MGJD1yRaCmslGqHFxd4oaL5b8zQt84pWf8
            7NCCO7GLEW5mMU+iDaT6FSXou/QZ1lPgjOCsYFoYmXd21wo7UffDAog9PUTqsDDH
            PwkPP05n02tPZfV+LDPlUXOWQGIWsNhS3N8JiSe4YrfdDUdXUmH5b/rvp7IjnShM
            Xx7Kdn5XkXet9x5b/h+7jpMdHBBx6AJBqveWO9dl5x/5fNMtnAx0G4yO8oYL23jU
            aAEJAhBTLl6Kf5g703qq+kvMobXdiAJTQedrdNfpyU/5LsdV0MFRkpZFiLoB7h59
            kZqnkmYUIdcR7t9fF9MQ6+OLr0LDp7Z2+xquEjjsaPDuQRMgS9CAaSGJP5VaFDaP
            b4LFGrIlAdpa
            =x5ad
            -----END PGP MESSAGE-----
          fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
        - created_at: "2026-02-26T01:12:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7m5W8M9NGm2ARAAl06b71zxrg9JvoTTunNB4RqVA02Ns120BaUe+HzqKM/a
            tF4uXOvjYGv6KhTV5BOdb1+VrCDqIjXTTe8sc2XKxEtvN2WZQFQPUVMVtfq4cU9r
            VRCCCCH8tk+62mQIrX7ots/ehAuoKA7DA59/sTGEqmdZAO61JsLoE+F03+JywJET
            dL71M7jZ6ghofevmH40A5Lz37u9ZumgJLhwHGzDbbSLrNKfxfn2HxG8/+tu+o4u9
            8UMoGN3uEM7Cvu12SCA4cu3ncLbO5Aw5J9ZNQgQpSOHysvi3p/yXulNaWkh9c8h2
            +v/lEv8Yk5x6lBIAL87iokkZKF8dci+EuAZw48idtcFKuP2pY28F2lKnDl0P2N3J
            UceSMul7zhJfltAWNuZh90yMKEQpNRRmZ3eSYTlXWu6aYt1l1EVzU0ua8EZUKGow
            DOXM4fkHVVlEmp8nXQbTls3FMCgvT4FW9PP16sGgF4mlDW+NC3FY7UQPRBYqOpda
            X95H5rhdf2xGRSnQsW1LRiWwGlRBOuMDCPbH9UKgzxaFB/JAGsLWGsn05mRhwO/y
            8JZZP1rZuzZd69EYiTcPHg3fEC0YAhHxKL0U8AkX8yiQ/RdrGqPac3VOHfgzMzhy
            /YDMCg9yfV1hjIidsMgn42+LtxO8fjGIrP5f8dcthYeBnaHue6BilvcNBxg0USPU
            aAEJAhAEBGMoKCxIDeF7jqL6KgJfz3T5AkYlmjISOGHbt6VqmpHhR4FPU8boOOkY
            Q9fJJuJ67Hr+nMMjQW5QQviXNSSG91SGxisW/q/KnxlLf8KLmRl5zU+A775TtW3x
            y7NvfRHpxdUA
            =lm6A
            -----END PGP MESSAGE-----
          fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
