apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingress.yaml
commonLabels:
  app: excalidash-frontend
  environment: production
images:
  - name: zimengxiong/excalidash-frontend
    newTag: latest

replacements:
  - source:
      kind: Deployment
      name: excalidash-frontend
      fieldPath: spec.template.spec.containers.[name=excalidash-frontend].image
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: Deployment
          name: excalidash-frontend
        fieldPaths:
          - spec.template.metadata.labels.version
