apiVersion: v1
kind: Secret
metadata:
  name: portfolio-production-secrets
type: Opaque
stringData: {}
sops:
  lastmodified: "2026-03-16T08:16:43Z"
  mac: ENC[AES256_GCM,data:sLNqX5EY0QeofuqS6zBBTIq61y23TECvlT96VB3fKxEVGZdY6nO4k3nCIXQDv+TWp+nT3dZoaTY7K1hmGlWLMavREJHggugZPKaNM5b8+8Rvk1Goo/YSZLGNw3E2eeZKBxxGXcR1PKaCgjKZfd5AJXh+eEvnHpn2b9c/zkptD/U=,iv:C4YJqYbCVU7w5SeEy8RCLQrXYhGQ136370WFkizTSgs=,tag:TAt93ISoop11nuci7x+7Bg==,type:str]
  pgp:
    - created_at: "2026-03-16T08:16:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAkTAMINEJfg9MxKtn9h1u7HF5YJBs7I90LTK7bxgIoxZY
        33bIzPOUYtgR1JcPXVo+gPIw9DP7pMxCh/SJ/Y1lhIU2laNL4grRR2g3wEWn9h7N
        nvvLWnczW4KmhPcEIKh8I6AyWgEFAlqKFAQvkm9EV3GVrvWdy9PXvnD5pxZwYBlg
        cUAOUYzFvX2es6WQn5PTLeqYz42vynVuM5ecJyprQixpjaoV55A0dRvL2bKDVXKN
        mQvXhT/buMM470O+vl6fpIhxKZR/zXDwt/hX6wqLoOI/UfyA5aG9t/obm1u+SIM5
        Vi+83SX6KJ+ao/DMCa/f6li6x4/R5mUT5vo+Q0Zi+k0j/2CR43MKPsb1fIwW8qKa
        hAASurO+pZNyNIxIJp2+nk8gnijIx0c2mdLrw5WARVwMu4B92YYXnpozN6xOaqyo
        NuADdnM5I1vDNbIKVWh9zAbLqdcF0qaOGL/aNKMfuUfBctkwCOtG/qDRcZQ+Ps0+
        BPqM2y+RMUcSsZ1YtGVLPn+KmYE7J2pk5hFeIyn98Q7PWsyFRzarm701djIapmbf
        YUod7eMWOMwzx7wpIf/gXaOqp4+KOc4qBkBWoFb148xBouO2GblcI0ZIZny4U9nK
        6PTM4Pe46Uh5uqExNsCRtHGwbMt06lRZv1hXcWrowHqhZ+lLL3cn32/H7I+ul13U
        aAEJAhBwYl34/b+y4IOWy86/0NDIWhtknB7S8MO9VMlxAGWpjZ3myeMZrlQyfEYn
        KYKoOng1BVUImL0FoEugIfH94E+JMSIlcONmbVhmu3pv6K8HUEu5Ai47KmyWY1Y3
        4cgdiJMxYYpM
        =EWOg
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-03-16T08:16:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ//YubJ980hEiRKv7aE9G77DmrbAuaZyRWxt/DZw/SPcW2H
        vaz+qj0MEHGAInbCPVBxOJdT/Od11sn/wDBgDncjPHIiPOjmiDVZiYF7uCbMJi9Z
        d/PIXYsXZOijydMH8PR/1PNyUtiEdAxd2y1gFM+n+4lVhy+fp25P9RwDue4PJJdX
        bdaLiD7J2Pv+HP87orevDzOVNrlx4EeVtY/kQP5GgK4XJd2/sNYOgPMxS4ZKZRQ4
        5qic53ozb8ApbPfYfwfR7EiJI4mm+RnsyT1HoO11fGQjKKJmSowl+hw7XmGAWVYF
        0VEqqtJtcDCfpqTJDvhtTShDy4X6m6Tm4XU+gAlT3IYQiKQB++oSVzkB52/uXENU
        8LkR0p35fQaQKChnsAxtziq4iAo5qQuiYgUBXV6aL4KJBP5EdHk/H9QJ6VUUicJC
        CU/9MEahpFIYeK1undosK6aGlm6T2i3ifDmfIP3hVlIQD1UNrDzJ+yz2Q/smNGmF
        L68aYyNzVcqQyR5WPVBulJQzXSO/hRMyRhHgmf8wOtQpvyhN/fgWZ5mik482vgNL
        vPlryp5/yF49d8cUipIq+V4JdT3QrGajOx/GRTetNFi8UuRXWHlNHHPbRM3cBJV2
        NkhBYgJhae0gldqPBFIqb2qA00JKIrsyhwDjE9r08/rkOHRsLhVjoBn+MvwJEQTU
        aAEJAhDyjX9epm+VlKEAWEtrKnneHx9WuukWdnX0BNPjVHHGdBXWG6y11ZFr/f9g
        6L453Dj/DRW3jkFfZ0un+RfYYgfuHmBQTEUi01WXwIMSxQ6EW1NzHpmmqONEiGru
        dIjJ+OW6+lS3
        =uWhI
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
