apiVersion: v1
kind: Secret
metadata:
  name: instalock-web-staging-secrets
type: Opaque
stringData:
  DB_HOST: ENC[AES256_GCM,data:vyKkIhxaJYCpLngvXumXpf0iLBq7pSJowBhbwtFudiHZDCCAThDZPRw=,iv:KLiI2rKRbAoho4jz70kwegtTzuN5zbtN3kqCWvpWQiE=,tag:hqRW6L5pJWD1uFIuVc6YfA==,type:str]
  DB_PORT: ENC[AES256_GCM,data:n5b29A==,iv:xZ5oSJAVnn6Hz3QB9dCy+zGPDRDdSQOWZNPnVY67A7g=,tag:D89uEJQd39t5FhTk+ptRsQ==,type:str]
  DB_NAME: ENC[AES256_GCM,data:t5CB4yMXFBMxl41cx67EhpfUUez83foN,iv:dQUPr6RHmSEjWeoOCcLEeTUAqV1GLWsHByQJOZh/aK8=,tag:/C6ye+GdhCZAALwznOpjIA==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:XnXKqmCf12w=,iv:W85cJfWgLPRG/TL9spSDlExOk+GC/ENzTtSTCaVPHr8=,tag:kydq1KslB9cDC6NaV+Vdjw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:vbU+wIvBWkQkf2/e1FB6FmDedo7tJz5xF4JLXCPs3Q6vtPaxREpNJrv5cv2mjaU5H9PLPyHtX4Db1MTt6Id6Sw==,iv:F9nlaOUvfQoWOsDcUJuausRwP1doo2VniAmkCf4t/h4=,tag:XegpHwhvpQPKe8Zpdkmu5Q==,type:str]
  RATE_LIMIT_REDIS_URL: ENC[AES256_GCM,data:VeSPCpslfOZYJo+902+OVuD/FfvkmEpibcHOM06ZNKS3+gkj2oOT7TueC64vyvsT5/CbOSQKk32dZyrmWOw4nd0MvK9hEFFCs7a1nlooq9lq/i4rAR9z,iv:QoG9VtSzArVJlRmbHDWu/3rqiMfUcgq8BNpTBBVurKQ=,tag:stU0cnOTKByOB7oGAexs6g==,type:str]
  CACHING_REDIS_URL: ENC[AES256_GCM,data:4L0nMNyJCBnjS3c0OwnT0MhPmWhSQnQndwTGe8Op7cx3ULYFqDUhBhOPiNhaNS9jnICd4UFmLyLE1Cv1v96Fy4YEH9pKgP6nnLN1TJ6xemK9i1wQVuoI,iv:KfAstF3hjgGuFQci18e7BUIpypDL2tPB8iuXDc4GyF8=,tag:+rY0hrqdxCqNgB24BEXVKw==,type:str]
  STATIC: ENC[AES256_GCM,data:FPgk9A==,iv:IzNpFKzvAGCVwvTBgHVawYNwNkIui0uAJDMvHWrEa6o=,tag:zsUh/B/O50aUhUdCKqOBag==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-03T03:06:18Z"
  mac: ENC[AES256_GCM,data:4T3pBSN6YA2RpumWjKVF+F64lAkAOpZ+MCBW5AYOES7z/k6LYTOwn34kklNwdpC/AkM11ywHd/ZOOmfQHx4SWCslg57vd5eAxDRASkkciTjvgVj9Za0B+sYGynaRIHTYcFYGEY4R/tHuorGvgRFHqovZ0EgWBAzujSogHv4lMA8=,iv:TQJ1lTVJ+AL1BAxcCjKRcNjSKhrSnrZXfAYyxv2hsGo=,tag:FxiHUBhZjam04gBGkrvm+w==,type:str]
  pgp:
    - created_at: "2026-02-26T06:36:26Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAgEgZFDvyt/CVwuWNuZf6lu9jT6d9dnjqqobbpmhtwnWx
        TKTvfatCynkUyFoVCR2o10jTUBJGgDZl7lqnYN7sSqEW3973tpGNOzYjVd477RDs
        zfQNuejmWy8nd+tuQB3+aEWFjJpDXMQO8Y6XUKP5vViKz0AgNDfqnDF8endPpO3b
        UyC/3igu60808Cow9MAbWc5gU15hgYxcsYMzVQZfqmA7GgPgtKc1Pzxem8ktBia7
        QmWkxQUo4iIT8IRrNeyrILG5iloiVxmvt9K9Mc3IYqvxFGTlhEGiv2zIs1Hhndjo
        nd9XGoM+9WyMaOEnVzTsGMq+7AdQ60NcwvQV1TWS+eZXVi+0yyBT4GpEmAdmUB+N
        /FxD4f12IkcyARnL+YBkwT1eO0JTjjrj3OgUa6IhQ09qB5MiNh+GT1myv76UAhoB
        fZQ8zfjLg80w10/VQDThh/ESoHc10WwQtwuKd3wEw6Y2L3uCEu4Av+YFTj+NTMZv
        TADNAy3WRGRGgkW056WeDf3R5dgdDWnjL5EpoMazkOAqMI3pdWY/L/t+5v4KgoX5
        3cS7M/YpB3f8mB6cw4W0Nz0g8E4vJit9MTkGjyLbUqU9wGRFyvuR2YP74nZNI+GP
        OHm9IDB53V2MyP4V8Me3OTTKji+wVlE03gwSjM20JbJ4ILbCzmuAUnW417Dot8LU
        aAEJAhDfttSnMNfp65HpWmeNs2lfTMIucAoG0M5wiZ2rW8PI4UW34eesnuiNPu7s
        1k3lBXJw1KKRRZyVX6BHbRmLV/zIxZWQAp5mKEqBw6dkKUUYKSCPuuURyGKYSzAu
        SxzkzNBjpV7O
        =83Cj
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-02-26T06:36:26Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ/+M7nf/+Cx0EsuKCAKb455Cymy0IX3V0WizaiLydbF+Rjv
        H7xAfRnZKXENhY+4ckz4IvPTFBCglpqJ7cdgH1u+xJpq9r39s+NYSzrRKcFZOTiD
        zTVROzqwB50ljq/ybmyrmlpBAFv8fi1HSANEYc8ProTj6K1uk55hzmOWnIl9LiSq
        HLXpbKQgM4v0s01FAZKL+bwvTI0hMTlGaMhoqBPJi8CTbVFxk/OmsVFTNbNpYfL2
        xKAJoJRi7DiExvg4FzLRSMbQmZFqimCjh0xhqO90a0nbMo+FfsI9np5Q3alVfwa+
        GWit4hEFT3fFdEBYvi/gTLpT/TdAdLrvOHUz1F2La75iqsL3U9qPMqXDyrKNtZyf
        rcnakKiYncZGfLop/Jba0KxfRkd3s/IBNiZ7Ih46gumdh6LVqmpsgrt2FMl8J5QH
        O5o95dFoUBvRxQuoBxziCpUpwuxPx2ZbNbKhAW8ZbSrhJ7Bsqu8s+p7Id71yKpq6
        ALz48UTpn75OK8mFo37J5w+au20wW8x/L+NwQluqU2QsSpVy+ykn9EI+fGJyyFOD
        BSYloEmUq1LiDFqSmE52iSWJCJMH2/vpMB+kG9HVM2cBX+wp2lJP8iNDrqyf60md
        rq2p/IKcJXU+zAPXtVrgaHWWH5Gn+SaG7iVGduKNTOYgyl3MpPBZHXI4g6VSQC7U
        aAEJAhCmk7g+uW7akYgYdxm4YWWDNeBBxDjHswYd+Yl+X6VaQJNq0wFz7WSNvr1v
        pJhNorj/aUH+aVpN8+ehww2rUS9uRhAmuAs+mWjiM65tMDzPU16Fpu+sKcwd1lAc
        Yc2rAu5EwhMe
        =41Gn
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
