apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-production-secrets
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:QNV2Qzv8+TcAVGQZ1hUJEXITANOudjPKTUe+6+K1UQZq1QJdqTNpy2AiwW1vo5hNTE2B84FkbnrcD+umcoEAlxg6DZjRKE4ENbemuVfTpDThUSZeXVkPJiQU9kuzX8hjEA1bNeJCX/Ct0NVhlglDxug/9BqWw8s0/p4+wM4CSawgIWYnM+rvcrseWtg+WPBDKQ==,iv:/qBrW3akReLV4yo2NZ94Mrjmuz414ZMwDLr76Vpv8O8=,tag:nm0ltLf7AlgaBzQyxYvtaw==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T01:51:46Z"
  mac: ENC[AES256_GCM,data:Rf/rL3he6UHgu4XHMu/Wn9eM6uyNEZjX+HrZLDZAl0ZhOFrue0s89Rs47OVXW7nVMNqvlDZLyoXaQTGTTBvO4rOGAll5SWXXVcBdCWW4WBZNFDRybhFghYxJfQCNmUZmJkeYCHQBPx5kbk/Lu2samEMbSamUFmOYL5kFb1g2l3w=,iv:IKoKPeO1Kz6WCZtrgxrDJZZI8yjD0+Qsy+fIvLgE7pk=,tag:C4uk6YON0HmgVbtq/ThBew==,type:str]
  pgp:
    - created_at: "2026-07-12T01:46:32Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAouGt4T046P9UyFz2Y2y6T081gV3iqiQ2euTUIBUFkhvl
        dooeO4COQZ+Dyz2hmwmRqhg3vwFDb/4YW9WJka8RGZS6aOcIycPLLuWqQ9EBWWDi
        Jonym9/QvTybvDg7FeVBaDCzZvSz+L804ifswVBOfeMh6LbKiG3XK6t39iFI123+
        TIOailn0hAZ8pgnIsdtci663u2fUqPlFSeAJ5VwhIxl801dVh9WZGQT3IbWWDmJh
        dfYhApslmwxhyvECRjyANh+sGwAJXnimS9Si6d4ukZeO1A03qUzeYeKtaHpUv3a3
        Ba+OSXSZi5lUVeyxgqp4U5mr2iRnhFzaq0sjs27PFKIF3AmN6ep7JS7gCw5lQKjV
        oavlpfdZpts/pa831Q17TFMNkfWg/CfP7FFQzTvZHfPKyusuBdui28iYNe4OMUw6
        0QYBkH59D/EBmZEUGOezkIr4RPK90wYTwHmMJWfAGfQCwxezm/MmXVUstuZT3tJQ
        OrEdxO62WI51L3NmXDbFRFW42PBt/3ppeEus28qC3iYzq5wj9f7DIF1PEQhbzvDO
        EjyNhm2tGBo5jc25svuAErsIq+d8sdWz5XpCmKIx41dD3TmXgmyJu88vCMmK4Z9T
        7UZ7ub7qpSQW2t21yzCI8Yi/bMPLKxaUBmG7zwKXKqc0iWUh4eQ3ANiv3ft9CObU
        aAEJAhArmHKMKcA3K59jiDwqrp1TEU6e59l8+wAPsOKRbV8BLErjNNAdVYq91uTj
        ZoLrisCOpVNRws/8EEwH0dF1u51+xyfyiBr8vFUGvphSUxnlHsoN8kX4GkuUgY9n
        Quuc3Jsgtbvo
        =Zzpe
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-07-12T01:46:32Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2ARAAogPj4hL7UdHXsbn8S0buCvyf/5cTnVoeYXxFi4ZFQKlQ
        gV8FZQt3bb66k3Ud8sqtyTFowQqdHfC1+Huv9GFjevm0rF9jugobT4jezVBrfwEb
        TkmP3GW8Rqovr8cMdEiLrQ1bZPxfXHvdGDozVIWw87b7QTnlu1x/Yqr/P21wlynk
        1ixkNPCHScQn86adMs5tMYe3O/iBPdf7Md22ki1mN05y4fpkI9DX45qk1INcP3/r
        2EnRPyaFD8GIe8ZMKUFpPgW+WwgsXijMYyz7N8H0Ta0dtPc0KH09TrqgMz1uBhu6
        4yCRdsLKHGUvtHBJV5kOfWPLR+1Cq6buYSgUYFwUZxXYET8+Wj1d4Wj9jfA9OLZ1
        MdfatL1/QCL4TrZrFOM61yOIJjM/rVHEh/mbHjukZqi8yk4bXpokLGBDNI1JMZqT
        6Qj/TmEV31Z2keIZVrhSYkCxxjOIxgIEYatWvfyyQjU0TXeqjeA/0MmUlj2FNRZj
        zTsXvgonL5a4voQ5mMXkZAW5sabQe89X9FB95uSqs07BvT8zZv3KvwyfbxPb3rFq
        0aTXKCemEljLrmIqKCx8pLWl3YTLo+1f7JtFBwRWnZWCxEuOP4CoeFUj8/Bx2aZG
        2K4NGqK+E0J4MdRht39cOq6nsOPi2g+lg3GOOcPokcc2P2IyI1D+21nDiSqRuNjU
        aAEJAhDRONzDiaqgPlP5bc5yF1EquycE7uN/7bfwYeXKOu0x1qViWAjG2spLoTKe
        sYAgI8cdxIARNZgMwipx+bYgvdtrlzNbjZ5r4UXgAEiUb+dD4vS1DMwKwe+ywywp
        7dqt/7Ju9zX1
        =QvQA
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
