apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-production-secrets
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:ugJWugaBqSz0WrPF93g/3MSDo4Cv+d/v4YQlbcN8M0mHdg15aeI+fPifhBpPvA+jl+GLDxPtzDOCKB29D1CujUxnUV/95DlmjrCOrS0KT93bqcEd0Jw12+3qHyy1STkJq1CYfkNbQSOll468zJ6DuD+BCWp6hesmImqC+fh7Nqk29of2686QZFKRaBuB/Rr6ww==,iv:PQwRl3WsbbZS+JZkl7PQ04F39WXJBuo4Nu3DGGLuEhk=,tag:IQRQwYQkuOqAf6lGqKisBg==,type:str]
  #ENC[AES256_GCM,data:IKz6bLU+lm0XYUD3Pfp4Mu0pdw5Orl2INTMhyc8PTNeBCLYq5fwIPcGq2fhia2bqB1hpDFH33m+2fw==,iv:KWVkrZ40NT1yll/nCfAGX/V7Vnis/6lsa8+N+Kk3jP8=,tag:T33WYur8nNN3zGJhyaYjlg==,type:comment]
  ADMIN_TOKEN: ENC[AES256_GCM,data:gR5/58vvr7znjreMCsHCcrZYh0JYKn4IBF2yay/dgufCNrXTEtsPm3AWWPiLN7xODKy7andIBg5vZJ2MYMN3PA==,iv:oYQ+YLdEBjNzfmzC/ikfQzpd3F/nv5X/xKczG88UjDw=,tag:d4Rcf0c6oL3FVG52Nq6AHw==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-13T04:12:26Z"
  mac: ENC[AES256_GCM,data:umoo9omNRtdA4e550JP34YnF+3boUT6fE0wD2CjEBgZXR21PiexGkuuIBuP3NKNH4H0gOqEIc2xVZmUNaN3gz2dWyDQUtyiwaNw2G43PY6pA+DQEzWqI9u0f92bwou8ctQe1xt64Ttr0KQk1Go4+xdU11N+fjeSUWSzlY0pHgMw=,iv:dD1YJf/7zu73FxcS3JrK9helc1rMx8Sdq2dCZcfDkCY=,tag:KzIbrmMiAzB8XNe+AngUaQ==,type:str]
  pgp:
    - created_at: "2026-07-12T03:28:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAluW2DkH4dfFkJ/x1Fd1yMcUXTwuO6aSKvBPR46bW3qx2
        mBwfy/k4R0NlnW0VL05ILGveq+eiZpQPbQ+ECuePy+tOrhCJkmruKyiuTp00IXMq
        WeNPCxMHACzwnnwW5eChxRgncJcGLz41dtnXL0E/EPuIJ4q5d/5Yk5VCn1hWqyrl
        bdirfOTn9xBs2/7xp71nadcjQrObuAn6x/WY88boTqa95RCoRnGFDKMqDyAJmHNF
        xd8ALaiZt9k1INUNyye0yraYhx7QI4n7bVyKTkFMFKST9cGaPX01cb8Wnm9YI3GA
        VQcF9YyP6DhUu/2RVqrF2GK0qE2YzUJkyKeeToMiIayp8RJ15wBjMvPCAjM23+ip
        MObw6KzvTvRpGq3+4+ZJn66eDK098XiSasAEoB4DZYpK8o3fdnx49UAdgzycHSsc
        feSiQn+1YK4GBg1wL3CjXg/yjYMDzbms1oH3aQc75EU4qabKAaVyHql1c6g1L1so
        SP3L460PpiYb9tNJZlug/jWqatWXmWjI1KSvPXjHzDR7pZGqRyUBow5dGQBoaY7L
        +N8JHU0Gfz6aWcn41emTeMkrfjMdKXkjEI84RBkxnnoa23H04NOgcxLpcIvewUD0
        LMTMu4qKNbJvFg7SUSMKdzg4ODVy66eO7o2e7VpURIkvAv8LmWQ4WzkDqt9xnCPU
        aAEJAhBDiLfzuEeK7nbarRye/5dT+dvjj81rfCcVTiYt/VqFrozpKnFxpMt0qbQd
        6DyTNa46Xcago4KFujDWcmJvgoWehKVxTUecvvGfcTWDzhSXItFH2X/pqz/oaGUV
        k+7OJl0KVSc/
        =Jpl6
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-07-12T03:28:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ//Zl4z57JmKbNbLnFtqgwMNFfoOg5WPPIIShq4in/H51MV
        pW9lqJo4LhY9caNz3zWOIDQZ1welEL0G6PqxwOq5WrEbGz7KugsS5LUli0ddRDE3
        bOKV74zgzcaJ+l2LHkUIlHZLOnG0FMOUiIiGbhJJFad+jSeF234xYNFkAnd2n4DJ
        WqyYjMGZ2ENuLPj07WSZAbaMuqienJnmtgR3vIUp9/+byMPs30WWehqTZY8zRhK8
        OYf+YvjYc5FjMIoSvwr8L+mZCjSpi1g6auo8nVvfaR4wcJ1iFYJVd6UZ3RpsmZm2
        3gCra29mBGhrkN2/nqVEdjQazdko6T0EYhVBZnFu5z88Usqk7tvUQloTIfWy8UrI
        LXsnI++E1w40Ra9okqtercMiLU62EUnGH3VHjrzxNd2pCBsetOFeX0bTqpSF5juP
        OXc4cP4f4D4UVjn6X6AOBpxWxZyuWVKk1kJwTfwSd80TCotcBf5o91Nh36oTr0kv
        4wM5K7bsEUL3ObGd07D4Zmqq7vvqxR784y+71/ywGYkbrV9pukiRfB2dBnJDSfJ6
        e6n8+Zdhxgjr8QcMBTXAmQ9N9MAqpsGtuI8Ki+9q2bBeYTbLirl36Qpq3FaOjF5G
        GNw5+tji3HdLLkA02EI8lVnzMH4eGHLN5+Zm9hHpENQg87LR6oR28r80cuD0KzDU
        aAEJAhCIvNyAO8HRGh62/WlX4YSQVlenZUYoi3WBwIwMYXvubrLIC8WsRsPsbwhk
        mWhQS6LnABjJVYMWjPKAqJ7yqp9hiGT6iEuSnbgBED84wS2/59RMl0b3/V4k4QT5
        WbXetWKuLh0I
        =4bkh
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
