apiVersion: v1
kind: Secret
metadata:
  name: mullvad-wireguard
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:ULgpdOI2ie0eccVc2CdpxKQc15P27gSv6kRjUKGiYg==,iv:d9HznR5m++3GRt4pmT4a7qpX5zopgzyfpL8LeXEVrBE=,tag:OF8EPRydOBQP85QSVIarVg==,type:comment]
  #ENC[AES256_GCM,data:E5ksYZFbdh39kC6kKqCrig/BX8Hp+/HRp1D0uF/7DjMNgA==,iv:sfew8EEU339aPwhD/35IjxMk2QQmcakfFOpdjTLOwBc=,tag:z4iNDc2L8gjdg3tKaom/bw==,type:comment]
  privateKey: ENC[AES256_GCM,data:43qvpSTsKsNz5BcRQcgkVjQZFhJdHvqAUfBxpgAJx2vnujCjIgiTkbYQmH0=,iv:aGHia2OOs2QlTR5QzqNTii+cO5EDSzW2dB3dIwrgBp4=,tag:n0DVZlr/W4wcgbotLaTFxQ==,type:str]
  addresses: ENC[AES256_GCM,data:iTZIZkzKeLawib5SZy/00ZDXRyjg3MMAFJ3q26Qa6t6G3C0+t+aUm9LFeUtVXiI=,iv:aQJSRJMA48A8kl49zN7C4Z9w9hDjQWb39vy8r/+cNXg=,tag:twfrLlWuGZ/wnlQ2fCB3Fw==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T06:11:36Z"
  mac: ENC[AES256_GCM,data:WAi1a9+MO7v0nfRdlFPgW0Q2Frg7VKvhz0FMaaOK3vFqG+5PR0GooycTalWVr9d/Fl549oys6WLxPNSBUU9cq38ooerdYqEBmHRVdieKtjuvXdj0MRMClkgwgPzGWBTWU97zeIEexfkPgPQHxuPMBDVznlvckixyKd1FpyfvPDI=,iv:aDV8yyobqZhPlQQkjkYPWEQhw0ze75gOafEs1Ru4zXY=,tag:oFl3zoG8l2L/636Vhd3mug==,type:str]
  pgp:
    - created_at: "2026-06-30T06:11:36Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAlRKh4P6B3oFXVYXrZjWOBAsfQgKSclhaSr3yk7f1VIKQ
        xf8I8ZO+XyPd6POzIrmNL256gQgg48+GsMMweLAp1SqlyaXSFm/iTkbyLD7kYykq
        YrUg2W8mq96UTZZ9F0DMHpdX95h0fnzW3Ca2CRcOh07dLzJZ/PAkeWn1KLIUBPfr
        v+mneMU0dfmD0usti//+A8yAG49Dt0Rcv5Z10qXP5kch/DtzxMDdAWgFc+OPLQEB
        4wwKjqsZ/xX6WjLgb0j1HIjNfAXDE0vgvBv53KUw0BeSuZAHdEhKSLkVzqH1KjNy
        9yc02uCDH2YRcq+KrLDkumjWg9PIQ8sDqZxSZ5u0CCm1YK6WRkdXY1ZvWv9oZLMf
        OnERtFM+cN4ZERwMrhcpye0u1dSExiXhZjHjils2KE3tD4ZREYxtQMLuNaG52F54
        4KT6VVOX+bMaKkORH3nyL2qgJKKTAPRTdhCOUfGyYLgPei2aQ3k4emps/4pyPj51
        2DX224F910ap+BDOD8iZtIEkX2iOnem90KflXmRfhdvdOc2DUbIsBNCvC18/qsNf
        ODYqo1b5J30cxnsvqcgfsc1hvbg12NcIGUUi9nCjzOlIK07U87h+Pl4zQ1D2288a
        QyyUVHu3P7sGq9pUrhcTDoj5VbbVcLshOlEwqjoQAGmCmPZTBw0Q2EUNtbgTadTU
        aAEJAhB0EEGg93RBqxuhCt3Ok6ADKFD4yYLpeIfZfxVShB/rBj+ZZRDRAiETyJS7
        CyWSP/tmzvLJAsVvE/GEs6fD3drYEjeMucVfzFvb8yiEwlJ3f4DDE0aps4CAv1Nw
        aKIYp8m6Cwav
        =DnCO
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-06-30T06:11:36Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2ARAAslYC3zPOFn5IAE3GIbLG4oWMWxFCrzRHtalGz7wtiQDX
        QL/gnXCNw2xHWO8cFTBqlY33oWKpbOLBdMc16qn8HNYLWMEc6jF6xcnVFisMBHIn
        Yyl8ZFhwbyL9DKnFk8eq/SZIr8jjZSe0g6QsatzBuYQvz76LWV74GqPEaXKk9p2T
        PhMtU1I/VozghzWUSkx+KeDZxRtt+ZX1Pq+Mz3FObPEs12iuIaKoTBHGy8CpBfc+
        aH3BOGRrPZojn9A6A8oYpgE0Pwl+tgCfbHCGQfldUD6kmiENxbPULKgHYHA7awaG
        B2CeEc5GJC+EIhD+xnGBL7ar9NryrEq+IPfRjo7WKk0szwRzFjXcz242bPP6z85n
        3JTz6JeyLj6Lzb7HYC/zg+kKzRWmToxgp/2Rk8OWIBwoIaFJs9XiuQxrTvmxtrHN
        TGwo3fz6bl0L8fUhKqm5MVCfbcKlLtBeq5fepthLPo9ol0zU1up2bIiqCBX238Fc
        FkSO+lN+UJKnumlZIQbF9s/cg6xexMS3pX34iPJpnRZvhmqCA5LrPSeMkpTSFR/O
        cCMoAUhaEhe4+k9jBxRET/heK7O5PqIYLNO4Mp9M4dR9ibRTwkKofYEgReF8Z96L
        FNwyw0DlvfGY9ecn4SaWvjR3w9p8v2dnHC/8Unwb9f6Hn8bjcjWyv4UET1ygAEfU
        aAEJAhAbwQO0Vh24n1zrxDUfDTilG/XjwkaxfnZSwZ2mCeBYQdtxamldnoWisLVi
        ECZiRS47AMJGL0lNHQkB5kdv7vraL3NKYaR2UjGxx20FaQZApnY/VBEFz6WRkCyD
        J+mTV+pqfqnp
        =bUZO
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: mullvad-exit-node-auth
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:41F93UrZwdhr3T1OrAPO7WeIZuXpgqHsW9gP+hn+YJleOfW7yXL4aaxdU4GSojfm,iv:z18+ma8c30duL2eTiox1/QKyxwL1HAKNd4NHxOGHACk=,tag:ZyC/UWL2AG2xdfni74QR6Q==,type:comment]
  authKey: ENC[AES256_GCM,data:zD/C59oJkrBR/iAk/Rwu279OdgBVQ88Sp1+nSBAYwHxNWx96qzp8yIA6Wyp0jt4OmwaR2FU854IcpXsQsw==,iv:SNEl15PqE985wvT9TQGfLonhsWptLV687hVqGwpnGiQ=,tag:8Qd4hVngTYcmtjLgBz1Crg==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T06:11:36Z"
  mac: ENC[AES256_GCM,data:WAi1a9+MO7v0nfRdlFPgW0Q2Frg7VKvhz0FMaaOK3vFqG+5PR0GooycTalWVr9d/Fl549oys6WLxPNSBUU9cq38ooerdYqEBmHRVdieKtjuvXdj0MRMClkgwgPzGWBTWU97zeIEexfkPgPQHxuPMBDVznlvckixyKd1FpyfvPDI=,iv:aDV8yyobqZhPlQQkjkYPWEQhw0ze75gOafEs1Ru4zXY=,tag:oFl3zoG8l2L/636Vhd3mug==,type:str]
  pgp:
    - created_at: "2026-06-30T06:11:36Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAlRKh4P6B3oFXVYXrZjWOBAsfQgKSclhaSr3yk7f1VIKQ
        xf8I8ZO+XyPd6POzIrmNL256gQgg48+GsMMweLAp1SqlyaXSFm/iTkbyLD7kYykq
        YrUg2W8mq96UTZZ9F0DMHpdX95h0fnzW3Ca2CRcOh07dLzJZ/PAkeWn1KLIUBPfr
        v+mneMU0dfmD0usti//+A8yAG49Dt0Rcv5Z10qXP5kch/DtzxMDdAWgFc+OPLQEB
        4wwKjqsZ/xX6WjLgb0j1HIjNfAXDE0vgvBv53KUw0BeSuZAHdEhKSLkVzqH1KjNy
        9yc02uCDH2YRcq+KrLDkumjWg9PIQ8sDqZxSZ5u0CCm1YK6WRkdXY1ZvWv9oZLMf
        OnERtFM+cN4ZERwMrhcpye0u1dSExiXhZjHjils2KE3tD4ZREYxtQMLuNaG52F54
        4KT6VVOX+bMaKkORH3nyL2qgJKKTAPRTdhCOUfGyYLgPei2aQ3k4emps/4pyPj51
        2DX224F910ap+BDOD8iZtIEkX2iOnem90KflXmRfhdvdOc2DUbIsBNCvC18/qsNf
        ODYqo1b5J30cxnsvqcgfsc1hvbg12NcIGUUi9nCjzOlIK07U87h+Pl4zQ1D2288a
        QyyUVHu3P7sGq9pUrhcTDoj5VbbVcLshOlEwqjoQAGmCmPZTBw0Q2EUNtbgTadTU
        aAEJAhB0EEGg93RBqxuhCt3Ok6ADKFD4yYLpeIfZfxVShB/rBj+ZZRDRAiETyJS7
        CyWSP/tmzvLJAsVvE/GEs6fD3drYEjeMucVfzFvb8yiEwlJ3f4DDE0aps4CAv1Nw
        aKIYp8m6Cwav
        =DnCO
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-06-30T06:11:36Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2ARAAslYC3zPOFn5IAE3GIbLG4oWMWxFCrzRHtalGz7wtiQDX
        QL/gnXCNw2xHWO8cFTBqlY33oWKpbOLBdMc16qn8HNYLWMEc6jF6xcnVFisMBHIn
        Yyl8ZFhwbyL9DKnFk8eq/SZIr8jjZSe0g6QsatzBuYQvz76LWV74GqPEaXKk9p2T
        PhMtU1I/VozghzWUSkx+KeDZxRtt+ZX1Pq+Mz3FObPEs12iuIaKoTBHGy8CpBfc+
        aH3BOGRrPZojn9A6A8oYpgE0Pwl+tgCfbHCGQfldUD6kmiENxbPULKgHYHA7awaG
        B2CeEc5GJC+EIhD+xnGBL7ar9NryrEq+IPfRjo7WKk0szwRzFjXcz242bPP6z85n
        3JTz6JeyLj6Lzb7HYC/zg+kKzRWmToxgp/2Rk8OWIBwoIaFJs9XiuQxrTvmxtrHN
        TGwo3fz6bl0L8fUhKqm5MVCfbcKlLtBeq5fepthLPo9ol0zU1up2bIiqCBX238Fc
        FkSO+lN+UJKnumlZIQbF9s/cg6xexMS3pX34iPJpnRZvhmqCA5LrPSeMkpTSFR/O
        cCMoAUhaEhe4+k9jBxRET/heK7O5PqIYLNO4Mp9M4dR9ibRTwkKofYEgReF8Z96L
        FNwyw0DlvfGY9ecn4SaWvjR3w9p8v2dnHC/8Unwb9f6Hn8bjcjWyv4UET1ygAEfU
        aAEJAhAbwQO0Vh24n1zrxDUfDTilG/XjwkaxfnZSwZ2mCeBYQdtxamldnoWisLVi
        ECZiRS47AMJGL0lNHQkB5kdv7vraL3NKYaR2UjGxx20FaQZApnY/VBEFz6WRkCyD
        J+mTV+pqfqnp
        =bUZO
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
