apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: infrastructure
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:eEnKOGwuog==,iv:ggCt0IXjhJ9R3++Y4y4UDACO/oupxumYBYiyke1ipus=,tag:bYWKdGLIl3QZV1gtWUtExQ==,type:str]
  #ENC[AES256_GCM,data:pKzqva4VEN3Y6Pgu6G2DEOCcDm367FGHVVlsHU5QN2DHC2n4JyTyCjnJowkBKEZw5jZDTjnD21LKrsS17A==,iv:cS9pIdkhaHDheqWaBA4h67fl/Pl/eTZkEsBmj4+hqu0=,tag:w0rYgm0ZsxdxQpZMMGeJfA==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:jbadnurc3s/qN9CXJ1jx9SbGkuYqo26Se+hJN5esCjc=,iv:S8QcaGpDsyuf3dNruMbPGHzbWkxDZFILx3FBEKj9ALA=,tag:QJx+xR94mLOQ34uFScVfnw==,type:str]
  DB_USER: ENC[AES256_GCM,data:pH5WT+HdLw==,iv:A+RMAlvaCftDy/bTFxgzawcyg9dVipSpI67ruLVo/ec=,tag:1Dfmfz4C67anSc7lmFPiFw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:RXRQJxM7OLgazDIydD6Qm5rqBbG0U9xhDZfhLfDchdM=,iv:yP/X+bZVnpiT4JvhtwWas8sVlD1YmBY1oSWB5bD/ucg=,tag:A8kzCX7rPArAU75qbTdyIg==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T09:36:49Z"
  mac: ENC[AES256_GCM,data:ptweSyf3bWNfPf1DuSRKtPP2cPPlee7iKnJqd8hThYSzqte9lE9uKSDEVIhSlGghBBwPRnTTapSbYW1gHCCYDrloNFkaVRkJoQITuUMXWMuc79/3rYWopd5TpJhgLqoEFYlWSQrv95NVHNr+60FEFGIm/rTezhISfnSGxlVpyas=,iv:DF47IpWyVPi0S6ND0IkCgZL3oYJ4nTBMmbSHxZ0bNnQ=,tag:dTbYkwA4Y9tQowgQAGT5MA==,type:str]
  pgp:
    - created_at: "2026-05-23T07:22:41Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ//RoOGp/inIRebNNrBG3d9eeytiz1MrSd2loqDuX0gJSM5
        R4jXyP1x88YiauKF2bRVI3mA01n0FLa9M6o44+8cLVfwSwkchHG6Glwn3rV7L+Ky
        d+uJGeOOJWUOpRW7s9QG2iRdr3ZzU8CWdxyHgnnyYW98OxNFrhXGCDN/XT5O0QMT
        UCOhEABrCSSbHwef72qtBlDDdZg3enZ6AGYRlBLWrjRJjvYkXoUAzQF4WvvK7QUf
        KQm5XF7+X5uA4gDlQwtq1q6IzC2BJbhtyVXzZ4oZlu0+3XGb2y5DNSqM/h9/clgl
        S2kGxAe/SDr8eFY5CBn3zuXZcj6QyiG6PKygeGhO9fymC23NLVdP3B8Xgts6MEP3
        OhWH0Hw7Dwme1CtRlvArsI9BjqCJMC96iiqGa6Jg1YBgMZal2pf4WpZN62dDvzpg
        QIXqWEahLPK1cc+QL/C/fCI6LNgc/WRUuwqHjn9xXCta8Ie3OBXaTWnMY0h+YiW2
        PjxV188EHdrd2E4uWchZUPB56IvdzWAo27mX7fvLzh3WcuQQpMrBSQCBXPqG2DGq
        J7BrM04z3dmCbDVT5V1CfBx5Jac8On+bpqImBhTLq2stmo8y2I79XVJ0MDswkc/h
        uxA9IzBsBG1ajBtLGfebZK03a+uRPf/DLZ+KZWb4nI74RwlU1neehL/yEwBuSdDU
        ZgEJAhDO368AlpGMpb/HWbgFyw1+PR1k1eytWTjNp/nzMf+PCkUfNKwF8C+GjG2I
        8ji+lLnywDSJ57Y7z5fgNAdi8nYf7SPFciW18lQhPzf1n4N0pxz8pi9zUn2MuY2i
        ucAaqrtDwA==
        =Cfvf
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-05-23T07:22:41Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ/9Esox7JVcEU6fN/+RUNWebTQ2TVoV+oez6QrqRvXlLThM
        mGfnb9d5WjXvlRAE0aW19GAl+iSbfoRat3z+uB1m9JADE7BFKuTAuoBMXo3UAqQN
        yWmM8HOhPmkIrxVUUtP73qKm3XEB4TUNpuSD7a2RHTF/JIXwlL8OCrMPknoz9blc
        F1oraxOyQgKGgAPc9pHrhTLLTci/xFryEWqvb0inIaz4nMcRXBiQ/D0CphkpU3Fs
        d8HQB+QUjD7KLBYMvPYW2MggnBaBN+lbbzbV4Y2pPGE61vHhAid+i6nLGnxHle5b
        sx6PEmzgD8VZD2jh19+kw4ukSntqrc4Nq7UhEsAMPV1IXzU0TBNXaXs6CGkyP8kF
        R2A9tMrI19nU6ihjgoQgu0lR+Qlp76t7aL7hnGxm+dB8cE7O4j2tkru4Y6ZWkqN0
        Lcn0ZmgPiiFYlY2V4+cBzGl7mQC21f8jPdw+EbWMOyxhGH/7zwX+1jNvpCOOzsX9
        J1U/zAoVExMGAKnBUe0S+BNdwroomKDps3L+lPrfOwc8FUo87GoyBqUysVszzJ6M
        2iE57dMSRXn7SJTNuKUufYK6oO6i8s5tMn9iXpPnPYsSel1PaEYtZVZjlR4JZP3c
        tCD3OGa8iu5y8lQmVkyR8xk9am/VBwEofirIIMAQLi3kII6zvs8O/aB78kNzaXfU
        ZgEJAhCJQBgAlwYyZFtqDtRUgPe79WVk/2A6175RaZX8ioaF6xp/M3luSc1DAA+g
        0O92T9NoRBQIIlYmEctVMOt8XryfvhXCiqKtilkpiBdPm6m6y041IkLyYOgwyALk
        ljnZ6yNH3Q==
        =1sPz
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
