# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-shared
  namespace: production
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 5Gi

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1.5Gi"
      cpu: "1000m"

  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-creds

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: instalock-server
      owner: postgres
      secret:
        name: postgres-creds
