apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux-system
  annotations:
    # az identity show --name kustomize-controller --resource-group k8s --query clientId -o tsv
    # this is managed by `platform-infra`
    azure.workload.identity/client-id: f2a95c59-6392-4133-a670-e1731411404f
    azure.workload.identity/tenant-id: 88e5fbad-e2c7-474e-a963-2fbe9a0bab8f
    azure.workload.identity/service-account-token-expiration: "3600"
  labels:
    azure.workload.identity/use: "true"
