apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=tahmid@tahmid.io"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--metrics.prometheus=true"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.fields.names.ClientUsername=drop"
      - "--accesslog.fields.headers.defaultmode=keep"
    ports:
      web:
        redirectTo:
          port: websecure
          priority: 10
      metrics:
        port: 9100
        expose:
          default: false
        exposedPort: 9100
        protocol: TCP
    metrics:
      prometheus:
        service:
          enabled: true
