apiVersion: v1
kind: Secret
metadata:
  name: codebloom-scrape-creds
  namespace: production
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:UqAOrfsm/Lg=,iv:59cDGjiYM5whRpPemmt4kqzyCOujD2eTdMIPs8iGPp4=,tag:OToMm3ihdWcrl6xMO72exg==,type:str]
  password: ENC[AES256_GCM,data:V/MVW/ygsH7lLZxF7vQi7Dqrvdb7FkUpWAC5IMb16i+Uwje/ijVivXg+U7PQ6b2RWfVS+F8xciSzd5qVYux1vg==,iv:K7HwrXo2r58qppGFBfvI/Ocfp/aZfuLSMeE83rA9+0Q=,tag:wDM2Gj2qatBBZN0oJyDx8g==,type:str]
sops:
  lastmodified: "2026-02-27T02:33:42Z"
  mac: ENC[AES256_GCM,data:dSzfU0UXt/V4mvbjGibrp9uwhrpWNaJ+wGNJK2Pe47SmA8AnTKk3pCNg9xMIcVeI2sAbR+LbZK8O3lJc2kIvnGx1HZTrchn1KXn3rEDp4UiNi04NX0dicQMSmKy+gVuY4NBQnYTEn982NZXMzSFQJWiqaYbVLe0gIpvvVUM+/lQ=,iv:UDj3mVGVF6udlwKSoTL3Sd6DRx8Xx6UG4alBvhRziSc=,tag:emFWM8i64wgaqcBY7xhkYQ==,type:str]
  pgp:
    - created_at: "2026-02-27T02:33:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAlKIhNA78zT5QXkHnqkLFIdkqDJEKKz/XSTYfK9zoWzXe
        fTek3FV2eUGMyQV9HNH9P2NYvzCbe7UQHBxfsqWIWYcpsyqdAElAO3SPgNh3nkW4
        h3xiIy+bb/djwSuQoqH6e3155IqD/kV1OE3l2ZMuF32Kf0c0pEY3P3/KvuGtAe9k
        fN2x2vce9mqlR5/D7woGBRBKWXwBFUT6NBW1vc0rYvaEmRUfeOtTXUBoapljqjEi
        L2kR5p6JdR6LMYONyHBUA3D1xmYJUWEZ4sYaJm0bgqd1SMjFRwZiiT6Cg2vXRQ8l
        KDz5ngKN0ooHc1iJnagXH6GCowIOSxc5twaeBulF8H98jvrfllq8O3sj3YsMxcvZ
        8zP5Qmv2ciGkf4P89srvPyMZvbqXtFMYma0kGIAz0vQJpae8LtScd+9589tYVJUE
        sDL3gIi0z8DBWVn00oTUeTtPkSRVabfM8fU7GiUoTAbtXd8rBO0Gk0KlRDhLnOsS
        9+r9zbEYT39PSzAR7q5XhR378y5x9vPHGo4E9cqUGutW6rWK6sHk/ZjJ0O04i3fz
        ZvkEKISX2yNJH0Dtv60yJjnNmvQadA7pM08uNX/6tN2OVS7k3CuLSddW5mWoRtMC
        qRGZcDxCda0QrtoGR7sWXDIHaXXRVzvdt/xlqIVayyManUNG14rdUPHLWEhD1y/U
        aAEJAhCLhaFB7T4mHanOPeXvPdtGTtSTQx/eyeUKjq88yIMKHgkJ5vRY+Z+D51PV
        XiaT6h5ONUYWWxTvvGFDUOrUjWN9DftNyA/8g7w/DPYWE4AZHKAtUqsmc3LH+/nK
        BfyMNgOK/Jcr
        =Nb8w
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-02-27T02:33:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ//bbTWHXrdq2K2YVxOErvi0kJlMqdxtnqYo7cvIxoBOLg3
        uftSWpQZwmLDCKUTMNXZ4f7aXqDM9t27N9E5g3bcVJSpdCgC92FWvwm1zys3xaWI
        QRB97GhA9Z8yNdK799SHV/Ex9VYHjzW3/xAWpxzN+DwrWPXApJW7HBI09OzsRiiu
        KFsceuW0jVqzq6Gec3ESZPKC1tnCyEeTQsXy1BDWvmNyRraIVEWNV4Sl2I8btpVx
        geHJYXL+ttZG/1cguxpsgd3TmDDNm7epDCQT1+FMNI9zKqhEgQjj9CALTgyknxdK
        a1cKql6ReSFmXVOexnPMU4j9ZwZYu+6NkVEoX37tHBZ9+rYUYDpYx2kc6t9WaK8Z
        x8q2VJRcmwGJA68HQxUa1WKEXw9CVNP5CTtQWf/4orGisnjJfCXWOAT7opmm1u2W
        imCBB1RRxQdf1Rwl7iWbG3LHhF4ZLawyaWjhSguXMb6bpMqhjGoa95HMnx0QqqYG
        pxerkeHBUvRF6HHrjq07R2mUWR7rphpRDjUyxi3oXsw55e4z4bpee/n/8JuVyINW
        11SRrkyhjLva7tiJ75dFf/TIOMjA6JHJnYFbnM2AguIARZqph8bDyivyGaTWHaJG
        HLgzg7Y2Ws3D7V4Y4TxhrfITg46jdrE9kXwz9OaA4mj2M2qzb+h5b3eSIb6oonrU
        aAEJAhBDZLOkHTW+9nOZ05wbOm7NQtqJsSrhyoB3HzboVSSmFxf9iSd21+7JozqI
        xAhq2hghZLF3MVzwAFJ7DSZ/3QfVCCBmAKXQy7WYVcavxfnTnnvghJXbv30suou1
        bAraxzrEmtZd
        =OoiX
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
