apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-k8s-tls
  namespace: infrastructure
spec:
  secretName: postgres-k8s-tls
  dnsNames:
    - db.tahmid.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
