apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-exporter
  namespace: infrastructure
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex-exporter
  template:
    metadata:
      labels:
        app: plex-exporter
    spec:
      containers:
        - name: plex-exporter
          image: ghcr.io/axsuul/plex-media-server-exporter:latest
          ports:
            - name: metrics
              containerPort: 9594
          env:
            - name: PLEX_ADDR
              value: http://media2-egress.infrastructure.svc.cluster.local:32400
            - name: PLEX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: plex-exporter-creds
                  key: token
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
