apiVersion: v1
kind: Secret
metadata:
  name: plex-exporter-creds
  namespace: infrastructure
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:s9HDFwmRUjLdnLoihgeRGkC/xp0=,iv:7JcV92KFrfviDqhvawHFB3BVPIrHVaEZVR79+PNM3Kg=,tag:M4+mMppTbX/wye5tGpcI4Q==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T05:49:49Z"
  mac: ENC[AES256_GCM,data:bKGYymOTa/opHcYuqqb/4buMXLa6eJRzUdGiXKe+8X0b4hkLwhSarTmdT/grYrdiMYow64os7IVK+grM5L+Wi3MqEYOfCkaGbHgSVuodPtu8QncAH5GKYkjkzwr8GPkJoAiWIsCofBBYmznbXlGeA41tElfVnVZGaXVTr3dH4f4=,iv:8UxxwfMMjkRpAhhZ4/B4G3HfIBcuQzcDrHfvCv3Uv+w=,tag:rKVobJQPYf89wHliJpRZjg==,type:str]
  pgp:
    - created_at: "2026-09-09T05:49:18Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ//SoyAON/cD+zz0SXQR44UPPOmJR7JpO1pfoJkq7GxZw9n
        /JWFOvGv97tzjqCcHlha1dr/yEWX96lPJvnO3F4TAzljRZKxO5CXsnJyJ3d8Zb1C
        LNpXvT/uv1Q0LR//1to3qJEfMejwA0Kjbl8sWoOF2taqL3YDjTwbr4tS0kw7OKwL
        H4DuQB1mbr2VHCE1gdRI8ixM1CuIAwfMsjNCqJyjLB0sFkymvbCJSZrUTYZWch5D
        iKKQzb/0RVP31qir4p+rdLirb7CM9WDpexfsMclVrK12Oi7KcV4H1W/qZ3QJY2oO
        weNel9SRfM9V0xfBBp/cpFyQL2+PtZTJ+0WpLLw8TRxNHu9ksknKF44OWpfbnSV8
        RCXowcPVVJrNxvLIF5Qx9Cl4wet1+D0H+RwCh8REJAlPK8WG1uLU0VlzJIl+AIku
        Jbch8y4b0UgJ5UcySXxaOtGNgtG6ixb+o+mAZwRiGgx/kIkOXq6DE2pdcqDecJ0n
        YTRgEUAG9LS3+DodksppvYFoQV3vOse3dxKdAyieLnOplcjhresWxNFav7V8esI6
        fKw6GGQTtMv76AjZxTyWeSFNPxVXSOa8aHf/nhe2v7Z+9xlL0cR4Gv/OJ7lk7eSl
        ES6HhFQ2vHuGe3ZdKizjZv4B4oywbbBoxbmHJQwLK6DS2But60AsYVtuzI3aAzzU
        aAEJAhDV/wUfjXoFzzdylxlHUik7BV9iu+8mcGf3DFpfz5UfZsiy00HVWnBNVcde
        P2c/LyP0UIke5IeLgMuco89P0Pyv4oI8MvvNEytdjU39/s/q2b3kyZi7JD2669ko
        M9U+YpazoxWz
        =kH/K
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-09-09T05:49:18Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2ARAAuMVl2ZH/R5Hl3ozD1ezIn/vbIH52J6QQ48oz++iAbJAP
        fR85f7C+bKd3jBXwVdzd19YoQ/ckvcePFgHLBFLDNN7HRjsIYCudalI0tRis16de
        CorUwan1AVTbiV57h6oY2YAfvjJIBl82QJu6M3aeFi+/GBgTHlUFg7KZ95vR2j8i
        k73uAo9Hg7LPeAcLHcAmfy9YolZi+tP6bgH7WO50bVYw/67RropIHwiemlKEeodH
        dO1+tdvyshMwUVx+CdJtJHLhVj1i29G3OWZlIMn19rWTZOW7hRIFFQx6xTNnkgz5
        3topz5BCWgEWe0p0UUQHiobvggKZxlqZDXK7VJzyD0lynipMmEHhtuAesIrhETFE
        wMG2K6heY2gu4/P8v1roTiG6CH7p31U78k6/5baxUmiNh+LvZAhBtsP+KtUYXezk
        gDsEI1JMAOFQo7LBerQaa5b6nvTqJJ2ZTBAoL6fe1LvFoKEAv5ShIw5KpXz8BdRU
        CQ8iPmLaAyEEsfgK8KrjpfC7gVO74JXOJo/+5D9KqN+vInfVuSviJEujp4cnC99E
        2vy66SK+rjUzgoxk/amHmQsmXm4oQeXIfO/RoH6elqFkIOXxollMI3ZLXuZYsmD+
        /k0fSEt6yh7HS7eKI608X61Mc/em5BBnBMfFl9IMd4TaEmWMbfxs4q7guwRadADU
        aAEJAhA2+4pkTVdHF1H++G0n0hTBT+sar6InSLPTin4VD8xPyEwzp+NMa31iLVYz
        12Bg877XdUgMYxJetG8sxAebbmSzMoWv3o4AFXvqjOx+SED87DBzaux45TdnWTCh
        6zpJF4eCGTDK
        =vIRV
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.3
