apiVersion: v1
kind: Service
metadata:
  name: plex-exporter
  namespace: infrastructure
  labels:
    app: plex-exporter
spec:
  selector:
    app: plex-exporter
  ports:
    - name: metrics
      port: 9594
      targetPort: metrics
      protocol: TCP
