apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: plex-exporter
  namespace: infrastructure
spec:
  selector:
    matchLabels:
      app: plex-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
