apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sh-tls
  namespace: infrastructure
spec:
  secretName: sh-tls
  dnsNames:
    - sh.tahmid.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
