# internal dns used to resolve domain names that is only possible via tailnet
apiVersion: v1
kind: Service
metadata:
  name: coredns-tailscale
  namespace: kube-system
  annotations:
    tailscale.com/hostname: "tailscale-dns"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
