apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./middleware
  - ./instalock-app
  - ./instalock-cron
  - ./spring-react-example
  - ./go-example
  - ./portfolio
  - ./excalidash-backend
  - ./excalidash-frontend
  - ./abclang
  - ./vaultwarden
