apiVersion: v1
kind: Secret
metadata:
  name: seerr-production-secrets
type: Opaque
stringData:
  DB_TYPE: ENC[AES256_GCM,data:VPsNhgX9LAw=,iv:g6q0WDCC+mEXsQlkqONGBeGdSSMH6PiPOPqXyKXIh/o=,tag:VAb7F8rMLSgif932lEWpHQ==,type:str]
  DB_HOST: ENC[AES256_GCM,data:B8jbVPx6aM3kQi4UvYhmhZZro05Xu6Ay9Bv5XCTQ55QeNIF/pSTsAkI=,iv:wSyL5kCTNmMi4LkF4C4flWOLrgsP4rbYLW0lJXzvEYo=,tag:P2tLOUMM0o1YyHesSMSyVg==,type:str]
  DB_PORT: ENC[AES256_GCM,data:xpmieg==,iv:+KzmvGdqTSGASAeBUeROF7faiLdxfamz5rH9h2HYGWI=,tag:matz9J27J1LV+hDkpdGnew==,type:str]
  DB_NAME: ENC[AES256_GCM,data:hINoE8c=,iv:O10+PVTSmfWsw1SX3dyRXvpAXLcAWSBxtUTCuykSFpY=,tag:SG3PjgErRHl8zb8Sh5fQkA==,type:str]
  DB_USER: ENC[AES256_GCM,data:fxutqO+CG3w=,iv:w5qqhWUXdaUq/crOze3cL/UCd2z98nFYP92uq5kGjeQ=,tag:/DYvfX0Jy+xrkGbAVV0j3w==,type:str]
  DB_PASS: ENC[AES256_GCM,data:XaKalDG2GrnB1+5zh270Fb9TBafAjcH0Gs5Jrr10SvHv5VMCOW2MS9XSu9X9LehBZgiUkqmsJqOLdcUTLU0Xhw==,iv:2SVw9/Mr39lqCwxz9BR2bs+4KTfzlIeG/NP6/gN2c2w=,tag:9uuUKhIbqW+oOtPqVy3/Cg==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-26T18:32:28Z"
  mac: ENC[AES256_GCM,data:9T5YSdAbta2ywKFrsIHGh8Kx/p5VkZRtCqPFfD1+1OFQj2ACMXpwfQPxcNFB3rTvDgAf59sfRK5p6BaV9A3rM9oDysjs9QXb62BBZ8kUdbAFDX55NpkIi/u/LABGC28IcSfHsBtD9qP5MggaofbNXr8pe4N0Q+B+QmuOHEu0Th4=,iv:4SviFflCkBw+BuLtteSS+Q/zsy5AQutlidW26Pq6ZKE=,tag:1k/jifqkO1TgoRIstMqoXA==,type:str]
  pgp:
    - created_at: "2026-08-26T18:31:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ//S3Lew1HCDfAivc6dSSMUArRD9N5+QS3pI+LyzYOsxdnH
        c4RKrGCDVu3kMgI2/z8TAaHC/gAeK6hnMya2qeKGiTarhiGAhp1A24IhvryfzKQ6
        sqQ7sWNUO3Vks7Ar2SiRat4+IWhWlXgGfZU+EJu6fYQkzXUmej9hAM7gdvufOK5v
        pYmdXraHJ2g0epG6Ut2b92nxsfhxp/P8PYCpJN/wynOQlLVC+ENVC2pn3MdfUXfX
        n7QWVH03C44UYUKHm6HJmOBQ9aopMcPnni/NkXntAIvRQ8frFHP3WlMY8wXvntm2
        e1Ee3k+X4z+2768w0Q9DRA9u358Fnt7ShC4R360tj9c1Eo13apeKvsnZMS1PGbh/
        G/fPRcLGoWnwYHtXyd5K0eiMkymtEVe8OySQj6O7cmacNfNuiwjXk3euU7VFhQOz
        C88BoC6jwEZEdM97f9FAoqkQRUj+DgcYMQwemPEutFyrVjvHIicRe1xEapqtShUj
        BJi3EfCnttVAFZVXINqoCVaigEavei11An+kz46KatqhVI5qfsGo4NkgNDK1fyGv
        0iJpbWOp+DsUrxGRKOocb3fb9kyi8Jn8iMcy6jJswNuyuucpic6m3mqxwPm57EvK
        H2ODKnWZvOChK/PAgDWfP4bqzDOMi9WsYHrNa/UyeiIPG5NgFgXXhbZSyFqD0/bU
        WwEJAhC6VKJLahqQsbsRt+BKlDN1CNbhEzVTx87GWR0i9EGmOS/whKaCrHM6rpXd
        6xoiDpf5bQKd20bUTmdRHJqAOw5a8kAA5w2712z6z3V0k8P9jQJSLLCMbOQ=
        =moYN
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-08-26T18:31:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ//ZwoxdysSgK+VqZxeXXqTKVb/xEjkYZQK53ef9HanSmyl
        /h2XvqYDTcbAF2JZt7rM1jRPbgAeJk5UT58qrlLUryEHKoXmuKnM7+iuHph8dtml
        aj9RC7/HhdTZDn8AFxfRT6D2yFBTlUX3/6jDMxTMR3ha6y9VTKpSdN6thVvN1bOn
        TyrLClWvlLrT/1Vl+Ktr1A3Ns4vRTJeehGY8SWap08sCYtZvaYwHZYIfUyBQKlUa
        0qIe7H2rWwGbtu2NNwP7pXOPlGumBBtaa9juioxTdHgwZxYo2OlzzdViWpt6DdVU
        K7cSLDsQCy3Q9OO+9ZF3tfMI+V+42wmaXGGQ6JJSJl1uG+3egShKgpHK0FYjryOI
        T6hEigPU+7mmQWIEUm0SKRQ5prWDeGg5ynqnxaWu2I3yA6n3Lq5Sv2PomJA0tGgS
        PejOqbHX5lHVEtlAWGd6eKQ85dh+avfCC/pUnoE8/9FwT5FIQsEbJKim2UP6VMvP
        pRRtMdT36aaN+KB48uy814mXB+2rgKjhIObBQgh6xyYfchpG5znUdMUrbYu2tsn6
        t3L5sIZPzcLBg3qSvbLC+nHf810Wjtcbn7i7P0xpX/ar0PCflY+wJFMT67fzHvZs
        RAq1DF8/2bjf/WgM/aK+6pa5aA0L/edsfKVZqVnEp+wgCyPcgREZmAdcyKcpS17U
        WwEJAhB2pmCQKvP3YRad/Gr9AvgLh3/PyvDJQVf4l4wwrJjU3A3VlMKN8oXdOJqA
        icHEGwLFjZ99KltkGLRuuDDIBN1ygahDk/lE9Y7QybKxB6+C/VhcgKLIY5U=
        =dLVp
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.3
