apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer-infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/infrastructure/cert-manager/issuer
  dependsOn:
    - name: cert-manager-infrastructure
    - name: traefik-infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: infrastructure
  wait: true
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt
