# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: infrastructure
spec:
  instances: 1
  enablePDB: false
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 8Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1.5Gi"
      cpu: "1000m"
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-creds
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      secret:
        name: postgres-creds
