apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# q: why is cluster split up?
# a: because kustomization diffing is not very smart, and without it
# we have a possible race condition where:
# - we need crds from cnpg operator
# - postgres needs crds
# - flux tries to do both at the same time, fails
resources:
  - cluster.yaml
  - secrets.yaml
  - service.yaml
  - podmonitor.yaml
