apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: infrastructure
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:8VuOX8T8w0E=,iv:QKYyOJp4LanPCt49i+RqPsgPrCzte1/yDM4QmA/5+n0=,tag:n8QzxD5ZAOmSRyumfcE8xQ==,type:str]
  password: ENC[AES256_GCM,data:oLz9Re7H3GxKA8bbbGXhwZ//pJRedkIDMlMoqQB154M6UMHEgKVvPXrDyTPyap7eI4da0XdONQGmaIImRF9eHQ==,iv:jJyuJG1/kAck9I4Bn4dObInRE6pjeYyv4xVxc0Kfyh8=,tag:V0EPHQGqtDwfZFRL7F8QsQ==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T07:04:59Z"
  mac: ENC[AES256_GCM,data:m/Bg/6CBoh/pddMoAdC2zDgM1+Tw1OUpd8e72PnbAKNHcJDxkPgnjELzLkub5TyL9w2BfKgxSEssHILORIT1lPwRn0io6zc3lkEmRxPYWjCGqiPj9qzwfn1d/H5oE+P3H9KbF5T7PcU+wZy1pKUVBHIt/r5laJTzf/mmftQsJ/Q=,iv:GU7TPTfwLuJ8B/2WVCSGlRTcNxoo5BbGiOYXe1dsJVQ=,tag:69VHlm41Mce9yfEUD9A7vQ==,type:str]
  pgp:
    - created_at: "2026-05-23T07:04:59Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ/+KtdGEmZ1KrQ+mjEYZAWHz9/1azpKJTAgZS8IzpQiL6+j
        GF6SuyZH+ifksAfz64halbwtVcvL74UCoeSGJPQlO39bEgHQ+EYtxzBR/KbEVu6Z
        5uONZ40L5UIze4j8p8inKvlvh6xTsSI+THtIAcF2A4sVA1ZuUjp7RBYFw2tHYDOY
        FwDOEtJZg8cJ4vXLNqe1Q9xEPXWFA5FN9c6oSlhAOw6p04D3qOJ76PI1d3YYX6dz
        ApjLk/BxdGevNQh95KRzSphU5MoBl93vG/sMGstRIiZZtaRvQaDtCfhmQFSqcqMR
        LvxKG92VucCftjMpFUguLRBi5cC75UIiyBpepySvhp9SCSBvDjZEgvAoksrfc+1S
        DWhQgl0SzrbIW6Yu5UEAksDMrbufw4TDIIuR6otQbw+9EP7EfBh8yebQkSdiokKs
        lmTk+Y7VAak12328LaQEy5NlBBriAsaAaB46h8vanUw0wjf/lB72pbGcwOLVMQjv
        oOoZuMcd0yCThR+Ao0m0Zg8Z5+KyJkBVEc2d4vL6wT4JMQ0wVTegudRkkvLDh2WA
        G8myUVS6NxwoPPeywZ/zc7ZQ9pMz+Gldc0B1uMEVny1CG69OgZ0QC1laxCTHuHuf
        BBglRnetDu1YXLEcDTNJuLJOKY5vZDK0s0qW5DFX2J/OoDEOic/yzI2PklYj6PbU
        aAEJAhDxzfq2X4r/mWt4pxqykmAuZAaCshjRkarFc2Oei3FA3fI/VCBDgiUFhMpK
        AGP9pxSwvsQV10M7CHRJ0GhMwdgVHxja2SpJk4yFrFC0rTBDRR+dLMMPdbn5XbzB
        1qvWlfnIhSIX
        =po5a
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-05-23T07:04:59Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2AQ//cVUyhX7mYb7v+7Y8/smbWKOjkH5OL7E3ChqzgeOO75PP
        1VIfx6kxvwkJweI+hzcpTtf/e7M04XaTl0DdT6ZEEpC/H2ekiImvzaWc4bMf5hhp
        U5pF3pZHk2oOkikxP78MFomgIGLjRyjSvLWHCyu5Qq4E5tAskQTXgb7AmD9BuWbr
        eRol6d4kdC36CzZ70I3+4dffa446wcIik1SqyYZfV+kIuzU5NfVF6ub6w5IGjRln
        s1RVJ+rwkXRq4Y9yClfxrVNH0QG8M2SAUHhAgAx8eD1ICzApi9QaqCLBTenvHSEC
        E36aGDa5fsZdOtBKo97aZ7M1jwDwfsxqWR0jh1SfVSRiYZeKu1RMH+/UTSZLBSLU
        0q9z5u6cBy28/K8Rue7+v4v1XEydv2SPlK3HixjoJkPeF9lCrEPaGihPUMvcNkjd
        usaVHUFFk9fxnH4Yfn/lXGHX2TYJp4ProYhhFivtVW1uAE/j2tOeI1G4Y/HzvBXZ
        0CuQsTUiRKAA9QUEVKmhlZIB9he9Cutknkp3oEpJW/CZZpvXsHaWJWQL1++0WyzC
        5AiDVoLyvJFWoeF+8UjX5F2SEk4kJsJcDGBN7jZma02lxaCl5JUV7SCWOj3OagmY
        1ma7f8P4QM61dexzBpecSxoXH+gLdYTrBX4PdAv4Krt7Gzu1wnd4aHCmvobVJMDU
        aAEJAhBr3XyPopmTPyW2fVZG4gmnCYVelcVJ2Ew/fns7TgYJjb6AKNSIZg1EGV+D
        LStO4gGfh/7GwTcq+V6XmvtL50tMQ1NqYVLXX3ZiNVMO2EtrQ165ND9KdBM+3o6T
        YEoMe07Lg57c
        =bGIR
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  version: 3.13.1
