apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-k8s-tls
  namespace: infrastructure
spec:
  secretName: redis-k8s-tls
  dnsNames:
    - redis.tahmid.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
