apiVersion: v1
kind: Secret
metadata:
    name: instalock-web-production-secrets
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:BOpETuKdRgkJf7/dUQ==,iv:DBR7nMSXpu3sHYiGDKhv6ReXVoEmCdhOnayrX4HTV74=,tag:v9z86WR2HoreNnN54bfiuQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:2msO3w==,iv:u9k1wpdt7QJtjKRszDrvZFZDvZ6ILeN612uDh+2kCYU=,tag:iJWgncabeLNrK+tOxkILMg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:f+X2F+B8MvrLre3tttFk2g==,iv:msTVIU9Nvh44eNnZc7B4Pnp0nYkegGpVl9WGyG8DPEY=,tag:8De+K1iStCECQGM2pU0n6g==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:qs0DUfTQErI=,iv:XZmus2Lzs6iqBxTFbzxqC8fCDSzdeO93F2rSUbggTlY=,tag:QpNxK8tPlidXAm79qwO2cw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ARjqGBZ92lK/nQUlpLvtA5rhnjjt5OisEv21gDZgADX5N1JI74JriG5wwZK0AOpv65ZD1tQgss5UdAdE46xwmA==,iv:6NxOWowBMiyz1oc42oaP8kM8eBJ5yCdvfxxjER2yFU0=,tag:5FI+KIw/7OFaD3eEHHOCNQ==,type:str]
    RATE_LIMIT_REDIS_URL: ENC[AES256_GCM,data:mMkpbsFZacTM/XMUUhPqVnuHuaJP6N5I0HdqbU5oxyKW2qM9AnyegAVv1544lCjLwiN1a6YtndlznIFG2Rg+J202ZDr990WU038exbcnMiPLIxBbmTD9ad2obQrPag==,iv:+CVLozfk9pxj5637VsLQxCZuDOt/nhEVLJw+Fx6YcFU=,tag:cFTa7hnbLRWZLN/wNvhwaA==,type:str]
    CACHING_REDIS_URL: ENC[AES256_GCM,data:4LS3ecAa8fB9khtIBcN22ptVpl3MIY5yUhBTbsRfPLPeFt2GEnLx2VF4af0bdyS3Xc/eah08mlPLywWGGqVoMby4ePOlwDt/E77oVdi0TQj/jUMxOSEqWWCnw1gwZA==,iv:Ts1Pnhm0dKuNR3IKUOfF2nULEFX/5PuhpikiOWO+f8A=,tag:CuhnITcahSrdB12LovPO1Q==,type:str]
    PROMETHEUS_USERNAME: ENC[AES256_GCM,data:KSuru/lscjQ=,iv:M3Gvja/89BD5L0WF/r4HkZoyS9TFxaiYbG54m944/P8=,tag:qc9aCnujQEpyUGILJM1i9g==,type:str]
    PROMETHEUS_PASSWORD: ENC[AES256_GCM,data:QuuIy5wswvLaldVyi0N+4SJDNe8LxWezSsDqtJ8N75tKBWHjkT4l+OdBvNu4J9RSGHBA/kWLbEUv2q5cYvP6Jg==,iv:LZBgWO30m7NwyaIJZzv66YGHLcq3uDBwiK4v4ror8C0=,tag:Gt9QyopoSVJ5oIgO5U7p8Q==,type:str]
    STATIC: ENC[AES256_GCM,data:qyBLAw==,iv:Pm1feHhIiwS1YZlWL9tLZks7asqFbY/g/r1cxqFDHVs=,tag:/c9at0RCdGMKRkX5nXNtcA==,type:str]
sops:
    lastmodified: "2026-02-24T02:50:36Z"
    mac: ENC[AES256_GCM,data:f9XHrXuZ3C8jAn+7IjhUFilVNG6oS3Cx/jwdpPJNsADBfhgjdvYUxIKqcnMQaenv0gDVMw5xlQydgSJILUFFkTvB/C1DKpv/FHRJluq0F4Cbb2FDbCz9W82x3qFDNi9m+pjLQMLwGK8CKEAI+sANRLx1uKXkQNGrTH8wea+Kab8=,iv:TOnWPyL2B3wLK6peBINyC7ZHThOXPoqLIDX2gTVU7/I=,tag:DAv5rEtahCloW+r1YlATIg==,type:str]
    pgp:
        - created_at: "2026-02-24T02:50:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYgP05NwJ3CAQ/7BGyVv9tvZwLgi+W4PLam3n6Y2g2fLThUrVWhVU6z5BL5
            epZ7RkpMG5TF+H6SCanvS5+i+JQvyoi9YjssyjlJOdXTFCJf0areTRB+jJm2qjFz
            w4Lgw6TKAigxGk9UYXXtZUVufGlQesqPr5x2LviYkA/YEe11tLDQ/wlOBuMGgqRW
            BA86yGMyV/cSw8I3X7G9GXJk/Dgb4SjBpprwx9xo/R16xCebtLDQrb7p4qqHVo5D
            Pvx4B5xoy0HaYd7g1JQy/AHTl6bJGJrGS9fNY2RxMZX4UWvl+MQ/f/ihfC2Bl0JD
            kw5w4DH9Wn4ry2ORkQN7FK+3Jcp32iTe6csKrnCXRsHuNqUlKHwJbBvg1Xov9CkC
            +jUf+5D87PPQ5JAaavoxrikeT+iYhjQoSFl3M6G4FnuFsnOcKfpXfkb4QRnFHawZ
            riakM+6iA48uDed8YiZ9gMjeFPFXBm+8qQQfbnyhFFH54xZ28vE5Ef29OQgCdPtT
            E/Kd/T3EGZbnsFFVAqKs0K+NmOsCSEgSVDA4LQyve8b2QZKbWdjvtFZqvU8MMAoc
            tLNrE9A2Kb9fQC2SlwNskxbVu96J0VsnjedovG4ztARsUA9cJ3D+k9L4HK4DP/pa
            UmAsWVlKWr/tqMxmS+s51UmXaBu889WYUbsftBIKjmDp37vMftwVth346UdD/XTU
            ZgEJAhDMj7ao65gpgak74fCcp30Fqmipmd5iA7vbHmGSLimaWGqkeQ7mNVudahZC
            +dxUzcnOL5Ki5NZ/JnqbdmpA95UXdqW6umH30LqQukJbECzFOv7sQkcA+hmb2JcH
            CcwgQ3Z7Iw==
            =Cwo3
            -----END PGP MESSAGE-----
          fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
        - created_at: "2026-02-24T02:50:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7m5W8M9NGm2AQ//VsZayVSvMKYgledGOsmST0Q+V7m5JTRhnfR86mi+O58/
            vEbySqhmwkQ+E/beHGHUdlJYeyLxHImlN9G/TkzTOp+PWihZCVfcwBz1hwegpj55
            SHUe9Gr54bM4zmMprSPvLBxksrPuFS+BRVQlfoz2uX6RxKa7Bq3qFWUmxmTHL9sM
            jh+Vj7e4FL9nDlzy9vVCChsQSo1rzbLfmD4U52g35h6dkii1iyn4Ar6D9C8Y6b8K
            YuvG7M0dRi/77hiiiqZ2zcg1NBLc4KVNLNEICP3zK97Blqzr82vsI24eh2aJiNQG
            XrTlkDrUkC2TRw3jVzf19pw5YqJGKX1Dt4Sg3daNP5yaTJLT67D0lXhlEJuET1wh
            H7zJA4e0etKj+CtdtWcqgpp7K6SdtGyPioUlnwGu3j6E7ksNjBJl68pXYYV2Cs7n
            bLAnDwqwztp7L2Xu68DKwGAPPCAjEzsUCe8jL2z1ho8R0/H7/gFl8LL4BO9kKrdC
            mZOoS6VC+PPE7gUaiYN4Z4yhWgT3XwXF9MvzyG3nmCWGjqYp/ehJFGBlEASareVM
            2EERdx29xAuf+Jsk97zEpzSVvYIdjaf9vTb6phq913+pwlHBD7lwLvqf7glpmdvG
            c5KG/7trwSk5bd03jm6Drn38e4VVeVBy21l25ivcj/hxyfwE8vgwgw8AopTR7vzU
            ZgEJAhBx4J/xd4JaibpVX+nse5AnyQvP4pNeiAqPjT3Td3K8LrjTsH/w/mIHCI2W
            D2YddUDtaFb7gF3ikjqfZcw6FNLz3Qx8IiwC44xNEtbTXTs9+VcvN/XEpP0tvC8q
            GL0rlMK+/g==
            =DXdy
            -----END PGP MESSAGE-----
          fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
