apiVersion: v1
kind: Secret
metadata:
    name: instalock-web-production-secrets
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:QnvIv1Rvdlc+qSnIDeU=,iv:MAbQDvM5+PGHTQ7/ziI0GzWe2Ux80dL+sTAmXNzaVMM=,tag:7X6rszlJWDeIvriiHZ+mQw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:2Q4Ktw==,iv:FdSrG7xw1sILqlD7dDQjARmr01u4ubmtt11D7KUO5ZA=,tag:ZVUzxm0hr87ntRjg3Wn2oQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:mk1EZrQ5H4e2aYOqm56Kdw==,iv:urxBtuGRSvZ4UrI51nUpLmzsE5sB0gl/ikaTSLJRDHc=,tag:ka7wz/0ZLKQLKd3886xiYg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:Y54f/n5Ueu8=,iv:OxHdK7k4ztuCIkCjQsnCVVR0khXhoQg7mwaruJIxhoE=,tag:7JFRoU63EGBMsfGUVkn/fw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ZFAqDfB2zvyxmnNbMV/VJSSxsgjQNQtCKkbzvsdxl80p9w3F1QjXKfJOjxxybw5g7oKgV5Xy4z7sSX774Dp2Cw==,iv:TbD7V7wdx5jQoqVrg/9evnPzNrDqdZuCWcOJxLTp07g=,tag:AaCZNQ8t+9OIW40Pa3wpTA==,type:str]
    RATE_LIMIT_REDIS_URL: ENC[AES256_GCM,data:IjMSpka2HxtQADEy3Zvhrx/1bb+/RWZLClulQP5yj0NjZgv/P3m+ooQy7UJPieB06IyK+FvUxKARt+bzJfTxLY3rv94ZNCNFi/eQLhgMT/9jRCyLv5wMT2RIbmFczg==,iv:+0rUoqYbEewSAGKNADYbhSqVmL6IHYNPNzRNI/XkMs4=,tag:fouLB0OVf8d5JmzD2HxjFw==,type:str]
    CACHING_REDIS_URL: ENC[AES256_GCM,data:SHlfLA5c2sDHOOZdGkg8WzyEAp3X6dHs62SEmIOo909vcHhWo13cTjWy6pJ5AyRed6FhfOm1TweU0S2tjBj3dwZhw1bxMRV31w+W7BvHJX4U2VgfYYLSVKODqqZ1iw==,iv:LsFQ0YlgOb8j0WpJuQOy46JZ7pYG2Sy22q7Czf7Q5Wc=,tag:/EkQUapP4dqJlzowNkO3dQ==,type:str]
    PROMETHEUS_USERNAME: ENC[AES256_GCM,data:/3gatYGKBro=,iv:rdg1cYPKYJsnV9QbW8qi6ahA+QN7+gr4oeiyYQ8jDz8=,tag:zBoNgfTm2Zi6HoaDGCAfOg==,type:str]
    PROMETHEUS_PASSWORD: ENC[AES256_GCM,data:b/fqNbG8mvujdtFabwrApma7B8jTPqWlN0c599APK/ccPAwzP1mY0guCk5cJDX5CTN0b56QyxMpgT88qGZSKVg==,iv:OJx8nTJeLzsM3vTAk3IQ3cE5ijZDM4QC0aiTKxJvqwA=,tag:gRjQ+Jw1o65WLJcrP2bd+w==,type:str]
    STATIC: ENC[AES256_GCM,data:Bm3oYA==,iv:iOYhlkvVLLOTreCCWYEW/pERtL5nJ4WGf1lY3WaY5Fk=,tag:JzZ1lZQI698WdJs/c5uc/A==,type:str]
sops:
    lastmodified: "2026-02-24T05:27:37Z"
    mac: ENC[AES256_GCM,data:X0mrqZOS2e2bONDN8YCnju7o5GjSO9VhAiQHhpysvSiYV4/qpFz2YfVfuDvxHKp6opXFjmtTyvruatC9tbDUJVHOWOS3AIY1ope15BI00QF7IAYeobrGsQQvBqf73eJPVCtIaDfcvFybfm3+qDx2hGtP4pQ4dOay7m6vxHgBn2M=,iv:6wWrptWv57UcqjHD2+Mw4wZzdsK6qoSWw83QkWmozog=,tag:dH69TuHxd2cVmtnAKgh7Fg==,type:str]
    pgp:
        - created_at: "2026-02-24T05:27:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYgP05NwJ3CAQ/+I84Cw1h8nub9FnPcdQ2t+T7kEVoA5sD8zH4hD4yMNYtm
            8NmdooYVenUg/g1EAqsy8mBKBYGDxAaVo/ep+JLuRPEeLRfBgEFSX93096BTz/gg
            Yk4pcOjXVC4DVvjq91pflRTm/5QWvuzA13Dm2mkm+Zz+F9j2p84mJjNJA0fFc7dg
            F+geG58NbWVBI+HbAzimCY8V1iqRJPIYHq+sEkEXtodGexTjC2sSeC7O68G7Xhub
            LpWQeDfmbTinMfXow+/YKOr0CiOQXGHqp5dvhkz82IbVsel/8Js4ti5B++m7emkY
            3xq6cRFMakrxlNewtzcohKxG1zxn7yefBD6AjC1xuzNVcpF4RJ4GqDEx+UYC0xJA
            2ndjoSt6QOxL6KYfC4voa4UZtvjCGbkhqzF1kmGBG2fZblJTkFkMQ4cJaBy9d0P4
            fwKiSNSYzSZpfIQhr0KKkQS3hKxpD5UGmKH6lfILo0TvyL+efG/yRTuW7IgT3W1Z
            4UQcbok7JPixkZwfuCwT5Fe8esa1c7J6CS6KpVhUhjXp6zDl92r8aJ3XtfvCxREK
            kfiy9P1Gy7/AdD5UAZiS4JLXNZEemyKwwXtuVSsVvWRACENE5F5urGKJ6sdfFspn
            8jFocfpOOSi5j8EgMIBm3KSd6iMCeNhI/2bkUfh+TCwXBT3jNalD6XBDAoSr7YnU
            aAEJAhAt4qID9h/dsETkRrRtAw+hKuLDahMNLlgQ2+Z4yJsglz5m3fkcxK9Cd52a
            P+3W8GVA2s63pLwbCZ37ao9Qz484DvcKBP9d4fduCS7gJE2wf874x7fwMtz+wdV8
            aPvB9caUmi9b
            =UM3M
            -----END PGP MESSAGE-----
          fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
        - created_at: "2026-02-24T05:27:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7m5W8M9NGm2ARAAqGrMijikzerRaRHgwlSIHuUgV8vVnoYFVKQBZg5RdWR1
            dI1SUymHlQGi1qcCT53+U6wnlUxgtnOZRsYheI+I6eEBekPc5u/aCbaZZx86BGRs
            flzUQuBzhqaRQj3VZYneR07TBY02JlWoJE5HQcs8hkHvMJ2IgzIG941FwddcV7a8
            yofhcCaC6/8Ez1QDh79mmoQmoScFTHvociY3lURWccvzrAVK5aBBfGGy0CZHT7cB
            IWr44PTt9Fq16809ztoG5pk11sEWeyBgJTvyEBNGatas+zGhjPcCmFxY6lvKmXjs
            Sz46y0eXtFDCTSnKNKczv5a6z9Zgyj98dQIZn86M43WCavzzJsXhE0bx6iq8pfUy
            fnlfP1PnXdbebYzXke0s34G/0xa4eKhsFd5Ad0LQ4VGOCPSxZzTlnMVEA3wRddKx
            iSoOxhloudZCSmStgC7AR05JLH6PRnI8DSZGFmtdLCc3Ue1AGR30zenrXhcMHic+
            VZ1wyBTTjtbLrR4sxfGx56REySA2L+aF0dUCGTaCS+/LpFI/EntkIX3HjaHRY/de
            +Qg7J3uf1UmWyzBhLNBKo+xOWedUdcQK0ppzRl8XxIZp51+sssZ6ZxRsDSk9gPJe
            47pg30rRNXi2pvDoaB5TAb0NhTD30GrleXjuPZv3aBT2Hm74MpEMKOfeVROm/4bU
            aAEJAhC2Itxj/aQKqxKOtGbBrbkKYOdx7xKU0c1cLIZgjN2HNe+aG4yGh0IAoTA2
            D9w2c99zH/ES2LfQRkyiq2OvAJanzEKQSByTdWQZI0HNHEv6PXlxsQNymb4TzlYY
            iIyufATf5IG4
            =mkAP
            -----END PGP MESSAGE-----
          fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
