apiVersion: v1
kind: Secret
metadata:
  name: ntfy-secrets
  namespace: production
type: Opaque
stringData:
  NTFY_DATABASE_URL: ENC[AES256_GCM,data:7Tppe8NbNwKgfxtG21o3abmwUyi86GKHphZJ0s6Nl+tyGFMqugpOQh/GFu8yH82O+qpK/YcnarZ9cxuuZsYjilQ60fWoijYZ0wR+Bo++Crg+4Y1jB06+vNaFdv0czxqL3wbEdalPlwzSQAJcEgdM/P1YdsXbSCxivDCp3sTHq/flCHIz/pXtH6gjmZlHXg==,iv:Lzn6336oKRnd6UwzM3hRok42Fec7/lKnmhMCYQBbeeI=,tag:+lwGuTsjI87ElNplK34mtg==,type:str]
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:1htpkpyrTjyRV92m0bQ66inujDMfqrhujxrmQKEPW2/UVlUlWzHXa0XH+Hz6OpFsXhm6qFfzU/s3LdpVfUde6ozcWIFVmTVZ,iv:u7gyy70S6lkjuu+yXoxwMI09oM+utwgFYqlCJZaPjo4=,tag:n17UcJNfKyIdxQrYa4Vccw==,type:str]
sops:
  lastmodified: "2026-03-31T15:45:26Z"
  mac: ENC[AES256_GCM,data:LgJvatgDXoYkqHqYT6S0I9iaSV5qXUe6VOIKaZrHHWAisxRz15zZ05r3CLYD+3stfrM4aTngxrpfR4hBh49CaDHq3p1igOniuizXHdkoFvX4n4h10cbY5en9JC8DAqRgpulVwr8n7v8rnKcrYFlCWTlxTvCcgNRXeiyTF7G5WGI=,iv:N9zrUgBxevzcCcf+cCT5A0s8CvB8Svw2kte9QXB+y6w=,tag:n1n1dlyBUp4Mc/Xu05UEdg==,type:str]
  pgp:
    - created_at: "2026-03-31T15:45:26Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ//S8n4Vpq7LTy2VkktrjbqhSZT9rk1E/ddB5GcwwQ3GtO+
        pflb6gXYbX7jSRVXX9g1nnHQMtSNLb5xmXMAJ3cc57eso3ATF54yQsCY6AHMarsy
        Vq2ppNNibo7YKFTVHDhbdm5+o82ueE2SURV5BQn1EVPTdU+i+WfNnFDMMJcLrGxb
        mIcBN60BFVxndrBlCF+0WxPj9i11Z9//xYOpj05KdM2zqbpX/8JQ/ZvZ8CTstk8K
        mNXCaUXbgw1AkQsNyx867jy4Unr+7wwCpHx8G8N3Vhmquy6FxBipvvECgakv+Jgz
        S+RSAGbJHMA6MvBBSTw3mGTlbRYAsmZZTL+qhleaQBnkNz5F2VznZOZELyNpbA66
        KrSLqRxICEODyFzMyrkhoY7W+i/fFA0AnrBMnKBXd7DlHykIObxjygG6ULe9WkZ6
        C6F/QRofp1hmcpb5J8P776j4uzesr8WxrrDraDos8woZyXKdi8Ixi+vVTXzWOKWt
        RbCaEd80duKJZHaGKiQAX7EdyUVQYdSL71NE/dANmMbJE2bUktjVPOH6LV7xA54h
        dMEdSTrhH+7epBcJGJHbcbRjxCHEiLASDsfugO6YFWGLC4iq8e0Y60N8N7og8gIs
        k3o2RJs0d0N/xbQ77e+YgEJ47QG0XHiQLlC1hj5W6x3vw2gag8cNBZX4rjPj3qzU
        aAEJAhCwKJfq559DKKoAXfXqPSZJjwg2tYqQrLV4WT5OT/Ut+Kvm0VwRmgqUUFOX
        L0lfjMZJYIwjDgkeq/D3Ljv9JYp2c0dHq628gneQk3BIFtiZvHRaYg0qShkKjfsA
        22aF+QEFuSwl
        =bdjo
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-03-31T15:45:26Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2ARAAvoP7L0T56QZYG2j48XlCxaAk0/4fz4ke+CYIQj8VYN4U
        GioUIgbnrgDBEUAk4ORXlmV4Ra1Y7rF1s1YDv66Wd9f3enqAOoh8g6LTdHE2uG1n
        3h/hB4W/K9O8PgcWo6wpxgZ91/AW4NDWVJNN4ZlX8BYeoT77CSriHUSidKIeRt37
        wjQfd8eR4YKszKzNtibRUrotOsvBUnbbj35uTNuH+9oUI6iy8C9cv63QlPnNcZ5T
        zUMYVgm64L0R2Fl26YXvMNP/Lh0L1tRxidRTtW2A56h70hj3LPxSvOEZ8dGy2fAB
        MDT0avQS3ze8UA9/l58Y9bsce8tzSEViZTw5E8rBK7mQMU/ofhV2NRQ6PICVyyGQ
        BlBm2PTIPq2G2dq5HcbgtVh6x/8G2pI8pCWMBfpjPutHVzB/kgeqhn4lH56MexYa
        IXZ6TFhH9AbaQxgnlRVUWXtauALBKS4jInjhumMlS41DDEVBmFEMQUIMCUeBSgdi
        MN/voHbzqT5HfCn/0S65HkoI1m1B8rA5ZDpapwXMpTirt/RtsePV+NFqwKeEjgQE
        0zxzUFNUCb+8G3F7FHBHbtgsoDlmXIDSYAuDmZgzFZTV8MFb6FzdDqK2PMZR0lSZ
        TAXAiX9Agf8q0v732YfpXVldyOL5BfnK/LyKtXx6mz+kCF2inmRR59SlQbd8oq3U
        aAEJAhDCdiaJqIzB3DO9JYNSNCEWpemHm0B7F8pO0kODbb39awHD//WVRPsiiyfM
        PeJUq/MUlls7aBqsuWymOVBLS3iZc8QbsCPWuysVvhC+7v/lBM0oPV2b06Wl2BW0
        V7nR5/xbUEah
        =4WEf
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
