apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex-exporter-infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/infrastructure/plex-exporter
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: infrastructure
  dependsOn:
    - name: tailscale-infrastructure
    - name: grafana-prometheus-infrastructure
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
