apiVersion: v1
kind: Secret
metadata:
  name: instalock-cron-production-secrets
  namespace: production
type: Opaque
stringData:
  DB_HOST: ENC[AES256_GCM,data:+Dftwd25F4uHZqGu+CS5v3fnP/TxY3bI/VTcwUASZIRDuoD5fQZVklqn9OGPrOA=,iv:IcaXkVlG05xk7Jzt9+h/fAxDMcio8BKljiplMq5mHIE=,tag:TDHSbR/ZUsxkkM0dx8MkHw==,type:str]
  DB_PORT: ENC[AES256_GCM,data:n5sEhQ==,iv:Wifb06RxJki74mhPQqcIDO01zJt336ywhLhkqNg+5r0=,tag:I7BkGKFmPq+82aPGyPeHyw==,type:str]
  DB_NAME: ENC[AES256_GCM,data:QJ01TzN9faIflIAMAr7KmA==,iv:dAFzOBnd7yDcH9kyZPL/fLQp1s2MhLval20+V9KNZS4=,tag:BBStf41vz6RL3t/9Zj15SQ==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:1NMsz1tovrE=,iv:lnuYoILcN0K/U/gvYlDcCzKSOpMF1sFTvrU8WE4brhQ=,tag:mrCAqHGCufSALCutVneBOw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:d7HwQ/iqrMNnB7Pz4UNpGxQL5DS4FRdJ7bCJfCq8AEwreMN06CBb0XGG6SNQeZt7SGoOMMhIkBWPEtWr5jdflg==,iv:s7pfk5+kTiGV2wn1QRKCLpem7q2oy9neuLw2Ku75MBE=,tag:0NwQG+kQ5WnyRNvAw04qmw==,type:str]
  PROMETHEUS_USERNAME: ENC[AES256_GCM,data:t4xFGl9i7J8=,iv:MgrIF//JIE1wLW0+7HQya+sBoCvL2kenAx8Ml9rNoos=,tag:Wh0U5fCYbwIBlsCZYlZNXw==,type:str]
  PROMETHEUS_PASSWORD: ENC[AES256_GCM,data:ObeouiNFZXLItcdicL3VxGuo5+EdLJYS5JLaYO8FZI3U+AuhjJHgS0qawcReampNKn7dC8jRqcvThahI5OHZ4Q==,iv:oZN4Jkj0w3Bj5cyiA2lC+axNtYjPws/4Mu595z+GB6Y=,tag:Fn0gokKaJdGSCSOXPi6PaQ==,type:str]
sops:
  lastmodified: "2026-03-26T00:09:59Z"
  mac: ENC[AES256_GCM,data:UkRA47TZRJMeh4p8vKv/babq1hefkpD11Mv2sGk/CTlcLxkA/2PFv+E8cFqBqwU07CVG1nXj3Nycd4jNBF8Xbv8qTHSNUhYeheQ4rnzyWPleuQgDQc9TzBEvXv0cU0EnPYmV36QofRWXsglRqi5/131ZSWoRB30Qf/ym6EGSsRQ=,iv:NxEzitWkoC8CoD5RVlRUnVB3VHzS/RXpKGNp59g91RU=,tag:31HLSAKd+Lh1GwAQVPAGiA==,type:str]
  pgp:
    - created_at: "2026-03-26T00:09:59Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CARAAh4QoZi5JB7XhkORNp8WwLTTYU13nPqYtWRXE9eOeIa5n
        fmktvAZu19opakAenvfJjnWIS1G08rzqAEdSKerODyt8zHO4xVH6KnzR1uvBBocD
        iuoxxRyqKrYPP2VnsrWTknXaGGTZkmlPEnVzde61gAzchRwsJF/8OM2204ni9m0k
        nIZJ+N6I+jSsLFVtktszFJqemKPT9QY47B+YOvbXcaukhHKOhDedHE5iFTiipTgL
        jV9+1JBgnkO1/81M0W6VUQoLJFIu5PJ8XyG1ZAiyUeCpWK/fPhh+ebD4E8NVPBiE
        1h9KIgytSRlQDSuvRGWEbX/efER8BaptQ7iHgTG1cADuYY5/xbjmYnxn3AOqlziW
        FihL/NREHnwXzSfIVOs1/NG9YCSipklT17gu3wBtJIzwPKMvhw0way85PCTU3EsG
        CPjBFoulNf/4rqBsbsjuaurQcFmZ0wSd81HtCtYayCRduFNKBDAtj6rEqlzg4eBx
        4ujierpMhEKH+lcl8PbOdNFK4lUIJ62ax4MgTxuW10FwVin5qK4H5ufty4hpJfHK
        ZDIwstMxQsTCPntWBaZbH4H2ZWNTS2pbxHp64J1d8vXxexY1eLgmronWQ3hf2PbI
        178PjrtxoDQEo/pzoVVXjXiojqbyyWoJ+9fqa8H9GfQtYWPbOFxABC1Et4+7oerU
        aAEJAhA97hPT+J0d/9Z3kxtpfLNZIxkm8qxRbz61UMma60+ofIQbJGpabRy1A7L1
        e7VNVWgeKV9U/QpOdGMILjjLoArNLog+opSzcJlWLJWq03JQR0LnpQJCHoivYW9G
        MGsI1bvUrDku
        =A2Qf
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-03-26T00:09:59Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2ARAAuhGTApjRtB3/X0fUbgWjz6nwi3aI/93pgQ3pSDu8ZsG+
        KGPcjR1sv7jlP1tgm9pXc3An/vLzIspn3zQg3SZFbWSneIB6SWj63noHOcM7krjV
        18JzL03KP+qqp6g/UHcene6aw5nxip6yDU5/FKMtF0B18OwaazPTcrlg6SzgjRmi
        h6xWEseTH1OcRcFOPiDAAcd5i/JZECTVvhy+oomVIDtbPXwXQOPK1fDBJpuIBL/S
        nIZEC4zD/XJw5av8mf62WbAJPJ+hhRNI5st7KotmsqiJnHTOtE+x8EenRcd34NDr
        E/07eHff7PUB8BXhQqdnbOXy+VnrkGo3wJ5tAbg6hFEuVwo8sJvyXHWr0Gtr3MZ2
        tfFhvcyQGw5hQkHW7FMoo4EkrbdT8nDVKDSZ8xZNB2PpgDdahZk+lUkB1TZo9NI4
        TLyJUxkUNe27YU2Pshmt83Lhgki5X+sXYLiEUcnuuB0Kanv+b/k/oZW/HjQH/98e
        NTUEbhNXIPsufL+kbgXISWs8ZgOZzS9vcXQ3XjDE8Z/l0tV+0L/OEwf7sdbJm67W
        3H09gBszLt6JUdeXZtlD+t/miQeqGC0ZItV/ogS0DesOLCH3rE4sjvmm98F/bgs0
        5+LTqFYFFLNFc9DI1MpbmACadDKIKAfMqGBZ9OFgikxuT47hDkQS1YrI2WEUNFLU
        aAEJAhDJy3SlvdtoFj1YDN+3x9d0HDGwsOzsLGlFa5elvgO2jDnOtRtJa8l91Hr5
        /kEthmE4mjqkRZnTy5YCpC2fv3egY434NwMSjN5z1ZlMBEWQ3uhiTsI+mAoIF+2S
        XiOUPWpBJKPt
        =9a8A
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
